Let-s-intern/lets-intern-client

src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx

[Feat] 챌린지 타입별 소개 수정

---

src/lib/order.ts
src/pages/common/program/PaymentInputPage.tsx

- [LC-943]
[LC-943]: https://letscareer-team.atlassian.net/browse/LC-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 결제 금액 수정: 보증금 포함

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeIntroCareerStart.tsx
src/components/challenge-view/ChallengePointView.tsx

- [LC-972]
[LC-972]: https://letscareer-team.atlassian.net/browse/LC-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-972 [USER] 2주를 챌린지 기초 소개에도 적용

---

src/components/ChallengeView.tsx
src/components/LiveView.tsx

[Chore] console.log 삭제

---

src/pages/admin/program/ChallengePrice.tsx

- [LC-979]
[LC-979]: https://letscareer-team.atlassian.net/browse/LC-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 금액유형이 이용료이면 보증금 인풋 숨기기

---

src/components/common/program/program-detail/button/FilledButton.tsx
src/components/common/program/program-detail/button/NotiButton.tsx
src/components/common/program/program-detail/review/ProgramDetailReviewItem.tsx
src/pages/common/program/ChallengeDetailSSRPage.tsx

- [LC-969]
- [LC-960]
[LC-969]: https://letscareer-team.atlassian.net/browse/LC-969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-960]: https://letscareer-team.atlassian.net/browse/LC-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CTA 버튼 수정 + 베스트 후기 폰트 크기 수정

---

src/components/challenge-view/ChallengePointView.tsx

- [LC-963]
[LC-963]: https://letscareer-team.atlassian.net/browse/LC-963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-963 아이콘 상단 정렬

---

src/components/challenge-view/ChallengePointView.tsx

- [LC-982]
[LC-982]: https://letscareer-team.atlassian.net/browse/LC-982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 진행 방식에 weekText 추가

---

src/components/live-view/LiveIntro.tsx
tailwind.config.js

- [LC-983]
[LC-983]: https://letscareer-team.atlassian.net/browse/LC-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 무한 자동 슬라이드 적용

---

src/components/ProgramDetailBlogReviewSection.tsx

- [LC-953]
[LC-953]: https://letscareer-team.atlassian.net/browse/LC-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-953 블로그 더보기 새창으로 열기

---

src/components/ChallengeView.tsx
src/components/LiveView.tsx
src/components/ProgramBestReviewSection.tsx
src/components/ProgramDetailBlogReviewSection.tsx
src/components/ProgramDetailNavigation.tsx
src/components/challenge-view/ChallengeFaq.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/common/program/program-detail/section/TabSection.tsx
src/components/live-view/LiveFaq.tsx
src/components/live-view/LiveInfoBottom.tsx
src/lib/isDeprecatedProgram.ts
src/pages/common/program/ProgramDetailLegacy.tsx

- [LC-987]
[LC-987]: https://letscareer-team.atlassian.net/browse/LC-987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-987 네비게이션 아이디 수정 및 초기 로딩 구현

---

src/components/live-view/LiveCurriculum.tsx

- [LC-987]
[LC-987]: https://letscareer-team.atlassian.net/browse/LC-987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-987 라이브 커리큘럼 아이디 중복 제거

---

src/components/live-view/LiveMentor.tsx

- [LC-989]
[LC-989]: https://letscareer-team.atlassian.net/browse/LC-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-989 라이브 멘토 관련 필드 nullable 반영

---

src/pages/admin/LiveEdit.tsx
src/pages/admin/program/LiveMentor.tsx

- [LC-989]
[LC-989]: https://letscareer-team.atlassian.net/browse/LC-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-989 라이브 멘토 널러블 연관 이슈 수정

---

src/components/live-view/LiveBasicInfo.tsx
src/components/live-view/LiveVod.tsx

- [LC-985]
[LC-985]: https://letscareer-team.atlassian.net/browse/LC-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-985 [USER] 짜잘짜잘 수정(ex. 띄어쓰기, 줄바꿈등)

---

src/components/LiveView.tsx
src/components/live-view/LiveMentor.tsx

- [LC-991]
[LC-991]: https://letscareer-team.atlassian.net/browse/LC-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 멘토 소개 제목에 커리큘럼 제목 추가

---

src/components/challenge-view/ChallengeDifferent.tsx

[Style] 띄어쓰기 수정

---

src/pages/common/program/PaymentInputPage.tsx

- [LC-990]
[LC-990]: https://letscareer-team.atlassian.net/browse/LC-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 할부 UI 추가

---

src/pages/common/program/PaymentInputPage.tsx

- [LC-990]
[LC-990]: https://letscareer-team.atlassian.net/browse/LC-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 할부 혜택 스타일 수정

---

src/components/challenge-view/ChallengePointView.tsx

- [LC-992]
[LC-992]: https://letscareer-team.atlassian.net/browse/LC-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 페딩 수정

---

src/components/challenge-view/ChallengeBrand.tsx
src/components/challenge-view/ChallengeCheckList.tsx
src/components/live-view/LiveInfoBottom.tsx

- [LC-998]
- [LC-1003]
- [LC-1002]
[LC-998]: https://letscareer-team.atlassian.net/browse/LC-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1003]: https://letscareer-team.atlassian.net/browse/LC-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1002]: https://letscareer-team.atlassian.net/browse/LC-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

USER 영상 숨김 + 스타일 수정

---

src/components/challenge-view/ChallengeCheckList.tsx

- [LC-1002]
[LC-1002]: https://letscareer-team.atlassian.net/browse/LC-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 제목에도 shrink-0 추가

---

src/components/ChallengeView.tsx
src/components/ProgramDetailNavigation.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeCurriculum.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/common/program/program-detail/review/ProgramDetailReviewItem.tsx
tailwind.config.js

- [LC-940]
- [LC-996]
- [LC-1005]
- [LC-1006]
[LC-940]: https://letscareer-team.atlassian.net/browse/LC-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-996]: https://letscareer-team.atlassian.net/browse/LC-996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1005]: https://letscareer-team.atlassian.net/browse/LC-1005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1006]: https://letscareer-team.atlassian.net/browse/LC-1006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1006 외 3 Pit-stop 수정

---

src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx

- [LC-1006]
[LC-1006]: https://letscareer-team.atlassian.net/browse/LC-1006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1006 할인율 정가 기준으로 변경

---

src/components/challenge-view/ChallengeCurriculum.tsx

- [LC-1007]
[LC-1007]: https://letscareer-team.atlassian.net/browse/LC-1007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 아이콘 위치 수정

---

src/components/challenge-view/ChallengeIntroCareerStart.tsx

[Style] CircularBox에 shrink-0 적용

---

src/components/ChallengeView.tsx
src/components/ProgramBestReviewSection.tsx

[Style] 베스트 후기 페딩 삭제

---

src/pages/common/program/ChallengeDetailSSRPage.tsx

[Chore] 불필요한 dependency 삭제

---

src/components/ProgramDetailNavigation.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx

- [LC-1006]
[LC-1006]: https://letscareer-team.atlassian.net/browse/LC-1006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1006 할인적용가/할부금액/할인율 원상복구

---

src/components/ProgramDetailNavigation.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx

- [LC-1006]
[LC-1006]: https://letscareer-team.atlassian.net/browse/LC-1006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1006 할인적용가 등 원상복구

---

src/components/common/ApplyCTA.tsx

[Fix] 재귀 함수 호출 삭제

---

src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1023]
[LC-1023]: https://letscareer-team.atlassian.net/browse/LC-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 서류 진단 keywords 추가

---

src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/nav/NavItem.tsx
src/components/common/ui/layout/nav/SideNavItem.tsx
src/pages/common/report/ReportPage.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1021]
[LC-1021]: https://letscareer-team.atlassian.net/browse/LC-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1021 서류진단 플로우 수정

---

src/components/common/ui/layout/nav/NavItem.tsx

- [LC-1021]
[LC-1021]: https://letscareer-team.atlassian.net/browse/LC-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1021 토글 z index 수정

---

src/components/common/home/new/banner/TopBanner.tsx
src/components/common/ui/layout/nav/NavItem.tsx

- [LC-1021]
[LC-1021]: https://letscareer-team.atlassian.net/browse/LC-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1021 z index 조정

---

src/pages/common/program/ChallengeDetailSSRPage.tsx
src/pages/common/program/LiveDetailSSRPage.tsx

LC-1015 프로그램 상페에서 카카오 로그인 시 redirectPath 수정

---

src/components/common/program/program-detail/basicInfo/BasicInfoRow.tsx

- [LC-1035]
[LC-1035]: https://letscareer-team.atlassian.net/browse/LC-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 폰트 크기 수정

---

src/components/common/home/new/review/ReviewSection.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/nav/NavItem.tsx

- [LC-1021]
[LC-1021]: https://letscareer-team.atlassian.net/browse/LC-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1021 리다이렉트 수정

---

src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx

- [LC-1043]
[LC-1043]: https://letscareer-team.atlassian.net/browse/LC-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1043 할인율 수정

---

src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx

- [LC-1043]
[LC-1043]: https://letscareer-team.atlassian.net/browse/LC-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV] LC-1043 할인율 수정

---

src/pages/admin/program/ProgramRecommendEditor.tsx

Lc 1032 program

---

src/pages/admin/program/ProgramRecommendEditor.tsx

- [LC-1032]
[LC-1032]: https://letscareer-team.atlassian.net/browse/LC-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 프로그램 찾는 로직 수정

---

src/components/ChallengeView.tsx

- [LC-1034]
[LC-1034]: https://letscareer-team.atlassian.net/browse/LC-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 프로그램 추천 배경색 수정

---

src/api/challenge.ts
src/components/admin/review/reviews/table-content/TableBody.tsx
src/components/admin/review/reviews/table-content/TableHead.tsx
src/components/common/program/program-detail/review/ProgramDetailReviewItem.tsx
src/components/common/review/MoreReviewButton.tsx
src/pages/admin/review/Reviews.tsx
src/schema.ts

LC-1040 후기 관련 유저/어드민 수정

---

src/api/challenge.ts
src/assets/icons/arrow-circle.svg
src/assets/icons/close.svg
src/components/ChallengeView.tsx
src/components/LiveView.tsx
src/components/admin/review/reviews/table-content/TableBody.tsx
src/components/admin/review/reviews/table-content/TableHead.tsx
src/components/common/program/program-detail/review/ProgramDetailReviewItem.tsx
src/components/common/review/MoreReviewButton.tsx
src/pages/admin/review/Reviews.tsx
src/pages/common/program/ChallengeDetailSSRPage.tsx
src/schema.ts

Lc 1040 유저단/어드민단 후기 전체조회 관련 적용

---

src/components/common/review/MoreReviewButton.tsx

LC-1040 리뷰 별에 스코어 반영

---

src/components/ChallengeView.tsx

LC-1040 후기 type 수정

---

src/components/admin/review/reviews/table-content/TableBody.tsx

LC-1040 review content 너비 수정

---

src/components/common/review/MoreReviewButton.tsx
src/schema.ts

- [LC-1052]
[LC-1052]: https://letscareer-team.atlassian.net/browse/LC-1052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] zod 스키마에 optional, nullable 추가

---

src/pages/admin/review/Reviews.tsx

- [LC-1052]
[LC-1052]: https://letscareer-team.atlassian.net/browse/LC-1052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] null 처리

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx

- [LC-1048]
[LC-1048]: https://letscareer-team.atlassian.net/browse/LC-1048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 썸네일 배경색 수정

---

src/Router.tsx
src/components/common/report/DateTimePicker.tsx
src/components/common/report/Heading2.tsx
src/components/common/report/Label.tsx
src/components/common/report/Tooltip.tsx
src/components/ui/HorizontalRule.tsx
src/hooks/useMinDate.ts
src/pages/common/program/PaymentInputPage.tsx
src/pages/common/report/ReportApplyPage.tsx
tailwind.config.js

- [LC-1070]
[LC-1070]: https://letscareer-team.atlassian.net/browse/LC-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1070 USER 진단서 신청하기 페이지에 서류 제출 Radio 추가

---

src/api/application.ts
src/api/review.ts
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/components/common/review/section/ReportReviewSection.tsx
src/components/common/review/section/StarScoreSection.tsx
src/components/common/review/section/TenScoreSection.tsx
src/pages/common/mypage/Review.tsx
src/pages/common/review/ReviewCreate.tsx
tailwind.config.js

- [LC-1056]
[LC-1056]: https://letscareer-team.atlassian.net/browse/LC-1056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1056 리뷰페이지-리포트 관련 UI 추가 (API 작업 필요)

---

src/api/report.ts
src/components/FaqSection.tsx
src/pages/admin/ChallengeCreate.tsx
src/pages/admin/ChallengeEdit.tsx
src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/pages/admin/report/AdminReportCreatePage.tsx
src/pages/admin/report/AdminReportEditPage.tsx
src/schema.ts

- [LC-1063]
[LC-1063]: https://letscareer-team.atlassian.net/browse/LC-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 1.4 FAQ

---

src/components/ProgramRecommendEditor.tsx
src/components/admin/program/ChallengeCurriculum.tsx
src/components/admin/program/LiveCurriculum.tsx
src/components/admin/program/LiveInformation.tsx
src/components/admin/program/ProgramBestReview.tsx
src/components/admin/program/ProgramBlogReviewEditor.tsx
src/components/admin/program/ui/form/ImageUpload.tsx
src/components/admin/report/ReportExampleEditor.tsx
src/components/admin/report/ReportProgramRecommendEditor.tsx
src/components/admin/report/ReportReviewEditor.tsx
src/components/admin/ui/heading/Heading2.tsx
src/pages/admin/ChallengeCreate.tsx
src/pages/admin/ChallengeEdit.tsx
src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/pages/admin/report/AdminReportCreatePage.tsx
src/pages/admin/report/AdminReportEditPage.tsx
src/types/interface.ts

- [LC-1064]
[LC-1064]: https://letscareer-team.atlassian.net/browse/LC-1064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1064 ADMIN 1.5 프로그램 추천

---

src/pages/common/report/ReportApplyPage.tsx

- [LC-1078]
[LC-1078]: https://letscareer-team.atlassian.net/browse/LC-1078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1078 USER 서류진단 결제 전 페이지: 폼 노출 조건 변경

---

src/components/common/blog/LexicalContent.tsx

- [LC-1079]
[LC-1079]: https://letscareer-team.atlassian.net/browse/LC-1079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] USER 블로그 에디터 max-width 삭제

---

src/components/admin/lexical/nodes/ImageNode.tsx
src/components/common/blog/LexicalContent.tsx
src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx

- [LC-1079]
[LC-1079]: https://letscareer-team.atlassian.net/browse/LC-1079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 이미지 max width 950px로 수정

---

src/api/paymentSchema.ts
src/components/common/mypage/credit/CreditSubRow.tsx
src/hooks/useCredit.tsx
src/pages/common/mypage/CreditDelete.tsx
src/pages/common/mypage/CreditDetail.tsx

- [LC-1081]
- [LC-1083]
- [LC-1086]
[LC-1081]: https://letscareer-team.atlassian.net/browse/LC-1081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1083]: https://letscareer-team.atlassian.net/browse/LC-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1086]: https://letscareer-team.atlassian.net/browse/LC-1086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

USER 프로그램 부분 환불 로직 수정

---

src/components/common/report/ReportApplyBottomSheet.tsx

- [LC-1069]
[LC-1069]: https://letscareer-team.atlassian.net/browse/LC-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] dependency array 수정

---

src/assets/icons/polygon.svg
src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/nav/NavItem.tsx
src/components/common/ui/layout/nav/NavSubItem.tsx
src/components/common/ui/layout/nav/SideNavItem.tsx
tailwind.config.js

- [LC-1072]
[LC-1072]: https://letscareer-team.atlassian.net/browse/LC-1072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1072 헤더/햄버거버튼에 리포트 관련 추가

---

src/pages/common/program/OrderProgramInfo.tsx

- [LC-1082]
[LC-1082]: https://letscareer-team.atlassian.net/browse/LC-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1082 OrderProgramInfo programType 필터링

---

src/pages/common/program/OrderProgramInfo.tsx

- [LC-1082]
[LC-1082]: https://letscareer-team.atlassian.net/browse/LC-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1082 챌린지의 경우 결제상세-진행방식 제거

---

src/api/faq.ts
src/api/report.ts
src/components/common/ui/button/BaseButton.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentPage.tsx
src/pages/common/report/ReportPaymentResult.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/store/useReportApplicationStore.ts

- [LC-1071]
[LC-1071]: https://letscareer-team.atlassian.net/browse/LC-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1071 button

---

src/Router.tsx
src/api/report.ts
src/components/common/ui/Badge.tsx
src/pages/common/report/ReportManagementPage.tsx
src/pages/common/report/ReportSubmitPage.tsx

- [LC-1088]
[LC-1088]: https://letscareer-team.atlassian.net/browse/LC-1088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1088 USER '서류 제출' 페이지 추가

---

src/Router.tsx
src/api/report.ts
src/pages/admin/report/ReportApplicationsPage.tsx
src/pages/common/report/ReportApplicationPage.tsx
src/pages/common/report/ReportManagementPage.tsx
src/pages/common/report/ReportSubmitPage.tsx
src/store/useReportApplicationStore.ts

- [LC-1090]
[LC-1090]: https://letscareer-team.atlassian.net/browse/LC-1090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1090 USER 나중에 서류 제출 API 연결

---

src/api/program.ts
src/components/ProgramDetailBlogReviewSection.tsx
src/components/challenge-view/ChallengeCheckList.tsx
src/components/challenge-view/ChallengeCurriculum.tsx
src/components/challenge-view/ChallengeFaq.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/challenge-view/ChallengeIntroCareerStart.tsx
src/components/challenge-view/ChallengeIntroPersonalStatement.tsx
src/components/challenge-view/ChallengeIntroPortfolio.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/challenge-view/ChallengeResult.tsx
src/components/common/report/Heading2.tsx
src/components/common/report/ReportApplyBottomSheet.tsx
src/components/common/report/ReportProgramRecommendSlider.tsx
src/components/common/report/SuperTitle.tsx
src/components/common/ui/Heading2.tsx
src/components/common/ui/ProgramRecommendSlider.tsx
src/components/live-view/LiveCurriculum.tsx
src/components/live-view/LiveFaq.tsx
src/components/live-view/LiveInfoBottom.tsx
src/components/live-view/LiveIntro.tsx
src/components/live-view/LiveMentor.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/schema.ts
src/utils/programConst.ts

- [LC-1077]
[LC-1077]: https://letscareer-team.atlassian.net/browse/LC-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1077 USER 1.11 프로그램 추천

---

src/components/common/report/ReportProgramRecommendSlider.tsx

- [LC-1077]
[LC-1077]: https://letscareer-team.atlassian.net/browse/LC-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 컴포넌트에 고유한 key 전달

---

src/components/common/blog/LexicalContent.tsx

- [LC-1095]
[LC-1095]: https://letscareer-team.atlassian.net/browse/LC-1095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] width가 0이면 이미지 원본 크기로 넣기

---

src/pages/admin/report/ReportApplicationsPage.tsx

- [LC-1100]
[LC-1100]: https://letscareer-team.atlassian.net/browse/LC-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1100 ADMIN 서류진단 참여자 목록 - 선결제 후제출 로직 추가

---

src/components/common/review/MoreReviewButton.tsx

- [LC-1101]
[LC-1101]: https://letscareer-team.atlassian.net/browse/LC-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1101 GA 클래스 추가

---

src/components/common/review/MoreReviewButton.tsx

- [LC-1101]
[LC-1101]: https://letscareer-team.atlassian.net/browse/LC-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV] LC-1101 GA 클래스 추가 + 이미지 원본크기 적용

---

src/api/report.ts
src/assets/icons/report-bubble-tail.svg
src/components/common/report/MainHeader.tsx
src/components/common/report/ReportApplyBottomSheet.tsx
src/components/common/report/ReportPlanSection.tsx
src/components/common/report/ReportProgramRecommendSlider.tsx
src/components/common/report/ResearchTeamSection.tsx
src/components/common/report/SectionHeader.tsx
src/components/common/report/SubHeader.tsx
src/components/common/ui/ProgramRecommendSlider.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx

- [LC-1106]
[LC-1106]: https://letscareer-team.atlassian.net/browse/LC-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1106 USER 1.7 상품 옵션 안내

---

src/components/common/report/ReportPlanSection.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx

- [LC-1106]
[LC-1106]: https://letscareer-team.atlassian.net/browse/LC-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1106 토글 숨김 + 자소서 내용 추가

---

src/components/common/report/PromoSection.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx
src/types/interface.ts

- [LC-1107]
[LC-1107]: https://letscareer-team.atlassian.net/browse/LC-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1107 USER 1.8 홍보 배너

---

src/components/common/report/ReportProgramRecommendSlider.tsx
src/components/common/report/ServiceProcessSection.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx

- [LC-1108]
[LC-1108]: https://letscareer-team.atlassian.net/browse/LC-1108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1108 USER 1.9 서비스 프로세스

---

src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1108]
[LC-1108]: https://letscareer-team.atlassian.net/browse/LC-1108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 이력서, 포폴 페이지에 서비스 이용 안내 추가

---

src/api/report.ts
src/components/challenge-view/ChallengeFaq.tsx
src/components/common/report/ReportFaqSection.tsx
src/components/common/ui/FaqChat.tsx
src/components/common/ui/FaqDropdown.tsx
src/components/live-view/LiveFaq.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1094]
[LC-1094]: https://letscareer-team.atlassian.net/browse/LC-1094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1094 USER 1.10 FAQ

---

src/components/admin/report/ReportReviewEditor.tsx
src/components/common/report/ReportBasicInfo.tsx
src/components/common/report/ReportExampleCard.tsx
src/components/common/report/ReportExampleSection.tsx
src/components/common/report/ReportInterviewCard.tsx
src/components/common/report/ReportPlanSection.tsx
src/components/common/report/ReportReviewCard.tsx
src/components/common/report/ReportReviewSection.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/data/reportConstant.ts
src/pages/admin/report/AdminReportEditPage.tsx
src/pages/common/report/ReportNavigation.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx
src/types/interface.ts

- [LC-1104]
[LC-1104]: https://letscareer-team.atlassian.net/browse/LC-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1104 리포트 후기 생성 및 리포트 예시, BasicInfo, Nav 등 수정

---

src/api/report.ts
src/components/common/ApplyCTA.tsx
src/components/common/report/ReportApplyBottomSheet.tsx
src/components/common/report/ReportPlanSection.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1109]
[LC-1109]: https://letscareer-team.atlassian.net/browse/LC-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1109 USER 1.12 CTA 마무리

---

src/components/common/report/ReportApplyBottomSheet.tsx
src/hooks/useHasScroll.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentPage.tsx

- [LC-1112]
[LC-1112]: https://letscareer-team.atlassian.net/browse/LC-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1112 CTA 자소서 문항 추가 구현

---

src/pages/common/report/ReportPaymentPage.tsx

- [LC-1112]
[LC-1112]: https://letscareer-team.atlassian.net/browse/LC-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 자소서 문항 추가 이름을 '문항 추가'로 고정

---

src/components/common/report/PromoSection.tsx
src/components/common/report/ReportFaqSection.tsx
src/components/common/report/ReportPlanSection.tsx
src/components/common/report/ReportProgramRecommendSlider.tsx
src/components/common/report/ReportReviewSection.tsx
src/components/common/report/ResearchTeamSection.tsx
src/components/common/report/ServiceProcessSection.tsx
src/components/common/ui/ProgramRecommendSlider.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1116]
[LC-1116]: https://letscareer-team.atlassian.net/browse/LC-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1116 USER 프로그램 추천: 제목 없으면 추천 표시 X

---

src/api/report.ts
src/components/common/ui/Badge.tsx
src/pages/common/report/ReportApplicationPage.tsx
src/pages/common/report/ReportManagementPage.tsx

- [LC-1113]
[LC-1113]: https://letscareer-team.atlassian.net/browse/LC-1113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1113 USER 후체줄 MY 진단서 디자인 수정

---

src/components/common/report/ReportReviewSection.tsx
src/data/reportConstant.ts
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1013]
[LC-1013]: https://letscareer-team.atlassian.net/browse/LC-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1124 색상 일부 수정

---

src/components/common/report/ReportExampleSection.tsx
src/components/common/report/ReportIntroSection.tsx
src/components/common/report/ReportPlanSection.tsx
src/components/common/report/ReportReviewSection.tsx
src/components/common/report/ServiceProcessSection.tsx
src/pages/common/report/ReportNavigation.tsx

- [LC-1125]
[LC-1125]: https://letscareer-team.atlassian.net/browse/LC-1125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1125 리포트 네비게이션 연결

---

src/components/ProgramDetailNavigation.tsx
src/components/common/home/new/banner/TopBanner.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/pages/common/report/ReportNavigation.tsx
src/store/useScrollStore.ts

- [LC-1115]
[LC-1115]: https://letscareer-team.atlassian.net/browse/LC-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1115 상단 내비게이션바 스크롤이벤트 추가

---

src/api/report.ts
src/components/common/report/ReportApplyBottomSheet.tsx
src/components/ui/BaseModal.tsx
src/components/ui/ModalOverlay.tsx
src/components/ui/ModalPortal.tsx
src/components/ui/ReportSubmitModal.tsx
src/hooks/useCredit.tsx
src/hooks/useReportProgramInfo.ts
src/pages/common/mypage/ReportCreditDelete.tsx
src/pages/common/mypage/ReportCreditDetail.tsx
src/pages/common/report/ReportApplicationPage.tsx
src/pages/common/report/ReportManagementPage.tsx
src/pages/common/report/ReportPaymentPage.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx

- [LC-1122]
[LC-1122]: https://letscareer-team.atlassian.net/browse/LC-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1122 USER 모달 컴포넌트 제작 + title -> optionTitle로 수정

---

src/components/common/report/Tooltip.tsx
src/components/common/review/MoreReviewButton.tsx
src/components/ui/BaseModal.tsx
src/components/ui/ReportSubmitModal.tsx
src/pages/common/report/ReportManagementPage.tsx

모달 스타일 수정 & 모바일에서 툴팁 위치 아래로 변경

---

src/components/admin/report/ReportReviewEditor.tsx
src/components/common/report/ReportReviewSection.tsx
src/types/interface.ts

- [LC-1131]
[LC-1131]: https://letscareer-team.atlassian.net/browse/LC-1131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1131 Admin 서류 진단 등록 페이지 수정

---

src/components/common/report/PromoSection.tsx
src/components/common/report/ReportBasicInfo.tsx
src/components/common/report/ReportExampleSection.tsx
src/components/common/report/ReportFaqSection.tsx
src/components/common/report/ReportIntroSection.tsx
src/components/common/report/ReportPlanSection.tsx
src/components/common/report/ReportProgramRecommendSlider.tsx
src/components/common/report/ReportReviewSection.tsx
src/components/common/report/ServiceProcessSection.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1132]
[LC-1132]: https://letscareer-team.atlassian.net/browse/LC-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1132 GA에 필요한 data 속성 추가

---

src/components/common/report/ReportPlanSection.tsx

- [LC-1134]
[LC-1134]: https://letscareer-team.atlassian.net/browse/LC-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1134 USER 가격 및 플랜 디자인 수정

---

src/components/common/report/PromoSection.tsx
src/components/common/report/ReportIntroSection.tsx
src/components/common/report/ResearchTeamSection.tsx
src/hooks/useSectionObserver.tsx
src/pages/common/report/ReportNavigation.tsx

- [LC-1132]
[LC-1132]: https://letscareer-team.atlassian.net/browse/LC-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1132 [GA] SPA 환경에서 섹션 도달률 및 이탈 구간 분석을 위한 데이터 추적 코드 구현 요청

---

src/components/common/ApplyCTA.tsx
src/components/common/report/ReportApplyBottomSheet.tsx
src/hooks/useInstagramAlert.tsx

- [LC-1147]
[LC-1147]: https://letscareer-team.atlassian.net/browse/LC-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1147 USER 인스타그램 결제 전 브라우저 변경 노티

---

src/App.tsx
src/api/report.ts
src/components/common/mypage/credit/ReportCreditRow.tsx
src/components/common/report/ControlLabel.tsx
src/components/common/report/DateTimePicker.tsx
src/components/common/report/ReportApplyBottomSheet.tsx
src/components/common/report/ReportPlanSection.tsx
src/components/common/report/ServiceProcessSection.tsx
src/components/common/ui/layout/channel/ChannelTalkBtn.tsx
src/hooks/useMinDate.ts
src/hooks/useReportProgramInfo.ts
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/report/ReportApplicationPage.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportManagementPage.tsx
src/pages/common/report/ReportPaymentPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1168]
[LC-1168]: https://letscareer-team.atlassian.net/browse/LC-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1168 price

---

src/components/common/report/ReportApplyBottomSheet.tsx
src/components/ui/ModalOverlay.tsx

- [LC-1239]
- [LC-1241]
[LC-1239]: https://letscareer-team.atlassian.net/browse/LC-1239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1241]: https://letscareer-team.atlassian.net/browse/LC-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

최종 QA 이슈 수정

---

src/components/common/report/ReportBasicInfo.tsx
src/components/common/report/ReportExampleSection.tsx
src/components/common/report/ReportInterviewCard.tsx
src/components/common/report/ReportIntroSection.tsx
src/components/common/report/ReportReviewSection.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/nav/NavItem.tsx
src/components/ui/BaseModal.tsx
src/data/reportConstant.ts
src/pages/common/report/ReportNavigation.tsx

- [LC-1228]
[LC-1228]: https://letscareer-team.atlassian.net/browse/LC-1228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1228 등 3차 qa 수정

---

src/components/common/report/ReportPlanSection.tsx

- [LC-1257]
[LC-1257]: https://letscareer-team.atlassian.net/browse/LC-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 숫자 리스트 정렬 수정

---

src/components/common/report/ReportApplyBottomSheet.tsx

- [LC-1273]
[LC-1273]: https://letscareer-team.atlassian.net/browse/LC-1273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 바텀 시트 높이 수정

---

src/components/common/ui/layout/nav/NavBar.tsx

- [LC-1283]
[LC-1283]: https://letscareer-team.atlassian.net/browse/LC-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1283 USER 모바일 사이드바 포폴 메뉴 숨기기

---

src/components/common/home/new/banner/Banner.tsx
src/components/common/home/new/banner/TopBanner.tsx
src/pages/common/home/Home.tsx

- [LC-1284]
[LC-1284]: https://letscareer-team.atlassian.net/browse/LC-1284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 배너 버튼 z-index 수정

---

src/components/common/ui/layout/nav/NavBar.tsx

[Fix] 네비 바 주석 풀기

---

src/hooks/useHasScroll.tsx

- [LC-1285]
[LC-1285]: https://letscareer-team.atlassian.net/browse/LC-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 랜더링 후 스크롤 길이 체크

---

src/components/common/ui/ProgramRecommendSlider.tsx

- [LC-1288]
[LC-1288]: https://letscareer-team.atlassian.net/browse/LC-1288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GA] 버튼 URL 전송

---

src/hooks/useHasScroll.tsx

[Fix] useRef에 null 설정

---

src/components/common/report/ReportIntroSection.tsx

[Fix] 오타 수정

---

src/components/common/ui/ProgramRecommendSlider.tsx

[GA] 이벤트 명 수정

---

src/components/common/ui/ProgramRecommendSlider.tsx

[GA] 함수 순서 변경

---

src/components/common/report/ReportIntroSection.tsx
src/components/common/report/ReportPlanSection.tsx

- [LC-1270]
[LC-1270]: https://letscareer-team.atlassian.net/browse/LC-1270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 자소서 스타일 수정

---

src/pages/common/program/Programs.tsx

USER 프로그램: 에러 발생 시, alert 대신 컴포넌트로 표시

---

src/components/common/report/ReportExampleSection.tsx

- [LC-1279]
- [LC-1275]
[LC-1279]: https://letscareer-team.atlassian.net/browse/LC-1279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1275]: https://letscareer-team.atlassian.net/browse/LC-1275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 후기 모달 스타일 변경 + 모달 오픈 시 스크롤 제한

---

src/components/admin/challenge/submit-check-detail/table/table-body/CommentCell.tsx
src/components/common/challenge/my-challenge/menu/AbsentMissionSubmitMenu.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionDetailMenu.tsx

- [LC-1295]
[LC-1295]: https://letscareer-team.atlassian.net/browse/LC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1295 [ADMIN] 챌린지 운영/제출확인/코멘트 기능 추가

---

src/components/common/challenge/my-challenge/ParsedCommentBox.tsx
src/components/common/challenge/my-challenge/menu/AbsentMissionSubmitMenu.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionDetailMenu.tsx

- [LC-1295]
[LC-1295]: https://letscareer-team.atlassian.net/browse/LC-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Refactor] 코멘트 컴포넌트 분리

---

src/components/common/report/ReportApplyBottomSheet.tsx

- [LC-1297]
[LC-1297]: https://letscareer-team.atlassian.net/browse/LC-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GA] 서류진단 신청 버튼 클래스네임 추가

---

src/components/ChallengeView.tsx
src/components/LiveView.tsx
src/components/ProgramDetailNavigation.tsx
src/components/challenge-view/ChallengeFaq.tsx
src/components/common/report/ReportIntroSection.tsx
src/components/common/ui/layout/nav/NavItem.tsx
src/components/live-view/LiveFaq.tsx
src/pages/common/report/ReportNavigation.tsx
src/schema.ts

- [LC-1278]
[LC-1278]: https://letscareer-team.atlassian.net/browse/LC-1278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1278 프로그램 상페 내비바 수정 등

---

src/assets/icons/polygon.svg
src/components/common/ui/layout/nav/NavItem.tsx

- [LC-1196]
[LC-1196]: https://letscareer-team.atlassian.net/browse/LC-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1196 svg 크기 등 수정

---

src/components/common/ui/layout/nav/NavItem.tsx

- [LC-1196]
[LC-1196]: https://letscareer-team.atlassian.net/browse/LC-1196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1196 relative 속성 추가

---

src/components/admin/report/ReportReviewEditor.tsx
src/components/common/report/ReportInterviewCard.tsx
src/pages/common/report/ReportNavigation.tsx

- [LC-1316]
- [LC-1294]
- [LC-1317]
[LC-1316]: https://letscareer-team.atlassian.net/browse/LC-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1294]: https://letscareer-team.atlassian.net/browse/LC-1294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1317]: https://letscareer-team.atlassian.net/browse/LC-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1316 후기 프로필 추가 등

---

src/components/common/ui/layout/nav/NavBar.tsx

- [LC-1326]
- ...
[LC-1326]: https://letscareer-team.atlassian.net/browse/LC-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1326 포트폴리오 비활성화

---

src/components/common/ui/layout/nav/NavBar.tsx

- [LC-1326]
- ...
[LC-1326]: https://letscareer-team.atlassian.net/browse/LC-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1326 포트폴리오 내비바 표시 제거

---

src/components/admin/lexical/plugins/AutoLinkPlugin/index.tsx
src/components/admin/lexical/plugins/KeywordsPlugin/index.ts

- [LC-1027]
[LC-1027]: https://letscareer-team.atlassian.net/browse/LC-1027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1027 Error loading component

---

src/pages/common/program/LiveDetailSSRPage.tsx
src/schema.ts

- [LC-1330]
[LC-1330]: https://letscareer-team.atlassian.net/browse/LC-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 라이브 place null 허용

---

src/components/admin/program/LiveBasic.tsx

- [LC-1330]
[LC-1330]: https://letscareer-team.atlassian.net/browse/LC-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 라이브 place null이면 빈 문자열 전달

---

src/components/common/report/ReportApplyBottomSheet.tsx

- [LC-1329]
[LC-1329]: https://letscareer-team.atlassian.net/browse/LC-1329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 서류 진단 상품 순서 변경

---

src/pages/admin/LiveEdit.tsx

- [LC-1333]
[LC-1333]: https://letscareer-team.atlassian.net/browse/LC-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 썸네일이 null이면 undefined로 설정

---

src/components/live-view/LiveBasicInfo.tsx

- [LC-1333]
[LC-1333]: https://letscareer-team.atlassian.net/browse/LC-1333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 이미지가 null이면 undefined로 설정

---

src/components/live-view/LiveIntro.tsx

- [LC-1334]
[LC-1334]: https://letscareer-team.atlassian.net/browse/LC-1334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 라이브 멘토 문구 변경

---

src/pages/common/mypage/MyPage.tsx
src/pages/common/review/ReviewCreate.tsx

- [LC-1337]
[LC-1337]: https://letscareer-team.atlassian.net/browse/LC-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 후기 스크롤 모달에 맞춰 숨기기

---

src/api/report.ts
src/pages/admin/report/ReportApplicationsPage.tsx

- [LC-1282]
[LC-1282]: https://letscareer-team.atlassian.net/browse/LC-1282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 후제출/동시제출 속성 추가

---

src/components/admin/lexical/EditorApp.tsx
src/pages/admin/BlogEditPage.tsx
src/pages/common/blog/BlogDetailSSRPage.tsx

- [LC-1084]
[LC-1084]: https://letscareer-team.atlassian.net/browse/LC-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1084 USER 블로그 CTA 노출 시점 당기기

---

src/pages/admin/report/AdminReportEditPage.tsx

- [LC-1341]
[LC-1341]: https://letscareer-team.atlassian.net/browse/LC-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 리포트 링크 복사 문구 수정

---

src/components/challenge-view/ChallengeBasicInfo.tsx

- [LC-1339]
[LC-1339]: https://letscareer-team.atlassian.net/browse/LC-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1339 패딩 추가

---

src/api/report.ts
src/components/common/ui/layout/nav/NavBar.tsx
src/pages/admin/report/AdminReportEditPage.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1341]
[LC-1341]: https://letscareer-team.atlassian.net/browse/LC-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1341 isVisible 조건 수정

---

src/api/report.ts
src/components/common/ui/layout/nav/NavBar.tsx
src/pages/admin/report/AdminReportEditPage.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [LC-1341]
[LC-1341]: https://letscareer-team.atlassian.net/browse/LC-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1341 리포트 링크 복사 문구 수정

---

src/assets/icons/polygon-sharp.svg
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/RadioButton.tsx
tailwind.config.js

- [LC-1339]
[LC-1339]: https://letscareer-team.atlassian.net/browse/LC-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1339 일정선택 넛지 추가

---

src/components/challenge-view/ChallengeBasicInfo.tsx
tailwind.config.js

- [LC-1339]
[LC-1339]: https://letscareer-team.atlassian.net/browse/LC-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1339 일정 정렬 및 애니메이션 속도 변경

---

src/components/challenge-view/ChallengeBasicInfo.tsx

- [LC-1339]
[LC-1339]: https://letscareer-team.atlassian.net/browse/LC-1339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1339 폰트/정렬 수정

---

tailwind.config.js

[Fix] module 대신 export 사용

---

src/components/admin/program/program-user/table-content/TableRow.tsx
src/hooks/useCredit.tsx
src/schema.ts

- [LC-1298]
[LC-1298]: https://letscareer-team.atlassian.net/browse/LC-1298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] ADMIN 신청서 조회: 결제금액에 보증금 포함

---

src/components/common/challenge/my-challenge/ParsedCommentBox.tsx

[Fix] Link에 key 추가

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/common/program/program-detail/basicInfo/BasicInfoBottomRow.tsx
src/components/common/program/program-detail/basicInfo/BasicInfoRow.tsx

- [LC-1348]
[LC-1348]: https://letscareer-team.atlassian.net/browse/LC-1348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] OT 내용 추가

---

src/components/challenge-view/ChallengePointView.tsx

- [LC-1348]
[LC-1348]: https://letscareer-team.atlassian.net/browse/LC-1348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] OT 일자 형식 수정

---

src/pages/common/review/ReviewCreate.tsx

- [LC-1360]
[LC-1360]: https://letscareer-team.atlassian.net/browse/LC-1360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] useControlScroll 삭제

---

src/Router.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/components/common/review/ReviewInstruction.tsx
src/components/common/review/ReviewQuestion.tsx
src/components/common/review/ReviewTextarea.tsx
src/components/common/review/score/TenScore.tsx
src/components/common/review/section/RecommendReviewField.tsx
src/components/common/review/section/RecommendReviewSection.tsx
src/components/common/ui/BackHeader.tsx
src/components/common/ui/input/TextArea.tsx
src/data/dayjsFormat.ts
src/pages/WriteReviewChallenge.tsx
src/pages/WriteReviewLive.tsx
src/pages/common/mypage/MyPage.tsx
src/pages/common/mypage/Review.tsx
src/pages/common/review/ChallengeReviewCreatePage.tsx
src/pages/common/review/ReviewCreate.tsx

- [LC-1351]
[LC-1351]: https://letscareer-team.atlassian.net/browse/LC-1351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1351 [USER] 마이페이지 챌린지 후기 작성 뷰

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/common/program/program-detail/basicInfo/BasicInfoBottomRow.tsx
src/components/common/program/program-detail/basicInfo/BasicInfoRow.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/data/dayjsFormat.ts
src/pages/common/review/ReviewCreate.tsx

- [LC-1345]
[LC-1345]: https://letscareer-team.atlassian.net/browse/LC-1345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1345 헤더 스크롤이벤트 조건 수정

---

src/components/common/ui/layout/nav/NavBar.tsx

- [LC-1345]
[LC-1345]: https://letscareer-team.atlassian.net/browse/LC-1345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1345 NavBar 스크롤이벤트 500 이상 시로 수정

---

src/Router.tsx
src/pages/common/review/LiveReviewCreatePage.tsx

- [LC-1351]
[LC-1351]: https://letscareer-team.atlassian.net/browse/LC-1351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1352 [USER] 마이페이지 챌린지 후기 작성 뷰

---

src/Router.tsx
src/components/common/review/GoalOrConcernsBox.tsx
src/pages/common/review/ReportReviewCreatePage.tsx

- [LC-1353]
[LC-1353]: https://letscareer-team.atlassian.net/browse/LC-1353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 서류 진단 후기 작성 페이지 추가

---

src/components/common/review/GoalOrConcernsBox.tsx
src/components/common/review/ReviewModal.tsx
src/components/common/review/ReviewTextarea.tsx
src/components/common/ui/BackHeader.tsx
src/components/common/ui/input/TextArea.tsx
src/pages/common/review/ChallengeReviewCreatePage.tsx
src/pages/common/review/LiveReviewCreatePage.tsx
src/pages/common/review/ReportReviewCreatePage.tsx

- [LC-1366]
[LC-1366]: https://letscareer-team.atlassian.net/browse/LC-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1366 USER 마이페이지 후기 작성 UI 세부 사항 반영

---

src/components/admin/review/reviews/ChallengeReviewTable.tsx
src/components/admin/review/reviews/table-content/ChallengeReviewTableBody.tsx
src/components/admin/review/reviews/table-content/ChallengeReviewTableHeader ChallengeReviewTableHeader.tsx
src/pages/admin/review/Reviews.tsx

- [LC-1369]
[LC-1369]: https://letscareer-team.atlassian.net/browse/LC-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1369 ADMIN 프로그램 참여 후기 > 챌린지

---

src/router-pages/admin/review/AdminBlogReviewListPage.tsx
src/router-pages/admin/review/AdminReviewHeader.tsx
src/router-pages/admin/review/Reviews.tsx

- [LC-1373]
[LC-1373]: https://letscareer-team.atlassian.net/browse/LC-1373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1373 ADMIN 후기 관리 > 블로그 후기 (뷰)

---

src/app/(user)/review/blog/page.tsx
src/app/(user)/review/interview/page.tsx
src/app/(user)/review/layout.tsx
src/app/(user)/review/program/page.tsx
src/components/common/review/ReviewNavBar.tsx

- [LC-1377]
[LC-1377]: https://letscareer-team.atlassian.net/browse/LC-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1377 USER 100% 솔직 후기 네비 바

---

src/components/common/review/ReviewBanner.tsx

- [LC-1320]
[LC-1320]: https://letscareer-team.atlassian.net/browse/LC-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 배너 본문 폰트 크기 수정

---

src/components/common/challenge/my-challenge/mission/DoneMissionDetailMenu.tsx
src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
src/pages/common/challenge/ChallengeUserInfo.tsx

- [LC-1349]
[LC-1349]: https://letscareer-team.atlassian.net/browse/LC-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1349 대시보드 미션 제출 view 구현

---

src/app/(user)/dev/page.tsx
src/app/(user)/review/page.tsx
src/components/common/ui/MoreHeader.tsx

- [LC-1396]
[LC-1396]: https://letscareer-team.atlassian.net/browse/LC-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1396 MoreHeader 생성

---

src/app/(user)/dev/page.tsx
src/app/(user)/review/layout.tsx
src/components/common/review/ReviewBanner.tsx
src/components/common/review/ReviewFilter.tsx

- [LC-1387]
[LC-1387]: https://letscareer-team.atlassian.net/browse/LC-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1387 USER Component 리뷰 필터 드롭다운

---

src/app/(user)/dev/page.tsx
src/components/common/review/ReviewFilter.tsx

- [LC-1387]
[LC-1387]: https://letscareer-team.atlassian.net/browse/LC-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1387 USER Component 리뷰 필터 드롭다운

---

src/app/(user)/program/challenge/[id]/[title]/page.tsx
src/components/ChallengeCTAButtons.tsx
src/router-pages/common/program/PaymentInputPage.tsx

- [LC-1398]
[LC-1398]: https://letscareer-team.atlassian.net/browse/LC-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1398 PaymentInput 및 application 수정

---

src/api/program.ts
src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeCheckList.tsx
src/components/challenge-view/ChallengeCurriculum.tsx
src/components/challenge-view/ChallengeDifferent.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/challenge-view/ChallengeResult.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/pages/admin/ChallengeEdit.tsx
src/schema.ts
src/utils/convert.ts

- [LC-1399]
[LC-1399]: https://letscareer-team.atlassian.net/browse/LC-1399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1399 feat

---

src/components/common/review/ReviewNavBar.tsx

- [LC-1403]
[LC-1403]: https://letscareer-team.atlassian.net/browse/LC-1403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1403 USER 데스크탑 네비 바 sticky

---

src/app/(user)/dev/page.tsx
src/app/(user)/review/blog/page.tsx
src/components/common/review/ReviewFilter.tsx
src/components/ui/BaseBottomSheet.tsx
src/components/ui/ModalOverlay.tsx

- [LC-1388]
[LC-1388]: https://letscareer-team.atlassian.net/browse/LC-1388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1388 USER Component 바텀시트

---

src/components/ProgramRecommendEditor.tsx
src/components/admin/ChallengePreviewButton.tsx
src/components/admin/LivePreviewButton.tsx
src/components/admin/program/ChallengeBasic.tsx
src/components/admin/program/LiveBasic.tsx
src/components/admin/program/SelectFormControl.tsx
src/context/ServerChallenge.tsx
src/context/ServerLive.tsx
src/hooks/useDuplicateProgram.ts
src/pages/admin/ChallengeCreate.tsx
src/pages/admin/ChallengeEdit.tsx
src/pages/admin/LiveCreate.tsx
src/pages/admin/VodCreate.tsx
src/pages/admin/program/VodEditor.tsx
src/schema.ts
src/utils/convert.ts

- [LC-1399]
[LC-1399]: https://letscareer-team.atlassian.net/browse/LC-1399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1399 B2 타입 추가

---

src/components/ChallengeView.tsx
src/hooks/useDuplicateProgram.ts
src/pages/admin/program/Programs.tsx
src/schema.ts

- [LC-1422]
[LC-1422]: https://letscareer-team.atlassian.net/browse/LC-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 프로그램 B2 타입 zod 에러 수정

---

src/components/ProgramRecommendEditor.tsx

[Fix] 프로그램 추천 타입 수정

---

src/components/ProgramRecommendEditor.tsx
src/hooks/useDuplicateProgram.ts
src/schema.ts

[Fix] 배열에 optional 추가

---

src/api/review.ts
src/components/admin/lexical/plugins/AutocompletePlugin/index.tsx
src/data/dayjsFormat.ts
src/router-pages/admin/review/AdminBlogReviewListPage.tsx
src/utils/random.ts

- [LC-1382]
[LC-1382]: https://letscareer-team.atlassian.net/browse/LC-1382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1382 ADMIN 후기 관리 > 블로그 후기 (API)

---

src/components/challenge-view/ChallengePointView.tsx

- [LC-1423]
[LC-1423]: https://letscareer-team.atlassian.net/browse/LC-1423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 대기업 자소서는 페이백 없음으로 내용 수정

---

src/api/review.ts
src/app/(user)/dev/page.tsx
src/app/(user)/review/blog/page.tsx
src/components/common/review/ReviewBanner.tsx
src/utils/client.ts

- [LC-1397]
[LC-1397]: https://letscareer-team.atlassian.net/browse/LC-1397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1397 fetch util 함수 추가

---

src/pages/common/report/ReportApplyPage.tsx
src/schema.ts

- [LC-1427]
[LC-1427]: https://letscareer-team.atlassian.net/browse/LC-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 자소서 프리미엄 validation 수정

---

src/pages/common/report/ReportApplicationPage.tsx

- [LC-1427]
[LC-1427]: https://letscareer-team.atlassian.net/browse/LC-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1427 [USER] 자기소개서 피드백 리포트 서류 제출 오류 및 수정사항

---

src/pages/common/report/ReportPaymentResult.tsx

- [LC-1427]
[LC-1427]: https://letscareer-team.atlassian.net/browse/LC-1427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 진단 서류를 null로 판단하기

---

src/components/ChallengeView.tsx
src/components/live-view/LiveBasicInfo.tsx

- [LC-1361]
- [LC-1429]
[LC-1361]: https://letscareer-team.atlassian.net/browse/LC-1361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1429]: https://letscareer-team.atlassian.net/browse/LC-1429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1361 LC-1429 프로그램 상페 디자인 수정

---

src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/nav/NavItem.tsx

- [LC-1426]
[LC-1426]: https://letscareer-team.atlassian.net/browse/LC-1426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 모의 면접 메뉴 추가

---

src/pages/admin/program/Programs.tsx

- [LC-1412]
[LC-1412]: https://letscareer-team.atlassian.net/browse/LC-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 프로그램 관리: 페이지네이션 size 수정

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx

- [LC-1429]
[LC-1429]: https://letscareer-team.atlassian.net/browse/LC-1429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1429 대기업 자소서 색상 기본 정보만 수정

---

src/pages/common/report/ReportManagementPage.tsx

- [LC-1437]
[LC-1437]: https://letscareer-team.atlassian.net/browse/LC-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Chore] MY 진단서 보기 워딩 수정

---

src/api/challenge.ts
src/components/admin/review/VisibilityToggle.tsx
src/router-pages/admin/review/AdminMissionReviewListPage.tsx

- [LC-1372]
[LC-1372]: https://letscareer-team.atlassian.net/browse/LC-1372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 미션후기 노출여부 변경 API 적용

---

next.config.mjs
package.json
src/api/blogSchemaCopy.ts
src/components/admin/blog/BlogRatingTable.tsx
src/components/admin/blog/BlogTable.tsx
src/components/admin/lexical/index.css
src/components/admin/program/ProgramBlogReviewEditor.tsx
src/components/common/blog/BlogCard.tsx
src/components/common/blog/RecommendBlogCard.tsx
src/router-pages/admin/BlogEditPage.tsx

- [LC-1320]
[LC-1320]: https://letscareer-team.atlassian.net/browse/LC-1320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1320 Sprint10 2024/02/01 테스트 서버 배포

---

src/components/ReviewCard.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionDetailMenu.tsx
src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
src/components/common/review/programReview/ProgramReviewSection.tsx
src/router-pages/common/challenge/ChallengeUserInfo.tsx

- [LC-1430]
[LC-1430]: https://letscareer-team.atlassian.net/browse/LC-1430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1430 ReviewCard 클릭이벤트 적용 등

---

src/app/(user)/review/blog/page.tsx
src/components/common/review/BlogReviewCard.tsx
src/components/common/review/BlogReviewWrapper.tsx

- [LC-1478]
[LC-1478]: https://letscareer-team.atlassian.net/browse/LC-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Test] 파비콘 가져오기

---

src/api/review.ts
src/components/common/review/BlogReviewListSection.tsx
src/components/common/review/BlogReviewWrapper.tsx
src/router-pages/admin/review/AdminBlogReviewListPage.tsx

- [LC-1491]
[LC-1491]: https://letscareer-team.atlassian.net/browse/LC-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1491 ADMIN 블로그 후기: 프로그램 구분에 VOD 제외

---

src/components/common/review/BlogReviewCard.tsx
src/components/common/review/MainBlogReviewSection.tsx
src/components/common/review/ReviewLinkCard.tsx

- [LC-1478]
[LC-1478]: https://letscareer-team.atlassian.net/browse/LC-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 파비콘 추가

---

src/api/challenge.ts
src/api/review.ts
src/components/common/challenge/dashboard/modal/DashboardCreateReviewModal.tsx
src/components/common/challenge/dashboard/modal/DashboardReviewModal.tsx
src/components/common/challenge/dashboard/section/EndDailyMissionSection.tsx
src/components/common/challenge/my-challenge/menu/AbsentMissionSubmitMenu.tsx
src/components/common/challenge/my-challenge/mission/AbsentMissionDetailMenu.tsx
src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
src/components/common/challenge/my-challenge/section/LastMissionSubmitModal.tsx
src/components/common/challenge/my-challenge/section/OtherMissionSection.tsx
src/components/common/review/ReviewModal.tsx
src/router-pages/common/challenge/MyChallengeDashboard.tsx
src/router-pages/common/review/ChallengeReviewCreatePage.tsx

- [LC-1521]
- [LC-1532]
[LC-1521]: https://letscareer-team.atlassian.net/browse/LC-1521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1532]: https://letscareer-team.atlassian.net/browse/LC-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1521 대시보드 회고 작성/확인 버튼 추가

---

src/components/common/review/BlogReviewWrapper.tsx
src/components/common/review/ReviewFilter.tsx
src/components/common/review/missionReview/MissionReviewFilterSection.tsx
src/components/common/review/programReview/ProgramReviewFilterSection.tsx

- [LC-1546]
[LC-1546]: https://letscareer-team.atlassian.net/browse/LC-1546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1546 USER 필터 디자인 수정 사항 반영 (update 2/5)

---

src/app/(user)/review/mission/page.tsx
src/app/(user)/review/program/page.tsx
src/components/common/review/BlogReviewListSection.tsx
src/components/common/review/BlogReviewWrapper.tsx
src/components/common/review/ReviewBanner.tsx
src/components/common/review/ReviewFilter.tsx
src/components/common/review/missionReview/MissionReview.tsx
src/components/common/review/missionReview/MissionReviewContentSection.tsx
src/components/common/review/missionReview/MissionReviewFilterSection.tsx
src/components/common/review/programReview/ProgramReview.tsx
src/components/common/review/programReview/ProgramReviewContentSection.tsx
src/components/common/review/programReview/ProgramReviewFilterSection.tsx
src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/next-footer/Footer.tsx

- [LC-1605]
- [LC-1606]
- [LC-1608]
[LC-1605]: https://letscareer-team.atlassian.net/browse/LC-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1606]: https://letscareer-team.atlassian.net/browse/LC-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1608]: https://letscareer-team.atlassian.net/browse/LC-1608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Footer 메뉴 추가, 리뷰 개수에 프로그램 후기 개수 포함, 필터 변경 시 페이지 초기화

---

src/api/program.ts
src/router-pages/admin/program/Programs.tsx
src/schema.ts

- [LC-1602]
[LC-1602]: https://letscareer-team.atlassian.net/browse/LC-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1602 프로그램 관리 Datagrid 적용

---

src/api/program.ts
src/router-pages/admin/program/Programs.tsx
src/schema.ts

- [LC-1602]
[LC-1602]: https://letscareer-team.atlassian.net/browse/LC-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1602 어드민 프로그램 관리에 Datagrid 적용

---

src/router-pages/admin/program/Programs.tsx

- [LC-1602]
[LC-1602]: https://letscareer-team.atlassian.net/browse/LC-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1602 InvalidateDate 수정

---

src/app/(user)/review/blog/page.tsx
src/app/(user)/review/mission/page.tsx

- [LC-1609]
[LC-1609]: https://letscareer-team.atlassian.net/browse/LC-1609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 필터와 리스트 간격 수정 및 불필요한 코드 삭제

---

src/router-pages/admin/program/Programs.tsx

- [LC-1602]
[LC-1602]: https://letscareer-team.atlassian.net/browse/LC-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 상페 이동 추가

---

src/components/common/review/BlogReviewCard.tsx
src/components/common/review/MainBlogReviewSection.tsx
src/components/common/review/ReviewLinkCard.tsx

- [LC-1615]
[LC-1615]: https://letscareer-team.atlassian.net/browse/LC-1615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 블로그 후기 썸넬 border 추가

---

src/AdminRoutes.tsx
src/components/admin/program/ui/form/ImageUpload.tsx
src/components/admin/ui/heading/Heading.tsx
src/router-pages/admin/blog/BlogBannerCreatePage.tsx
src/router-pages/admin/blog/BlogBannerListPage.tsx

- [LC-1621]
[LC-1621]: https://letscareer-team.atlassian.net/browse/LC-1621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1621 ADMIN 블로그 배너 생성 페이지 (VIEW)

---

src/AdminRoutes.tsx
src/router-pages/admin/blog/BlogBannerEditPage.tsx
src/router-pages/admin/blog/BlogBannerListPage.tsx

- [LC-1618]
[LC-1618]: https://letscareer-team.atlassian.net/browse/LC-1618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 블로그 광고 배너 수정 페이지 추가

---

src/components/admin/blog/Tag.tsx
src/router-pages/admin/blog/BlogCreatePage.tsx
src/router-pages/admin/blog/BlogEditPage.tsx

- [LC-1623]
- [LC-1624]
[LC-1623]: https://letscareer-team.atlassian.net/browse/LC-1623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1624]: https://letscareer-team.atlassian.net/browse/LC-1624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

블로그 등록/수정에 프로그램/블로그 추천 추가 (view)

---

src/api/program.ts
src/router-pages/admin/blog/BlogCreatePage.tsx
src/router-pages/admin/blog/BlogEditPage.tsx

- [LC-1638]
[LC-1638]: https://letscareer-team.atlassian.net/browse/LC-1638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 프로그램 선택 드롭다운 추가

---

src/router-pages/admin/blog/BlogCreatePage.tsx
src/router-pages/admin/blog/BlogEditPage.tsx

- [LC-1628]
[LC-1628]: https://letscareer-team.atlassian.net/browse/LC-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 블로그 발행 시, 게시일자가 없을 때만 '지금'으로 설정

---

src/components/common/report/ReportReviewSection.tsx
src/components/common/review/MoreReviewButton.tsx
src/components/common/review/missionReview/MissionReviewContentSection.tsx
src/components/common/review/programReview/ProgramReviewContentSection.tsx

- [LC-1614]
[LC-1614]: https://letscareer-team.atlassian.net/browse/LC-1614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1614 서류진단 상페 후기 더보기 버튼 추가

---

src/components/LiveView.tsx

- [LC-1643]
[LC-1643]: https://letscareer-team.atlassian.net/browse/LC-1643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 리뷰 없으면 리뷰 section 숨기기

---

src/components/common/about/section/ReviewSection.tsx

[Fix] 스크롤 조건 스타일 삭제

---

src/components/LiveView.tsx
src/components/live-view/LiveVod.tsx

- [LC-1644]
[LC-1644]: https://letscareer-team.atlassian.net/browse/LC-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] vod 제공여부에 margin 추가

---

src/components/BlogListContent.tsx
src/components/common/blog/BlogCard.tsx
src/components/common/program/pagination/MuiPagination.tsx

- [LC-1631]
- [LC-1629]
[LC-1631]: https://letscareer-team.atlassian.net/browse/LC-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1629]: https://letscareer-team.atlassian.net/browse/LC-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

USER 블로그 광고 노출 로직 추가, 블로그 페이지네이션 적용

---

src/api/blog.ts
src/api/blogSchema.ts
src/router-pages/admin/blog/BlogBannerCreatePage.tsx
src/router-pages/admin/blog/BlogBannerEditPage.tsx
src/router-pages/admin/blog/BlogBannerListPage.tsx

- [LC-1619]
- [LC-1622]
[LC-1619]: https://letscareer-team.atlassian.net/browse/LC-1619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1622]: https://letscareer-team.atlassian.net/browse/LC-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 블로그 배너 목록 조회/생성/수정 API 연결

---

src/app/(user)/blog/[id]/[title]/page.tsx
src/components/common/blog/BlogLikeBtn.tsx
src/components/common/blog/BlogRecommendCard.tsx
src/components/common/blog/ProgramRecommendCard.tsx

- [LC-1634]
[LC-1634]: https://letscareer-team.atlassian.net/browse/LC-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 좋아요 클릭 여부를 localStorage에 저장

---

src/components/common/blog/BlogCTA.tsx

- [LC-1652]
[LC-1652]: https://letscareer-team.atlassian.net/browse/LC-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1652 블로그 CTA latest:{text} 방식 동작하지 않는 문제 수정

---

src/api/blog.ts
src/api/blogSchema.ts
src/api/program.ts
src/api/report.ts
src/app/(user)/blog/[id]/[title]/page.tsx
src/app/(user)/blog/[id]/loading.tsx
src/components/BlogListContent.tsx
src/components/common/blog/BlogKakaoShareBtn.tsx
src/components/common/blog/BlogLikeBtn.tsx
src/components/common/blog/BlogRecommendCard.tsx
src/components/common/blog/ProgramRecommendCard.tsx
src/schema.ts

LC-1637 USER 블로그 상페: 추천 프로그램/블로그 API 연결

---

src/api/blog.ts
src/api/blogSchema.ts
src/app/(user)/blog/[id]/[title]/page.tsx
src/components/common/blog/BlogLikeBtn.tsx

- [LC-1671]
[LC-1671]: https://letscareer-team.atlassian.net/browse/LC-1671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 좋아요 api 연결

---

src/api/blog.ts
src/api/blogSchema.ts
src/components/common/blog/BlogLikeBtn.tsx

- [LC-1701]
[LC-1701]: https://letscareer-team.atlassian.net/browse/LC-1701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1701 USER 블로그 좋아요 API 수정

---

src/api/program.ts
src/app/(user)/blog/[id]/[title]/page.tsx
src/components/common/blog/ProgramRecommendCard.tsx
src/components/common/ui/ProgramRecommendSlider.tsx
src/components/page/ReportPersonalStatementPage.tsx

- [LC-1695]
[LC-1695]: https://letscareer-team.atlassian.net/browse/LC-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1695 USER 프로그램 추천 디폴트 값 넣기

---

src/app/(user)/blog/[id]/[title]/page.tsx
src/components/common/blog/BlogRecommendCard.tsx
src/components/common/ui/MoreHeader.tsx

- [LC-1709]
- [LC-1695]
[LC-1709]: https://letscareer-team.atlassian.net/browse/LC-1709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1695]: https://letscareer-team.atlassian.net/browse/LC-1695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

USER 블로그 게시글 내 프로그램/블로그 추천 리스트 선택하지 않은 경우 기본값 노출 요청

---

src/router-pages/common/mentor/MentorNotificationAfter.tsx
src/schema.ts

- [LC-1764]
[LC-1764]: https://letscareer-team.atlassian.net/browse/LC-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1764 라이브 멘토 후기 표시

---

src/components/challenge-view/ChallengeDifferent.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/challenge-view/ChallengePointView.tsx
src/router-pages/common/program/PaymentInputPage.tsx

- [LC-1792]
[LC-1792]: https://letscareer-team.atlassian.net/browse/LC-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1792 마케팅 챌린지 환급 숨기기 (임시방편)

---

src/components/challenge-view/ChallengePointView.tsx

- [LC-1792]
[LC-1792]: https://letscareer-team.atlassian.net/browse/LC-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 페이백 이미지도 숨기기

---

src/router-pages/common/program/PaymentInputPage.tsx

- [LC-1792]
[LC-1792]: https://letscareer-team.atlassian.net/browse/LC-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 프로그램 제목에 대기업 포함되면 페이백 숨기기

---

src/router-pages/common/mentor/MentorNotificationAfter.tsx

- [LC-1764]
[LC-1764]: https://letscareer-team.atlassian.net/browse/LC-1764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 멘토 후기 좋았던 점만 표시

---

src/app/(user)/blog/[id]/[title]/page.tsx

[Feat] 프로필 이름 수정

---

src/components/common/home/ProgramContainer.tsx
src/components/common/home/section/LetsCareerSection.tsx
src/components/common/home/section/MainBannerSection.tsx
src/index.css

- [LC-1738]
[LC-1738]: https://letscareer-team.atlassian.net/browse/LC-1738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1738 polygon 및 empty 관련 수정

---

src/app/(user)/blog/[id]/[title]/page.tsx

[Fix] 프로그램 추천 조건 변경

---

src/app/(user)/blog/[id]/[title]/page.tsx

[Fix] 날라간 코드 원복

---

src/components/common/home/ProgramContainer.tsx
src/components/common/home/section/MainBannerSection.tsx

- [LC-1814]
[LC-1814]: https://letscareer-team.atlassian.net/browse/LC-1814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1814 Empty 관련 수정

---

src/components/common/home/section/IntroSection.tsx

- [LC-1814]
[LC-1814]: https://letscareer-team.atlassian.net/browse/LC-1814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 링크 수정

---

src/app/(user)/blog/[id]/[title]/page.tsx

[Fix] 날라간 코드 주석 처리

---

src/app/(user)/blog/[id]/[title]/page.tsx
src/router-pages/admin/blog/BlogCreatePage.tsx
src/router-pages/admin/blog/BlogEditPage.tsx

- [LC-1817]
[LC-1817]: https://letscareer-team.atlassian.net/browse/LC-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 프로그램 추천 로그 추가

---

src/app/(user)/blog/[id]/[title]/page.tsx

- [LC-1817]
[LC-1817]: https://letscareer-team.atlassian.net/browse/LC-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 프로그램 추천 섹션 숨기기

---

src/app/(user)/blog/[id]/[title]/page.tsx

- [LC-1817]
[LC-1817]: https://letscareer-team.atlassian.net/browse/LC-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Chore] 로그 수정

---

src/api/program.ts

- [LC-1817]
[LC-1817]: https://letscareer-team.atlassian.net/browse/LC-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 스키마 수정

---

src/api/program.ts

[Fix] fetch path 수정

---

src/app/(user)/blog/[id]/[title]/page.tsx
src/components/common/blog/ProgramRecommendCard.tsx

[Chore] 불필요한 로그 삭제

---

src/components/common/blog/BlogLikeBtn.tsx
src/components/common/blog/ProgramRecommendCard.tsx

[Fix] 조건문 위치 수정

---

src/components/common/blog/BlogLikeBtn.tsx

[Chore] 훅 정리

---

src/components/BlogListContent.tsx
src/components/common/blog/BlogCard.tsx

- [LC-1805]
[LC-1805]: https://letscareer-team.atlassian.net/browse/LC-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] a 대신 next/link 사용

---

src/app/(user)/blog/[id]/page.tsx

- [LC-1805]
[LC-1805]: https://letscareer-team.atlassian.net/browse/LC-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] redirect 에러 핸들링

---

src/api/blog.ts
src/components/BlogListContent.tsx

- [LC-1804]
[LC-1804]: https://letscareer-team.atlassian.net/browse/LC-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 블로그 광고 배너 개수에 따라 유동적으로 게시글 사이즈 변경

---

src/api/blogSchema.ts
src/app/(user)/blog/[id]/[title]/page.tsx
src/components/common/blog/ProgramRecommendCard.tsx
src/hooks/useBlogMenuItems.tsx
src/hooks/useProgramMenuItems.tsx
src/router-pages/admin/blog/BlogCreatePage.tsx
src/router-pages/admin/blog/BlogEditPage.tsx

- [LC-1808]
- [LC-1809]
- [LC-1810]
- [LC-1827]
[LC-1808]: https://letscareer-team.atlassian.net/browse/LC-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1809]: https://letscareer-team.atlassian.net/browse/LC-1809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1810]: https://letscareer-team.atlassian.net/browse/LC-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1827]: https://letscareer-team.atlassian.net/browse/LC-1827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

프로그램/블로그 추천 표시

---

src/components/common/blog/LexicalContent.tsx

- [LC-1787]
[LC-1787]: https://letscareer-team.atlassian.net/browse/LC-1787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 블로그 lexical 행간 수정

---

src/components/common/about/section/program/ProgramMenuSection.tsx
src/components/common/blog/BlogCard.tsx

- [LC-1450]
- [LC-1755]
[LC-1450]: https://letscareer-team.atlassian.net/browse/LC-1450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1755]: https://letscareer-team.atlassian.net/browse/LC-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

블로그 리스트 간격 수정, 브랜드 스토리 페이지에서 LIVE, VOD 필터링 함께 걸기

---

src/components/BlogListContent.tsx

- [LC-1830]
[LC-1830]: https://letscareer-team.atlassian.net/browse/LC-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 블로그/id/title로 바로 넘어가기

---

src/components/admin/lexical/nodes/ImageNode.tsx
src/components/admin/lexical/plugins/ImagesPlugin/index.tsx
src/components/common/blog/BlogArticle.tsx
src/lib/image.ts

- [LC-1831]
[LC-1831]: https://letscareer-team.atlassian.net/browse/LC-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1831 feat

---

src/components/admin/lexical/nodes/ImageNode.tsx
src/components/admin/lexical/plugins/ImagesPlugin/index.tsx
src/components/common/blog/BlogArticle.tsx
src/lib/image.ts

- [LC-1831]
[LC-1831]: https://letscareer-team.atlassian.net/browse/LC-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1831 [ADMIN-블로그] 블로그 게시글 작성 에디터를 PC/모바일 각각 입력할 수 있게 구현

---

src/components/common/blog/BlogArticle.tsx

- [LC-1786]
[LC-1786]: https://letscareer-team.atlassian.net/browse/LC-1786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 썸네일 응답 받으면 주조색 추출

---

src/api/challenge.ts
src/components/common/home/ProgramContainer.tsx
src/components/common/home/section/IntroSection.tsx
src/components/common/home/section/LetsCareerSection.tsx
src/components/common/home/section/LogoPlaySection.tsx
src/components/common/home/section/ReviewSection.tsx
src/components/common/mypage/application/section/CompleteSection.tsx
src/components/common/mypage/application/section/ParticipateSection.tsx
src/components/common/mypage/review/section/DoneSection.tsx
src/components/common/mypage/review/section/WaitingSection.tsx
src/components/common/report/ReportApplyBottomSheet.tsx
src/index.css
src/router-pages/common/program/PaymentInputPage.tsx

- [LC-1836]
[LC-1836]: https://letscareer-team.atlassian.net/browse/LC-1836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1836 인트로섹션 API 수정 및 리포트 가격 옵션 수정 등

---

src/components/common/blog/BlogArticle.tsx
src/components/common/blog/BlogRecommendCard.tsx
src/components/common/blog/ProgramRecommendCard.tsx

- [LC-1839]
[LC-1839]: https://letscareer-team.atlassian.net/browse/LC-1839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] next/image 대신 <img> 태그 사용

---

next.config.mjs
src/components/common/blog/BlogArticle.tsx
src/components/common/blog/BlogRecommendCard.tsx
src/components/common/blog/ProgramRecommendCard.tsx
src/utils/dominantColor.ts

- [LC-1840]
[LC-1840]: https://letscareer-team.atlassian.net/browse/LC-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1840 썸네일 주조색 추출 안 됨

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeDifferent.tsx
src/components/challenge-view/ChallengePointView.tsx
src/schema.ts
src/utils/convert.ts

- [LC-1837]
[LC-1837]: https://letscareer-team.atlassian.net/browse/LC-1837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 마케팅 챌린지 구분 추가

---

src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/next-footer/Footer.tsx

- [LC-123]
- ...
[LC-123]: https://letscareer-team.atlassian.net/browse/LC-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 푸터 메뉴 수정

---

src/components/common/blog/BlogCard.tsx

- [LC-1787]
[LC-1787]: https://letscareer-team.atlassian.net/browse/LC-1787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1787 블로그 본문 Line height 수정

---

src/app/(user)/dev/page.tsx
src/components/common/review/BlogReviewCard.tsx
src/components/common/review/ReviewBanner.tsx
src/components/common/review/ReviewLinkCard.tsx

- [LC-1854]
[LC-1854]: https://letscareer-team.atlassian.net/browse/LC-1854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1854 리뷰 썸네일 깨짐 이슈 (vercel 최적화 이슈)

---

src/components/admin/program/LiveInformation.tsx
src/router-pages/admin/LiveCreate.tsx
src/router-pages/admin/LiveEdit.tsx

- [LC-1855]
[LC-1855]: https://letscareer-team.atlassian.net/browse/LC-1855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 라이브 수정 시 이미지 안 보임

---

src/components/common/home/section/ReviewSection.tsx

- [LC-1857]
[LC-1857]: https://letscareer-team.atlassian.net/browse/LC-1857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1857 [USER] 홈/프로그램 참여 후기 카드들 중에서 내용이 공란으로 보이는 경우가 있음

---

src/components/common/home/section/BottomBannerSection.tsx
src/components/common/home/section/MainBannerSection.tsx

- [LC-1862]
[LC-1862]: https://letscareer-team.atlassian.net/browse/LC-1862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1862 메인페이지 배너 비율 적용

---

src/components/common/home/section/ReviewSection.tsx

- [LC-1863]
[LC-1863]: https://letscareer-team.atlassian.net/browse/LC-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1863 리뷰아이템 수정

---

src/components/challenge-view/ChallengePointView.tsx

[Style] 진행 방식 box 배경색 수정

---

src/components/common/program/program-detail/review/ProgramDetailReviewItem.tsx

[Style] 리뷰 카드 스타일 수정

---

src/components/common/home/section/IntroSection.tsx

- [LC-1878]
[LC-1878]: https://letscareer-team.atlassian.net/browse/LC-1878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1878 [USER] 웹 홈페이지 경험정리 링크 연결 수정 요청

---

src/components/common/ui/MoreHeader.tsx

- [LC-1853]
[LC-1853]: https://letscareer-team.atlassian.net/browse/LC-1853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1853 MoreHeader subtitle 크기 변경

---

src/router-pages/admin/challenge/ChallengeOperationRegisterMission.tsx

- [LC-1866]
[LC-1866]: https://letscareer-team.atlassian.net/browse/LC-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1866 [ADMIN] 챌린지 미션 등록: 여백 클릭해도 수정 모드 유지

---

src/components/common/home/section/IntroSection.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/next-nav/NavBar.tsx
src/hooks/useActiveReports.tsx

- [LC-1874]
[LC-1874]: https://letscareer-team.atlassian.net/browse/LC-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[USER-홈] 이력서 진단받기 아이콘 노출 off 요청 및 일부 아이콘 노출 로직 수정

---

src/router-pages/admin/challenge/ChallengeOperationAttendances.tsx

- [LC-1882]
[LC-1882]: https://letscareer-team.atlassian.net/browse/LC-1882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 챌린지 운영: 제출한 사람 수와 표기되는 수가 다름

---

src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx

- [LC-1879]
[LC-1879]: https://letscareer-team.atlassian.net/browse/LC-1879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1879 USER 0% 할인은 숨기기

---

src/components/common/report/ReportPlanSection.tsx
src/router-pages/admin/review/AdminBlogReviewListPage.tsx
src/utils/random.ts

- [LC-1411]
[LC-1411]: https://letscareer-team.atlassian.net/browse/LC-1411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1411 [USER] 서류진단 상세페이지 플랜 카드 수정

---

src/components/common/ui/layout/nav/KakaoChannel.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/next-nav/NavBar.tsx

- [LC-1875]
[LC-1875]: https://letscareer-team.atlassian.net/browse/LC-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1875 USER 햄버거 메뉴 너비 조정

---

src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/next-nav/NavBar.tsx

- [LC-1875]
[LC-1875]: https://letscareer-team.atlassian.net/browse/LC-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1875 [USER] 햄버거 메뉴 너비 조정

---

src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/next-footer/Footer.tsx
src/components/common/ui/layout/next-nav/NavBar.tsx

[Chore] 모의 면접 메뉴 숨김

---

src/AdminRoutes.tsx
src/components/admin/ui/layout/AdminLayout.tsx
src/hooks/useProgramMenuItems.tsx
src/router-pages/admin/blog/BlogCreatePage.tsx
src/router-pages/admin/blog/BlogEditPage.tsx
src/router-pages/admin/notification/NotificationCreatePage.tsx
src/router-pages/admin/notification/NotificationEditPage.tsx
src/router-pages/admin/notification/NotificationListPage.tsx

- [LC-1889]
- [LC-1890]
- [LC-1891]
[LC-1889]: https://letscareer-team.atlassian.net/browse/LC-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1890]: https://letscareer-team.atlassian.net/browse/LC-1890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1891]: https://letscareer-team.atlassian.net/browse/LC-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 출시알림신청 View

---

src/router-pages/admin/notification/NotificationListPage.tsx

- [LC-1898]
[LC-1898]: https://letscareer-team.atlassian.net/browse/LC-1898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1898 ADMIN 출시알림신청 redesh 버튼 추가

---

src/components/common/home/section/IntroSection.tsx

USRE 홈 면접 메뉴 숨김

---

src/router-pages/common/challenge/ChallengeUserInfo.tsx

[Chore] 에러 alert에 찍기

---

src/components/admin/program/ChallengeOptionSection.tsx
src/components/admin/program/ChallengePrice.tsx
src/router-pages/admin/ChallengeCreate.tsx
src/router-pages/admin/ChallengeEdit.tsx
src/router-pages/admin/program/Programs.tsx
src/router-pages/admin/report/AdminReportCreatePage.tsx

- [LC-1911]
- [LC-1912]
[LC-1911]: https://letscareer-team.atlassian.net/browse/LC-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1912]: https://letscareer-team.atlassian.net/browse/LC-1912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1911 ADMIN 챌린지 가격 플랜 View

---

src/components/ChallengeCTAButtons.tsx
src/components/common/ApplyCTA.tsx
src/components/common/program/PricePlanBottomSheet.tsx
src/components/common/report/ReportApplyBottomSheet.tsx
src/components/common/ui/ControlLabel.tsx
src/components/common/ui/DrawerCloseBtn.tsx
src/components/common/ui/OptionDropdown.tsx
src/index.css
src/router-pages/common/report/ReportApplyPage.tsx

- [LC-1910]
[LC-1910]: https://letscareer-team.atlassian.net/browse/LC-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1910 USER 챌린지 하단 옵션 Drawer 추가

---

src/api/challenge.ts
src/app/(user)/program/challenge/[id]/[title]/page.tsx
src/components/admin/challenge/ui/ChallengeOperationAdminLayout.tsx

- [LC-1871]
[LC-1871]: https://letscareer-team.atlassian.net/browse/LC-1871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1871 [ADMIN] 챌린지 대시보드 복제기능 추가

---

src/components/admin/program/ChallengeBasic.tsx
src/components/admin/program/ChallengePrice.tsx
src/hooks/useChallengeOption.tsx
src/router-pages/admin/ChallengeCreate.tsx
src/router-pages/admin/ChallengeEdit.tsx
src/schema.ts

- [LC-1913]
[LC-1913]: https://letscareer-team.atlassian.net/browse/LC-1913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1913 ADMIN 챌린지 가격 플랜 별 금액 계산

---

src/components/admin/program/ChallengePrice.tsx
src/hooks/useAdminChallenge.tsx
src/router-pages/admin/ChallengeCreate.tsx
src/router-pages/admin/ChallengeEdit.tsx

- [LC-1926]
[LC-1926]: https://letscareer-team.atlassian.net/browse/LC-1926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1926 [Feat] 챌린지 최종 금액 표시

---

src/api/application.ts
src/components/common/program/PricePlanBottomSheet.tsx
src/components/common/report/ReportApplyBottomSheet.tsx
src/components/common/ui/PriceView.tsx
src/lib/order.ts
src/schema.ts
src/store/useProgramStore.ts

- [LC-1914]
[LC-1914]: https://letscareer-team.atlassian.net/browse/LC-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1914 USER 챌린지 가격 플랜 결제 API 연결

---

src/components/common/home/section/ReviewSection.tsx

- [LC-1930]
[LC-1930]: https://letscareer-team.atlassian.net/browse/LC-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1930 USER 홈 리뷰 안 보임

---

src/components/common/home/section/ReviewSection.tsx

- [LC-1930]
[LC-1930]: https://letscareer-team.atlassian.net/browse/LC-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 후기 page를 state로 수정

---

src/components/common/home/section/ReviewSection.tsx

- [LC-1930]
[LC-1930]: https://letscareer-team.atlassian.net/browse/LC-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 적어도 5개 리뷰가 있을 때 표시

---

src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/next-footer/Footer.tsx

- [LC-1931]
[LC-1931]: https://letscareer-team.atlassian.net/browse/LC-1931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

USER Footer 서류 진단 서비스 링크 수정

---

src/components/admin/program/ChallengeBasic.tsx
src/components/common/ui/layout/footer/Footer.tsx
src/router-pages/admin/ChallengeCreate.tsx
src/router-pages/admin/ChallengeEdit.tsx
src/router-pages/admin/LiveCreate.tsx
src/router-pages/admin/LiveEdit.tsx
src/schema.ts

- [LC-1928]
[LC-1928]: https://letscareer-team.atlassian.net/browse/LC-1928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1928 ADMIN 프로그램 데스크탑 썸네일 추가

---

src/AdminRoutes.tsx
src/Router.tsx
src/components/admin/challenge/submit-check-detail/filter/ResultFilter.tsx
src/components/admin/challenge/submit-check-detail/filter/StatusFilter.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/AllChoiceCheckbox.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/ChoiceCheckbox.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/CommentCell.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/ResultDropdown.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/StatusDropdown.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/TableRow.tsx
src/components/admin/challenge/submit-check-detail/table/table-head/TableHead.tsx
src/components/admin/challenge/submit-check/table/table-body/ChallengeSubmitDetail.tsx
src/components/admin/program/program-user/bottom-action/BottomAction.tsx
src/components/admin/program/program-user/bottom-action/ChallengeActionDropdown.tsx
src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
src/components/admin/program/program-user/table-content/TableBody.tsx
src/components/admin/program/program-user/table-content/TableHead.tsx
src/components/admin/program/program-user/table-content/TableRow.tsx
src/router-pages/admin/challenge/ChallengeOperationAttendances.tsx
src/router-pages/admin/challenge/ChallengeOperationParticipants.tsx
src/router-pages/admin/challenge/ChallengeOperationPayback.tsx
src/router-pages/admin/program/ProgramUsers.tsx
src/schema.ts
src/utils/tableCellWidthList.ts

LC-1932 ADMIN 챌린지 운영 옵션 구분 추가

---

src/components/common/home/section/ReviewSection.tsx

- [LC-1930]
[LC-1930]: https://letscareer-team.atlassian.net/browse/LC-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 미션 리뷰 제외하고 후기 가져오기

---

src/router-pages/common/mypage/CreditDelete.tsx

- [LC-1934]
[LC-1934]: https://letscareer-team.atlassian.net/browse/LC-1934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1934 USER 경험 정리 챌린지 환불 예정 금액 안 맞음

---

.gitignore
src/api/application.ts
src/api/paymentSchema.ts
src/components/common/mypage/credit/CreditListItem.tsx
src/components/common/mypage/credit/section/CreditList.tsx
src/components/common/program/PricePlanBottomSheet.tsx
src/hooks/useCredit.tsx
src/lib/order.ts
src/router-pages/common/mypage/Credit.tsx
src/router-pages/common/mypage/CreditDelete.tsx
src/router-pages/common/mypage/CreditDetail.tsx
src/router-pages/common/program/PaymentResult.tsx
src/schema.ts

- [LC-1927]
- [LC-1935] USER 결제내역 할인금액 있을 때만 정가 표시
[LC-1927]: https://letscareer-team.atlassian.net/browse/LC-1927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-1935]: https://letscareer-team.atlassian.net/browse/LC-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1927 USER 챌린지 결제/환불 내역 수정

---

.gitignore
src/app/(user)/program/live/[id]/[title]/page.tsx
src/components/common/mypage/application/section/ApplySection.tsx
src/components/common/mypage/application/section/CompleteSection.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/router-pages/common/mypage/Application.tsx

- [LC-1941]
[LC-1941]: https://letscareer-team.atlassian.net/browse/LC-1941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1941 USER 마이페이지 > 프로그램 상세로 이동할 때 404

---

src/api/review.ts
src/components/ReviewCard.tsx
src/components/common/home/section/ReviewSection.tsx

- [LC-1942]
[LC-1942]: https://letscareer-team.atlassian.net/browse/LC-1942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1942 희망산업 -> 희망기업으로 워딩 수정

---

src/router-pages/admin/program/Programs.tsx

- [LC-1943]
[LC-1943]: https://letscareer-team.atlassian.net/browse/LC-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 구버전 버튼 삭제

---

src/components/common/ui/MoreHeader.tsx

- [LC-1885]
[LC-1885]: https://letscareer-team.atlassian.net/browse/LC-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1885 홈 블로그 컨테이너 폰트 사이즈 수정

---

src/components/admin/program/ProgramBlogReviewEditor.tsx

- [LC-1886]
[LC-1886]: https://letscareer-team.atlassian.net/browse/LC-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1886 ADMIN 추천 블로그 목록 선택에서 '비공개' 숨기기

---

src/hooks/useChallengeOption.tsx
src/router-pages/admin/ChallengeCreate.tsx
src/router-pages/admin/ChallengeEdit.tsx

- [LC-1945]
[LC-1945]: https://letscareer-team.atlassian.net/browse/LC-1945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1945 USER/ADMIN 프리미엄 로직 수정

---

src/api/review.ts
src/components/common/program/PricePlanBottomSheet.tsx
src/components/common/program/program-detail/apply/section/CouponSection.tsx
src/hooks/useCredit.tsx
src/router-pages/common/program/PaymentInputPage.tsx
src/store/useProgramStore.ts

- [LC-1909]
[LC-1909]: https://letscareer-team.atlassian.net/browse/LC-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1909 챌린지 결제 및 환불 정책 수정 & 챌린지 베이직 판매가에만 쿠폰 적용

---

src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx

- [LC-1946]
[LC-1946]: https://letscareer-team.atlassian.net/browse/LC-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1946 USER 챌린지 상페 기본 정보 금액 수정

---

src/components/common/home/section/IntroSection.tsx

- [LC-1951]
[LC-1951]: https://letscareer-team.atlassian.net/browse/LC-1951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1951 홈화면 아이콘 사이값 수정

---

src/components/admin/OutlinedTextarea.tsx
src/components/admin/program/ChallengePrice.tsx
src/components/admin/program/LiveInformation.tsx
src/hooks/useChallengeOption.tsx
src/router-pages/admin/ChallengeCreate.tsx
src/router-pages/admin/ChallengeEdit.tsx
src/router-pages/admin/LiveCreate.tsx
src/schema.ts

- [LC-1954]
[LC-1954]: https://letscareer-team.atlassian.net/browse/LC-1954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1954 ADMIN 베이직/스탠다드/프리미엄 설명란 추가

---

src/components/admin/program/ChallengePrice.tsx

- [LC-1955]
[LC-1955]: https://letscareer-team.atlassian.net/browse/LC-1955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1955 ADMIN 베이직/스탠다드/프리미엄 가격 각각 노출

---

src/components/challenge-view/ChallengePricePlanSection.tsx
src/components/common/report/ReportPlanSection.tsx
src/components/common/ui/PriceSummary.tsx
src/components/ui/SectionHeader.tsx
src/components/ui/SectionMainHeader.tsx
src/components/ui/SectionSubHeader.tsx

- [LC-1956]
[LC-1956]: https://letscareer-team.atlassian.net/browse/LC-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 1956 feat

---

src/components/challenge-view/ChallengePricePlanSection.tsx

[Style] 제목 줄바꿈 추가

---

src/components/BlogListContent.tsx

- [LC-1899]
[LC-1899]: https://letscareer-team.atlassian.net/browse/LC-1899

LC-1899 블로그 필터 수정

---

src/api/review.ts
src/components/common/review/programReview/ProgramReviewSection.tsx

- [LC-1968]
[LC-1968]: https://letscareer-team.atlassian.net/browse/LC-1968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1968 USER 리뷰 데이터 없을 때 read properties of undefined 에러 해결

---

src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
src/utils/debounce.ts

- [LC-1952]
[LC-1952]: https://letscareer-team.atlassian.net/browse/LC-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1952 ADMIN 참여자 중복 이슈

---

src/components/common/program/PricePlanBottomSheet.tsx

- [LC-1970]
[LC-1970]: https://letscareer-team.atlassian.net/browse/LC-1970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1970 USER 챌린지 가격 플랜 제목 기본값 넣기

---

src/components/common/home/section/LogoPlaySection.tsx
src/components/common/home/section/ReviewCurationSection.tsx
src/components/common/home/section/ReviewSection.tsx
src/hooks/useActiveReports.tsx

- [LC-1971]
[LC-1971]: https://letscareer-team.atlassian.net/browse/LC-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1971 홈 후기 위아래 패딩값 수정

---

src/components/common/auth/ui/SocialLogin.tsx
src/router-pages/common/auth/Login.tsx

- [LC-1969]
[LC-1969]: https://letscareer-team.atlassian.net/browse/LC-1969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 기본값 지우고 basePath 없으면 로그인 중단

---

src/components/common/home/new/banner/TopBanner.tsx

- [LC-1973]
[LC-1973]: https://letscareer-team.atlassian.net/browse/LC-1973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 상단 때 배너 top 위치 수정

---

src/api/payment.ts
src/components/admin/program/program-user/table-content/TableRow.tsx

- [LC-1976]
[LC-1976]: https://letscareer-team.atlassian.net/browse/LC-1976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 환불 차감 금액에 옵션 금액 반영

---

src/components/common/review/ReviewNavBar.tsx

- [LC-1981]
[LC-1981]: https://letscareer-team.atlassian.net/browse/LC-1981

LC-1981 후기 네비와 탭 사이 공간 수정

---

.gemini/styleguide.md

docs: gemini에 프론트엔드 개발 가이드라인 추가

---

src/components/common/ui/layout/BottomNavBar.tsx

- [LC-1979]
[LC-1979]: https://letscareer-team.atlassian.net/browse/LC-1979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 메뉴 클릭 시에도 active 상태 갱신

---

src/router-pages/admin/challenge/ChallengeOperationRegisterMission.tsx

- [LC-1987]
[LC-1987]: https://letscareer-team.atlassian.net/browse/LC-1987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 마감 시간 00s -> 59s로 수정

---

src/components/ChallengeMarketingView.tsx
src/components/common/challenge-marketing-view/ChallengeTabNavigation.tsx
src/components/common/challenge-marketing-view/MarketingCurriculumSection.tsx
src/components/common/challenge-marketing-view/MarketingIntroSection.tsx

- [LC-1997]
[LC-1997]: https://letscareer-team.atlassian.net/browse/LC-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1997 USER 마케팅 상페 네비게이션 바

---

src/components/ChallengeMarketingView.tsx
src/components/challenge-view/ChallengePricePlanSection.tsx
src/components/common/challenge-marketing-view/ChallengePriceInfo.tsx
src/components/common/challenge-marketing-view/ChallengeRecruitmentInfoSection.tsx
src/components/common/challenge-marketing-view/MarketingPricingSection.tsx
src/components/common/program/PricePlanBottomSheet.tsx
src/utils/getChallengeOptionPriceInfo.ts

- [LC-2000]
[LC-2000]: https://letscareer-team.atlassian.net/browse/LC-2000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2000 마케팅 가격구성 섹션

---

src/components/ChallengeMarketingView.tsx
src/components/common/challenge-marketing-view/MarketingChallengeCalendar.tsx

- [LC-2012]
[LC-2012]:https://letscareer-team.atlassian.net/browse/LC-2012?atlOrigin=eyJpIjoiOGY0MTA2YTI2ZDdmNDI4MjhmOThiZDdlMDQwY2I0NDgiLCJwIjoiaiJ9
[LC-2012]: https://letscareer-team.atlassian.net/browse/LC-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2012]: https://letscareer-team.atlassian.net/browse/LC-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2012 USER 마케팅 달력 섹션 기능 구현

---

src/components/common/ui/layout/BottomNavBar.tsx

- [LC-2023]
[LC-2023]: https://letscareer-team.atlassian.net/browse/LC-2023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2023 [USER] (모바일) 하단 네비게이션바가 결제하기 버튼을 가려서 클릭할수가 없음

---

src/components/ProgramDetailNavigation.tsx
src/components/common/ui/layout/header/GlobalNavTopBar.tsx
src/components/page/ReportNavigation.tsx

- [LC-2008]
[LC-2008]: https://letscareer-team.atlassian.net/browse/LC-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 2008 USER 프로그램 상페 네비게이션바 위치 조정

---

src/components/admin/program/ChallengePrice.tsx
src/components/common/challenge-marketing-view/ChallengePriceInfoContent.tsx

- [LC-2028]
[LC-2028]: https://letscareer-team.atlassian.net/browse/LC-2028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc 2028 feat

---

src/components/common/challenge-marketing-view/ChallengeTabNavigation.tsx

style: z-index 수정

---

src/components/common/challenge-marketing-view/MarketingFAQSection.tsx

- [LC-2034]
[LC-2034]:https://letscareer-team.atlassian.net/browse/LC-2034?atlOrigin=eyJpIjoiNzg4MTdiZTUyNjExNGQwM2I4ZWVmMjVlOWQ1ZjgyYmQiLCJwIjoiaiJ9
[LC-2034]: https://letscareer-team.atlassian.net/browse/LC-2034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2034]: https://letscareer-team.atlassian.net/browse/LC-2034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2034 FAQ 사파리 버튼 재정렬 및 열림상태 적용

---

src/components/common/challenge-marketing-view/ChallengeRecruitmentInfoSection.tsx

fix: 모집 개요에 제목 표시

---

src/app/(user)/program/challenge/[id]/[title]/page.tsx
src/components/common/challenge-marketing-view/MarketingPricingSection.tsx
src/components/common/challenge-marketing-view/TestimonialCarousel.tsx

S13 운영 이슈 수정

---

src/components/common/challenge-marketing-view/MarketingFAQSection.tsx

- [LC-2035]
[LC-2035]:https://letscareer-team.atlassian.net/browse/LC-2035?atlOrigin=eyJpIjoiYTM2OTZlNWQwZTA3NDk3YzkyMDM0YzQ1NmJiMjFjYTkiLCJwIjoiaiJ9
[LC-2035]: https://letscareer-team.atlassian.net/browse/LC-2035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2035]: https://letscareer-team.atlassian.net/browse/LC-2035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2035 FAQ 1:1 문의 빠짐

---

src/components/common/challenge-marketing-view/MarketingFAQSection.tsx

- [LC-2036]
[LC-2036]:https://letscareer-team.atlassian.net/browse/LC-2036?atlOrigin=eyJpIjoiOWM0NmYzN2IxZjRhNDRlZGJlNWVkNTc1OGQyYzBkYTYiLCJwIjoiaiJ9
[LC-2036]: https://letscareer-team.atlassian.net/browse/LC-2036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2036]: https://letscareer-team.atlassian.net/browse/LC-2036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2036 FAQ 콘텐츠 사이 간격 체크

---

src/components/common/challenge-marketing-view/MarketingFeaturesSection.tsx

- [LC-2039]
[LC-2039]: https://letscareer-team.atlassian.net/browse/LC-2039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2039 feat: 퍼포먼스 키워드 삭제

---

src/components/common/challenge-marketing-view/MarketingFeaturesSection.tsx

- [LC-2039]
[LC-2039]: https://letscareer-team.atlassian.net/browse/LC-2039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2039 style: flex-wrap 삭제

---

package-lock.json
src/router-pages/admin/challenge/ChallengeOperationFeedbackPage.tsx
src/router-pages/admin/challenge/FeedbackParticipantPage.tsx
src/schema.ts

- [LC-2049]
[LC-2049]: https://letscareer-team.atlassian.net/browse/LC-2049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2049 ADMIN 피드백 참여자 페이지 그리드 추가

---

src/AdminRoutes.tsx
src/router-pages/admin/challenge/ChallengeFeedbackPage.tsx
src/router-pages/admin/challenge/ChallengeOperationFeedbackPage.tsx
src/router-pages/admin/challenge/FeedbackParticipantPage.tsx

- [LC-2051]
[LC-2051]: https://letscareer-team.atlassian.net/browse/LC-2051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2051 ADMIN 피드백 페이지 UI 추가

---

src/app/(user)/report/landing/layout.tsx
src/components/page/ReportNavigation.tsx
src/router-pages/common/report/ReportNavigation.tsx

- LC-1978 이후에 작업 예정 
- [LC-1904]
[LC-1904]: https://letscareer-team.atlassian.net/browse/LC-1904?focusedCommentId=12509&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-12509

LC-1904 서류진단 탭추가

---

src/components/common/challenge-marketing-view/MarketingReviewsSection.tsx

- [LC-2059]
[LC-2059]:https://letscareer-team.atlassian.net/browse/LC-2059?atlOrigin=eyJpIjoiMDA3MTAxMzQ3YWIxNGZkMWIyNTA2N2Q5M2U3MWNkOGEiLCJwIjoiaiJ9

LC-2059 마케팅 챌린지 사파리 후기 뷰 수정

---

src/api/challenge.ts
src/api/challengeOptionSchema.ts
src/api/challengeSchema.ts
src/router-pages/admin/challenge/ChallengeOperationFeedbackPage.tsx

- [LC-2048]
[LC-2048]: https://letscareer-team.atlassian.net/browse/LC-2048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2048 ADMIN 챌린지 운영 > 피드백 목록 조회 API 연결

---

src/api/challenge.ts
src/api/challengeSchema.ts
src/router-pages/admin/challenge/FeedbackParticipantPage.tsx
src/schema.ts

- [LC-2050]
[LC-2050]: https://letscareer-team.atlassian.net/browse/LC-2050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2050 ADMIN 피드백 참여자 페이지 API 연결

---

src/api/challenge.ts
src/api/challengeOption.ts
src/api/mission.ts
src/api/missionSchema.ts
src/components/admin/program/ChallengeBasic.tsx
src/components/admin/program/LiveBasic.tsx
src/components/admin/program/SelectFormControl.tsx
src/router-pages/admin/challenge/ChallengeOperationRegisterMission.tsx
src/router-pages/admin/challenge/FeedbackParticipantPage.tsx
src/router-pages/admin/program/ChallengeMentorRegistrationSection.tsx
src/router-pages/admin/program/VodEditor.tsx
src/schema.ts

- [LC-2046]
[LC-2046]: https://letscareer-team.atlassian.net/browse/LC-2046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2046 ADMIN 미션 등록: 피드백 미션 여부 컬럼 추가

---

src/api/user.ts
src/api/userSchema.ts
src/router-pages/common/mypage/Feedback.tsx
src/router-pages/common/mypage/MyPage.tsx

- [LC-2054]
[LC-2054]:https://letscareer-team.atlassian.net/browse/LC-2054?atlOrigin=eyJpIjoiNWZhZGE4ODFiNGY3NDY2Y2E1Y2NlMDk5YzQxZGNhMTgiLCJwIjoiaiJ9
[LC-2054]: https://letscareer-team.atlassian.net/browse/LC-2054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2054]: https://letscareer-team.atlassian.net/browse/LC-2054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DRAFT] LC-2054 USER 마이페이지 챌린지 피드백 리스트 구현

---

src/api/user.ts
src/api/userSchema.ts
src/components/admin/challenge/ui/ChallengeOperationAdminLayout.tsx
src/components/admin/ui/layout/AdminLayout.tsx

- [LC-2066]
[LC-2066]: https://letscareer-team.atlassian.net/browse/LC-2066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2066 ADMIN 사용자에 따라 어드민 기능 숨기기

---

src/api/challengeSchema.ts
src/router-pages/admin/challenge/FeedbackParticipantPage.tsx

- [LC-2079]
[LC-2079]: https://letscareer-team.atlassian.net/browse/LC-2079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2079 ADMIN 챌린지 피드백 미션별 제출자 조회 API에서 멘토를 name이 아니라 id로 조회

---

src/api/challenge.ts
src/hooks/useInvalidateQueries.ts
src/router-pages/admin/challenge/ChallengeFeedbackPage.tsx
src/router-pages/admin/challenge/FeedbackParticipantPage.tsx

- [LC-2077]
- ...
[LC-2077]: https://letscareer-team.atlassian.net/browse/LC-2077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2077 ADMIN 멘토/관리자에 따라 '피드백 진행상태' 권한 제어

---

src/api/challenge.ts
src/router-pages/admin/challenge/FeedbackParticipantPage.tsx

- [LC-2080]
[LC-2080]: https://letscareer-team.atlassian.net/browse/LC-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2080 ADMIN 멘토용 미션별 제출자 조회 API 추가

---

src/Router.tsx
src/api/challenge.ts
src/components/common/challenge/my-challenge/ParsedCommentBox.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionDetailMenu.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionItem.tsx
src/router-pages/admin/challenge/ChallengeFeedbackPage.tsx
src/router-pages/common/challenge/MissionFeedback.tsx
src/schema.ts

- [LC-2055]
[LC-2055]:https://letscareer-team.atlassian.net/browse/LC-2055?atlOrigin=eyJpIjoiY2ViZTRjYjBhODM5NDRiNWEyZmZhYTgzNGFhMTZhOTAiLCJwIjoiaiJ9
[LC-2055]: https://letscareer-team.atlassian.net/browse/LC-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2055]: https://letscareer-team.atlassian.net/browse/LC-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DRAFT] LC-2055 user 챌린지 개설시 멘토 등록 기능 추가

---

src/router-pages/common/challenge/MissionFeedback.tsx

- [LC-2081]
[LC-2081]: https://letscareer-team.atlassian.net/browse/LC-2081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2081 USER 피드백 페이지 LexicalContent 적용

---

src/api/user.ts
src/components/admin/user/users/filter/AdminUserFilter.tsx
src/router-pages/admin/user/AdminMentorPage.tsx

- [LC-2115]
[LC-2115]: https://letscareer-team.atlassian.net/browse/LC-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 멘토 관리 검색 기능 추가 + 페이지네이션 적용

---

src/components/common/home/new/banner/TopBanner.tsx
src/components/page/ReportNavigation.tsx
src/hooks/useScrollDirection.ts

- [LC-1985]
[LC-1985]: https://letscareer-team.atlassian.net/browse/LC-1985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1985 USER 홈 띠 배너 폰트 사이즈 수정 + 스크롤 시 숨기기

---

.cursor/rules/toss-frontend.mdc
.gitignore
src/components/BlogListContent.tsx
src/components/ProgramDetailNavigation.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/common/challenge-marketing-view/ChallengeTabNavigation.tsx
src/components/common/home/ProgramContainer.tsx
src/components/common/home/section/BottomBannerSection.tsx
src/components/common/home/section/MainBannerSection.tsx
src/components/common/home/section/RoadMapSection.tsx
src/components/common/report/ReportPlanSection.tsx
src/components/common/report/Tooltip.tsx
src/hooks/useProgramScrollDirectionStyle.ts
src/hooks/useScrollDirection.ts
src/utils/constants.ts

- [LC-1985]
[LC-1985]: https://letscareer-team.atlassian.net/browse/LC-1985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-1985 스크롤 방향에 따라 스타일 반환하는 useScrollDirectionStyle 훅 추가

---

src/components/common/home/BlogItem.tsx
src/components/common/home/ProgramItem.tsx

- [LC-2092]
[LC-2092]:https://letscareer-team.atlassian.net/browse/LC-2092?atlOrigin=eyJpIjoiNjk3NTc1OTQ3Zjg3NGZjMGEyNjYzZTMxMWIyYTE0NmUiLCJwIjoiaiJ9
[LC-2092]: https://letscareer-team.atlassian.net/browse/LC-2092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2092]: https://letscareer-team.atlassian.net/browse/LC-2092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2092 홈 썸네일 아이템에 border 0.7px 추가

---

src/router-pages/common/report/ReportManagementPage.tsx

- [LC-2061]
[LC-2061]:https://letscareer-team.atlassian.net/browse/LC-2061?atlOrigin=eyJpIjoiMWRmMGE3ZWY1YTRlNGZjZjg3NjdhZDZmNzJkY2EyMTEiLCJwIjoiaiJ9
[LC-2061]: https://letscareer-team.atlassian.net/browse/LC-2061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2061]: https://letscareer-team.atlassian.net/browse/LC-2061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2061 서류피드백이 없을 경우 신청하지 못하는 페이지로 랜딩되는 현상 수정

---

src/components/common/home/new/banner/TopBanner.tsx
src/components/common/ui/layout/header/NextNavBar.tsx
src/components/common/ui/layout/header/Spacer.tsx

- [LC-2126]
[LC-2126]:https://letscareer-team.atlassian.net/browse/LC-2126?atlOrigin=eyJpIjoiMjhhZjUxNzg2NGYwNDQzM2I2YjhmNDE5ODk4MTY1ZTgiLCJwIjoiaiJ9
[LC-2126]: https://letscareer-team.atlassian.net/browse/LC-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2126]: https://letscareer-team.atlassian.net/browse/LC-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DRAFT] LC-2126 상단 띠 배너 비노출시에도 스크롤시 색상 노출됨

---

.cursor/rules/commit-convention.mdc
src/components/common/program/programs/card/ProgramCard.tsx
src/reducers/filterReducer.ts
src/router-pages/common/program/Programs.tsx

refactor: 프로그램 컴포넌트 분리

---

src/components/common/challenge-marketing-view/ChallengePriceInfoContent.tsx

- [LC-2135]
[LC-2135]: https://letscareer-team.atlassian.net/browse/LC-2135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2135 USER 플랜이 하나일 때는 플랜 탭 숨기기

---

src/components/common/challenge-marketing-view/ChallengePriceInfoContent.tsx

- [LC-2135]
[LC-2135]: https://letscareer-team.atlassian.net/browse/LC-2135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2135 refactor(ChallengePriceInfoContent): console logs 제거

---

.cursor/rules/commit-convention.mdc
src/components/common/home/section/LetsCareerSection.tsx

- [LC-2156]
[LC-2156]: https://letscareer-team.atlassian.net/browse/LC-2156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2156 VOD 조회 개수 늘리기

---

src/Router.tsx
src/components/common/challenge/ui/layout/ChallengeLayout.tsx
src/components/common/challenge/ui/layout/NavBar.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/router-pages/common/challenge/DashboardMyMissionPage.tsx
src/router-pages/common/challenge/DashboardPage.tsx
src/router-pages/common/challenge/MyChallengeDashboard.tsx

- [LC-2166]
[LC-2166]: https://letscareer-team.atlassian.net/browse/LC-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2166 USER 챌린지 대시보드 분기 처리

---

src/Router.tsx
src/router-pages/common/challenge/ExperienceSummaryLatest.tsx
src/router-pages/common/challenge/MarketingLatest.tsx
src/router-pages/common/challenge/PersonalStatementLatest.tsx
src/router-pages/common/challenge/PortfolioLatest.tsx

- [LC-2155]
[LC-2155]:https://letscareer-team.atlassian.net/browse/LC-2155?atlOrigin=eyJpIjoiN2I4NDFmODc5OTc3NDM4MDgzNGQ5ZWJmMTZjMjE2NGYiLCJwIjoiaiJ9
[LC-2155]: https://letscareer-team.atlassian.net/browse/LC-2155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2155]: https://letscareer-team.atlassian.net/browse/LC-2155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2155 챌린지 상세페이지 랜딩 url 추출

---

src/router-pages/admin/challenge/ChallengeMissionManagement.tsx
src/router-pages/admin/challenge/ChallengeOperationParticipants.tsx
src/schema.ts

- [LC-2171]
[LC-2171]: https://letscareer-team.atlassian.net/browse/LC-2171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2171 ADMIN 미션 목록 zod 에러

---

src/components/common/challenge/DashboardLayout.tsx
src/router-pages/common/challenge/DashboardMyMissionPage.tsx
src/router-pages/common/challenge/DashboardPage.tsx

- [LC-2174]
[LC-2174]:https://letscareer-team.atlassian.net/browse/LC-2174?atlOrigin=eyJpIjoiY2RhNjgyNzIxMGJjNDQ4ZDliNWY4NzJiMWNiNTIxNjEiLCJwIjoiaiJ9
[LC-2174]: https://letscareer-team.atlassian.net/browse/LC-2174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2174]: https://letscareer-team.atlassian.net/browse/LC-2174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2174 user new 챌린지 대시보드 공통 내부요소 gap 추가

---

src/components/common/challenge/DashboardLayout.tsx
src/components/common/challenge/RecommendedProgramSection.tsx
src/components/common/challenge/RecommendedProgramSwiper.tsx
src/router-pages/common/challenge/ChallengeDashboard.tsx
src/router-pages/common/challenge/DashboardPage.tsx

- [LC-2153]
- ...
[LC-2153]: https://letscareer-team.atlassian.net/browse/LC-2153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2153 USER 챌린지 대시보드: 프로그램 추천 슬라이드 추가

---

src/api/review.ts
src/router-pages/admin/review/AdminBlogReviewListPage.tsx

- [LC-2162]
[LC-2162]: https://letscareer-team.atlassian.net/browse/LC-2162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2162 ADMIN 블로그 후기 관리: 연락처, 계좌번호 컬럼 추가 (API 연결)

---

src/Router.tsx
src/components/common/challenge/DashboardNavBar.tsx
src/router-pages/common/challenge/DashboardGuidePage.tsx

- [LC-2179]
[LC-2179]:https://letscareer-team.atlassian.net/browse/LC-2179?atlOrigin=eyJpIjoiY2MzNTA0M2IyOWYzNGFlMmJkODEwODNhMmM1ZGY3NTUiLCJwIjoiaiJ9
[LC-2179]: https://letscareer-team.atlassian.net/browse/LC-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2179]: https://letscareer-team.atlassian.net/browse/LC-2179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2179 user 공지사항 가이드라인 UI 구현

---

src/components/admin/challenge/ui/lineTable/LineTableBodyCell.tsx
src/router-pages/admin/challenge/ChallengeMissionManagement.tsx
src/schema.ts

- [LC-2157]
[LC-2157]:https://letscareer-team.atlassian.net/browse/LC-2157?atlOrigin=eyJpIjoiYWYxOTc2ZmYyNTA0NDdlYjk5OTQwNGEyYmUwZjk1MmYiLCJwIjoiaiJ9
[LC-2157]: https://letscareer-team.atlassian.net/browse/LC-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2157]: https://letscareer-team.atlassian.net/browse/LC-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2157 admin 미션 관리 미션 vod 추가

---

src/components/common/challenge/DashboardLayout.tsx
src/components/common/challenge/dashboard/section/ChallengeGuideSection.tsx
src/components/common/challenge/dashboard/section/DailyChallengeMissionSection.tsx
src/components/common/challenge/dashboard/section/NoticeBoardSection.tsx
src/components/common/challenge/my-challenge/mission-calendar/ChallengeMissionCalendar.tsx
src/components/common/challenge/my-challenge/mission-calendar/ChallengeMissionCalendarItem.tsx
src/components/common/challenge/my-challenge/section/MissionCalendarSection.tsx
src/index.css
src/router-pages/common/challenge/DashboardPage.tsx

- [LC-2154]
[LC-2154]: https://letscareer-team.atlassian.net/browse/LC-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2154 USER 챌린지 대시보드 반응형 추가

---

src/router-pages/common/challenge/DashboardMyMissionPage.tsx

- [LC-2192]
[LC-2192]:https://letscareer-team.atlassian.net/browse/LC-2192?atlOrigin=eyJpIjoiNzM0OTNhZjI4OTk4NGVlMDkyNmVkOTFiZjcxOTYyMTkiLCJwIjoiaiJ9
[LC-2192]: https://letscareer-team.atlassian.net/browse/LC-2192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2192]: https://letscareer-team.atlassian.net/browse/LC-2192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2192 user 보너스 미션 팝업노출 조건 미션 제출시 팝업 노출

---

src/api/challenge.ts
src/components/common/challenge/my-challenge/MissionSubmitBonusSection.tsx
src/components/common/challenge/my-challenge/MissionSubmitSection.tsx
src/router-pages/common/challenge/DashboardMyMissionPage.tsx

- [LC-2188]
[LC-2188]:https://letscareer-team.atlassian.net/browse/LC-2188?atlOrigin=eyJpIjoiNTZmNGY0MGRhNmEyNDU4OWFiN2NjZTM5YmNkMmVjZTAiLCJwIjoiaiJ9
[LC-2188]: https://letscareer-team.atlassian.net/browse/LC-2188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2188]: https://letscareer-team.atlassian.net/browse/LC-2188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2188 user 보너스 미션 api 연동

---

src/components/common/challenge/DashboardLayout.tsx
src/components/common/challenge/dashboard/section/ChallengeGuideSection.tsx
src/components/common/challenge/dashboard/section/NoticeBoardSection.tsx
src/components/common/challenge/my-challenge/mission-calendar/ChallengeMissionCalendarItem.tsx

- [LC-2196]
[LC-2196]: https://letscareer-team.atlassian.net/browse/LC-2196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2196 user 대시보드 UI 개선사항 반영

---

src/components/common/challenge/DashboardLayout.tsx
src/components/common/challenge/DashboardNavBar.tsx
src/components/common/challenge/my-challenge/BankSelectDropdown.tsx
src/components/common/challenge/my-challenge/LinkInputSection.tsx
src/components/common/challenge/my-challenge/MissionFileLink.tsx
src/components/common/challenge/my-challenge/MissionGuideBonusSection.tsx
src/components/common/challenge/my-challenge/MissionGuideZeroSection.tsx
src/components/common/challenge/my-challenge/MissionHeaderSection.tsx
src/components/common/challenge/my-challenge/MissionMentorCommentSection.tsx
src/components/common/challenge/my-challenge/MissionSubmitBonusSection.tsx
src/components/common/challenge/my-challenge/MissionSubmitRegularSection.tsx
src/components/common/challenge/my-challenge/MissionSubmitZeroSection.tsx
src/components/common/ui/layout/header/NavBar.tsx
src/components/common/ui/layout/header/NextNavBar.tsx
src/router-pages/common/challenge/DashboardMyMissionPage.tsx

- [LC-2201]
[LC-2201]:https://letscareer-team.atlassian.net/browse/LC-2201?atlOrigin=eyJpIjoiYjczOGI3YWEwNGEyNDJkYTgyMjJjYTZiMDI2MjdkZjEiLCJwIjoiaiJ9
[LC-2201]: https://letscareer-team.atlassian.net/browse/LC-2201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2201]: https://letscareer-team.atlassian.net/browse/LC-2201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2201 user 나의미션 모바일 반응형 UI 처리

---

src/api/challenge.ts
src/components/common/challenge/my-challenge/MissionGuideSection.tsx
src/components/common/challenge/my-challenge/MissionSubmitZeroSection.tsx

- [LC-2185]
[LC-2185]: https://letscareer-team.atlassian.net/browse/LC-2185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2185 USER 나의 미션 0회차 OT 챌린지 목표 API 연동

---

src/router-pages/common/challenge/DashboardMyMissionPage.tsx

- [LC-2207]
[LC-2207]:https://letscareer-team.atlassian.net/browse/LC-2207?atlOrigin=eyJpIjoiZTIwZWIyMzAyZjBjNGYyYmFhMTc0MTU2MjM0MTk0ODgiLCJwIjoiaiJ9
[LC-2207]: https://letscareer-team.atlassian.net/browse/LC-2207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2207]: https://letscareer-team.atlassian.net/browse/LC-2207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2207 현재 QA를 위해 4,6회차만 보이게 수정

---

src/components/common/challenge/my-challenge/MissionGuideBonusSection.tsx

LC-2204 보너스 미션 상세 콘텐츠

---

src/components/common/challenge/my-challenge/MissionSubmitBonusSection.tsx

- [LC-2232]
[LC-2232]:https://letscareer-team.atlassian.net/browse/LC-2232?atlOrigin=eyJpIjoiNDczMDQ2NDQxMTYxNGY4ZWE4NmEyZWY4NThmZmQ3NTQiLCJwIjoiaiJ9
[LC-2232]: https://letscareer-team.atlassian.net/browse/LC-2232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2232]: https://letscareer-team.atlassian.net/browse/LC-2232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2234 보너스미션-계좌-입력란에-숫자-이외의-문자-입력시-제출되지-않도록 변경

---

src/components/common/challenge/my-challenge/MissionGuideZeroSection.tsx

- [LC-2229]
[LC-2229]:https://letscareer-team.atlassian.net/browse/LC-2229?atlOrigin=eyJpIjoiYmY0MjA5MWI5ZDVjNGEzMGJlNWUyODhjNzQ2OWQ5MTYiLCJwIjoiaiJ9
[LC-2229]: https://letscareer-team.atlassian.net/browse/LC-2229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2229]: https://letscareer-team.atlassian.net/browse/LC-2229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2229 user 나의 미션 첨부파일 열리지 않음

---

public/icons/check-gray-outline.svg
src/components/common/challenge/my-challenge/mission-calendar/ChallengeMissionCalendarItem.tsx
tailwind.config.js

- [LC-2203]
[LC-2203]: https://letscareer-team.atlassian.net/browse/LC-2203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2203 미션현황 카드 디자인 변경

---

src/components/common/challenge/my-challenge/MissionGuideBonusSection.tsx
src/components/common/challenge/my-challenge/MissionGuideRegularSection.tsx
src/components/common/challenge/my-challenge/MissionGuideZeroSection.tsx
src/components/common/challenge/my-challenge/MissionHeaderSection.tsx
src/components/common/challenge/my-challenge/menu/AbsentMissionSubmitMenu.tsx
src/components/common/challenge/my-challenge/mission/AbsentMissionDetailMenu.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionDetailMenu.tsx
src/components/common/challenge/my-challenge/mission/YetMissionDetailMenu.tsx

- [LC-2254]
[LC-2254]:https://letscareer-team.atlassian.net/browse/LC-2254?atlOrigin=eyJpIjoiZmRmY2Y2ZGRkZWI4NGFkYWFmNDc4ZmY5OTNkOTU0MGYiLCJwIjoiaiJ9

LC-2254 user 나의미션 0회차에 today th로 설정되어있는 문제

---

src/components/common/challenge/my-challenge/MissionGuideRegularSection.tsx
src/components/common/challenge/my-challenge/MissionSubmitSection.tsx
src/lib/dayjs.ts
src/router-pages/common/challenge/DashboardMyMissionPage.tsx

- [LC-2251]
[LC-2251]:https://letscareer-team.atlassian.net/browse/LC-2251?atlOrigin=eyJpIjoiODc5ZjA3MmYwZWViNGYzOTk5N2E4ZmE5NjE0Y2ZhNGUiLCJwIjoiaiJ9
[LC-2251]: https://letscareer-team.atlassian.net/browse/LC-2251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2251]: https://letscareer-team.atlassian.net/browse/LC-2251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2251 user 나의미션 아직 오픈전인 미션 클릭시 미션 상세페이지 수정

---

src/components/common/challenge/my-challenge/MissionSubmitRegularSection.tsx
src/components/common/challenge/my-challenge/MissionSubmitSection.tsx
src/router-pages/common/challenge/DashboardMyMissionPage.tsx

- [LC-2240]
[LC-2240]:https://letscareer-team.atlassian.net/browse/LC-2240?atlOrigin=eyJpIjoiMTFiNmQ5Yjg3OTViNGZiNzlhMmYzNTUxNTlhZDg3MGMiLCJwIjoiaiJ9
[LC-2240]: https://letscareer-team.atlassian.net/browse/LC-2240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2240]: https://letscareer-team.atlassian.net/browse/LC-2240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2240 데이터 제출, 수정할때마다 refetch하도록 수정

---

src/components/common/challenge/my-challenge/MissionGuideBonusSection.tsx
src/components/common/challenge/my-challenge/MissionGuideRegularSection.tsx

- [LC-2253]
[LC-2253]:https://letscareer-team.atlassian.net/browse/LC-2253?atlOrigin=eyJpIjoiNzU5N2RlNDUxZmNjNDIxMThkMjFmYWFmOTZlNTcwMjEiLCJwIjoiaiJ9
[LC-2253]: https://letscareer-team.atlassian.net/browse/LC-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2253]: https://letscareer-team.atlassian.net/browse/LC-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2253 모바일 0회차 이외 미션 폰트 사이즈

---

src/components/common/challenge/my-challenge/MissionSubmitButton.tsx
src/components/common/challenge/my-challenge/MissionSubmitZeroSection.tsx
src/router-pages/common/challenge/DashboardMyMissionPage.tsx

- [LC-2264]
[LC-2264]:https://letscareer-team.atlassian.net/browse/LC-2264?atlOrigin=eyJpIjoiZmM0NzQ2YjhlMTYyNDMxN2JlNjNkMjYxOWUwZGExMmYiLCJwIjoiaiJ9
[LC-2264]: https://letscareer-team.atlassian.net/browse/LC-2264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2264]: https://letscareer-team.atlassian.net/browse/LC-2264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2264 user 0회차 ot미션 제출 완료시 수정할 수 없음

---

src/components/common/challenge/my-challenge/mission-calendar/ChallengeMissionCalendarItem.tsx
src/lib/dayjs.ts
src/router-pages/common/challenge/DashboardPage.tsx

- [LC-2257]
[LC-2257]: https://letscareer-team.atlassian.net/browse/LC-2257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2257 미션 기한 남았을 경우, 미션 표시

---

src/components/common/challenge/dashboard/section/ChallengeGuideSection.tsx
src/components/common/challenge/dashboard/section/NoticeBoardSection.tsx

- [LC-2292]
[LC-2292]: https://letscareer-team.atlassian.net/browse/LC-2292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2292 Feat : 공지, 가이드 숨기기

---

src/api/attendance.ts
src/api/attendanceSchema.ts
src/api/challenge.ts
src/components/admin/challenge/submit-check-detail/table/table-body/CommentCell.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/ResultDropdown.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/StatusDropdown.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/TableRow.tsx
src/components/admin/review/VisibilityToggle.tsx
src/components/common/challenge/my-challenge/menu/AbsentMissionSubmitMenu.tsx
src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
src/router-pages/admin/challenge/ChallengeFeedbackPage.tsx
src/router-pages/admin/challenge/FeedbackParticipantPage.tsx
src/schema.ts

- [LC-2300]
[LC-2300]: https://letscareer-team.atlassian.net/browse/LC-2300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2300 ADMIN/USER 새 출석 API 적용

---

src/api/challenge.ts
src/components/common/challenge/DailyMissionLinkInputSection.tsx
src/components/common/challenge/DailyMissionReviewSection.tsx
src/components/common/challenge/OtMissionInputSection.tsx
src/components/common/challenge/OtVideo.tsx
src/components/common/challenge/my-challenge/dropdown/ContentsDropdown.tsx
src/components/common/challenge/my-challenge/dropdown/MenuContentsDropdown.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionCalendar.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionCalendarItem.tsx
src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionDetailMenu.tsx
src/components/common/challenge/my-challenge/section/DailyMissionInfoSection.tsx
src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx
src/components/common/challenge/my-challenge/section/MissionCalendarSection.tsx
src/components/common/challenge/my-challenge/section/OtherMissionSection.tsx
src/components/common/challenge/ui/layout/ChallengeLayout.tsx
src/components/common/challenge/ui/layout/NavBar.tsx
src/context/CurrentChallengeProvider.tsx
src/router-pages/common/challenge/ChallengeDashboard.tsx
src/router-pages/common/challenge/ChallengeUserInfo.tsx
src/router-pages/common/challenge/MyChallengeDashboard.tsx
src/schema.ts

- [LC-2301]
- [LC-2309]
[LC-2301]: https://letscareer-team.atlassian.net/browse/LC-2301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2309]: https://letscareer-team.atlassian.net/browse/LC-2309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2301 USER 구 대시보드: 0회차(OT) 미션 추가, 챌린지 대시보드 추가정보 입력 페이지: 목표 입력란 제거 및 유효성 검증 로직 수정

---

src/api/review.ts
src/router-pages/admin/review/AdminBlogReviewListPage.tsx
src/utils/convert.ts

- [LC-2314]
[LC-2314]: https://letscareer-team.atlassian.net/browse/LC-2314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2314 ADMIN 블로그 후기: 연락처, 은행, 계좌번호 컬럼 추가

---

src/router-pages/admin/review/AdminBlogReviewListPage.tsx

- [LC-2315]
[LC-2315]: https://letscareer-team.atlassian.net/browse/LC-2315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2315 ADMIN 블로그 후기: csv 다운로드 추가

---

src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
src/components/common/challenge/my-challenge/mission/YetMissionItem.tsx
src/router-pages/common/challenge/ChallengeDashboard.tsx
src/router-pages/common/challenge/MyChallengeDashboard.tsx

대시보드 자잘한 에러 수정

---

src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/footer/NextFooter.tsx
src/components/common/ui/layout/header/NavBar.tsx
src/components/common/ui/layout/header/NextNavBar.tsx

- [LC-2239]
[LC-2239]: https://letscareer-team.atlassian.net/browse/LC-2239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2239 VOD 추가 (HOTFIX)

---

src/api/review.ts
src/components/common/challenge/BonusMissionSubmitMenu.tsx
src/components/common/challenge/OtMissionSubmitMenu.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionCalendarItem.tsx
src/components/common/challenge/my-challenge/mission/AbsentMissionDetailMenu.tsx
src/components/common/challenge/my-challenge/section/DailyMissionSection.tsx
src/schema.ts

- [LC-2345]
[LC-2345]: https://letscareer-team.atlassian.net/browse/LC-2345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2345 USER 구 대시보드: AbsentMissionDetailMenu에 OT, 보너스 미션 적용

---

src/components/common/challenge/dashboard/section/DailyMissionSection.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionCalendarItem.tsx
src/components/common/challenge/ui/layout/ChallengeLayout.tsx
src/components/common/challenge/ui/layout/NavBar.tsx
src/router-pages/common/challenge/ChallengeDashboard.tsx

- [LC-2304]
[LC-2304]: https://letscareer-team.atlassian.net/browse/LC-2304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2304 미션 클릭 시 페이지 이동 로직 수정

---

src/router-pages/common/challenge/MyChallengeDashboard.tsx

- [LC-2303]
[LC-2303]: https://letscareer-team.atlassian.net/browse/LC-2303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2303-feat-나의 미션, 챌린지 상태 변경

---

src/components/admin/challenge/submit-check-detail/filter/ResultFilter.tsx
src/components/common/challenge/my-challenge/mission/AgreementCheckbox.tsx
src/components/common/challenge/my-challenge/mission/MissionSubmitButton.tsx
src/components/common/challenge/my-challenge/section/MissionCalendarSection.tsx
src/components/common/challenge/my-challenge/section/MissionGuideBonusSection.tsx
src/components/common/challenge/my-challenge/section/MissionGuideZeroSection.tsx
src/components/common/challenge/my-challenge/section/MissionHeaderSection.tsx
src/components/common/challenge/my-challenge/section/MissionSubmitBonusSection.tsx
src/components/common/challenge/my-challenge/section/MissionSubmitRegularSection.tsx
src/components/common/challenge/my-challenge/section/MissionSubmitSection.tsx
src/components/common/challenge/my-challenge/section/MissionSubmitZeroSection.tsx
src/router-pages/common/challenge/ChallengeDashboard.tsx
src/router-pages/common/challenge/MyChallengeDashboard.tsx
src/schema.ts

- [LC-2316]
- [LC-2349]
- [LC-2351]
- [LC-2356]
- [LC-2357]
[LC-2316]: https://letscareer-team.atlassian.net/browse/LC-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2349]: https://letscareer-team.atlassian.net/browse/LC-2349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2351]: https://letscareer-team.atlassian.net/browse/LC-2351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2356]: https://letscareer-team.atlassian.net/browse/LC-2356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2357]: https://letscareer-team.atlassian.net/browse/LC-2357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …

LC-2316 USER 구 나의 미션 스타일링

---

src/components/common/challenge/dashboard/section/DailyMissionSection.tsx
src/components/common/challenge/dashboard/section/GuideSection.tsx
src/components/common/challenge/dashboard/section/ScoreSection.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionCalendarItem.tsx
src/components/common/challenge/ui/layout/NavBar.tsx

- [LC-2364]
[LC-2364]: https://letscareer-team.atlassian.net/browse/LC-2364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2364-제출 상태 활성화 조건을 페이지별로 다르게 적용

---

src/components/challenge-view/ChallengeCheckList.tsx

- [LC-2402]
[LC-2402]: https://letscareer-team.atlassian.net/browse/LC-2402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2402 대기업 챌린지내 페이백 워딩 삭제

---

src/components/OldMyDailyMissionSection.tsx
src/components/common/challenge/OldGuideSection.tsx
src/router-pages/common/challenge/OldChallengeUserInfo.tsx

- [LC-2413]
[LC-2413]: https://letscareer-team.atlassian.net/browse/LC-2413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2413 USER 구 대시보드 분기처리 되도록 복구 작업

---

public/icons/Arrow_Left.svg
src/components/common/challenge/my-challenge/section/MissionMentorCommentSection.tsx
src/components/common/challenge/my-challenge/section/MissionSubmitRegularSection.tsx
src/hooks/useMissionCalculation.ts
src/router-pages/common/challenge/ChallengeDashboard.tsx
src/router-pages/common/challenge/MyChallengeDashboard.tsx

- [LC-2400]
- [LC-2423]
- [LC-2431]
[LC-2400]: https://letscareer-team.atlassian.net/browse/LC-2400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2423]: https://letscareer-team.atlassian.net/browse/LC-2423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2431]: https://letscareer-team.atlassian.net/browse/LC-2431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2400, LC-2423, LC-2431-V2-QA 반영

---

src/components/common/challenge/ui/layout/NavBar.tsx
src/hooks/useMissionCalculation.ts

- [LC-2441]
- [LC-2439]
[LC-2441]: https://letscareer-team.atlassian.net/browse/LC-2441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2439]: https://letscareer-team.atlassian.net/browse/LC-2439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2441-USER 미션이 모두 미제출 상태로 노출

---

src/Router.tsx
src/api/challenge.ts
src/components/common/challenge/NoticeGuideLink.tsx
src/components/common/challenge/dashboard/section/GuideSection.tsx
src/components/common/challenge/dashboard/section/NoticeSection.tsx
src/components/common/challenge/ui/layout/NavBar.tsx
src/router-pages/common/challenge/ChallengeGuidePage.tsx

- [LC-2305]
- [LC-2306]
[LC-2305]: https://letscareer-team.atlassian.net/browse/LC-2305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2306]: https://letscareer-team.atlassian.net/browse/LC-2306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2305 USER 공지사항/가이드 페이지 추가 

---

src/components/common/challenge/my-challenge/mission/DoneMissionDetailMenu.tsx

- [LC-2444]
[LC-2444]: https://letscareer-team.atlassian.net/browse/LC-2444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2444-feat-USER 멘토 미션 피드백 페이지 랜딩 오류

---

src/components/ProgramRecommendEditor.tsx
src/components/admin/ui/section/MoreButtonSection.tsx
src/components/common/challenge/ui/layout/ChallengeLayout.tsx

- [LC-2318]
[LC-2318]:https://letscareer-team.atlassian.net/browse/LC-2318?atlOrigin=eyJpIjoiNWNjZTZjM2JhMjE0NDQwYmFkNjlhYWNjZmZkOThlYWMiLCJwIjoiaiJ9
[LC-2318]: https://letscareer-team.atlassian.net/browse/LC-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2318]: https://letscareer-team.atlassian.net/browse/LC-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2318 admin 챌린지 운영 추천 프로그램 더보기 추가

---

src/components/common/challenge/my-challenge/section/RecommendedProgramSection.tsx

- [LC-2288]
[LC-2288]:https://letscareer-team.atlassian.net/browse/LC-2288?atlOrigin=eyJpIjoiZWJiOGFkZTljMWYyNDE0M2JmNGNjNTY3ZmZiN2E3NTAiLCJwIjoiaiJ9
[LC-2288]: https://letscareer-team.atlassian.net/browse/LC-2288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-2288]: https://letscareer-team.atlassian.net/browse/LC-2288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-2288 프로그램 추천 안내 텍스트 변경
