src/components/common/program/program-detail/ui/price/CautionPriceContent.tsx

[#471] 메인 브랜치에 개발 브랜치 수정사항 반영

---

src/components/common/auth/modal/PrivacyPolicyModal.tsx
src/components/common/ui/layout/Footer.tsx
src/pages/common/auth/SignUp.tsx

[#475] 개인정보처리방침 및 서비스이용약관 링크 수정

---

src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx

[#497] 챌린지 어드민 제출확인 20행만 나오는 오류 수정

---

src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx

Reverts Let-s-intern/lets-intern-client#498

Revert "[#497] 챌린지 어드민 제출확인 20행만 나오는 오류 수정"

---

src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx

[#496] CSV 다운로드 시 입금 예정 금액 행 나누어지는 오류 수정

---

src/components/common/challenge/my-challenge/section/DailyMissionSection.tsx
src/components/common/ui/layout/Footer.tsx
src/components/common/ui/layout/Layout.tsx
src/components/common/ui/layout/LayoutRegacy.tsx
src/components/common/ui/layout/NavBar.tsx
src/components/common/ui/tab/TabItemRegacy.tsx
src/pages/common/program/Programs.module.scss

> Close #515
- **Footer**, **NavBar** 코드는 별도의 폴더에 들어있어서 기존 main Footer, NavBar 코드만 추가했습니다.
- **TabItem**은 별도의 regacy 파일로 생성했습니다 (Tailwind만 수정했었습니다)

[#515] Regacy 파일 생성

---

src/components/admin/program/program-user/table-content/TableHead.tsx
src/components/admin/program/program-user/table-content/TableRow.tsx
src/components/admin/program/programs/table-content/TableBody.tsx
src/components/admin/program/programs/table-content/TableHead.tsx
src/pages/admin/program/ProgramUsers.tsx
src/utils/convert.ts

[#521] 어드민 프로그램 및 프로그램 참여자 페이지 열 수정 및 순서 변경

---

src/components/admin/program/ui/editor-section/ProgramTypeSection.tsx
src/components/admin/program/ui/editor/ProgramEditor.tsx

[#523] 어드민 프로그램 개설 입력 폼 변경

---

src/components/admin/challenge/mission/mission-contents/table/table-body/TableBody.tsx
src/components/common/home/regacy/header/HomeHeader.tsx
src/pages/admin/program/ProgramUsers.tsx
src/pages/common/home/HomeRegacy.tsx

[#525] 메인 배포 페이지 수정사항 반영 (main)

---

src/components/admin/program/ui/editor/ProgramEditor.tsx
src/components/common/ui/layout/NavBar.tsx
src/pages/admin/program/ProgramCreate.tsx
src/pages/admin/program/Programs.tsx
src/pages/common/auth/Login.tsx
src/pages/common/auth/SignUp.tsx
src/utils/convert.ts

[#528] 회원 API 및 프로그램 개설 API 교체

---

src/components/admin/ui/layout/AdminLayout.tsx
src/components/common/ui/layout/NavBar.tsx
src/pages/admin/program/Programs.tsx

[#533] 유저 정보와 관리자 확인 API 교체

---

src/components/admin/challenge/home/item/GuideItem.tsx
src/components/admin/challenge/home/section/GuideSection.tsx
src/components/admin/challenge/home/section/MissionDateSection.tsx
src/components/admin/challenge/home/section/NoticeSection.tsx
src/components/admin/challenge/ui/modal/GuideEditorModal.tsx
src/components/admin/challenge/ui/modal/InputBox.tsx
src/interfaces/Guide.interface.ts
src/interfaces/interface.ts
src/pages/admin/challenge/ChallengeHome.tsx

> Close #517
API 코드 작성했으나 잘 동작하는지 추후에 확인 필요

[#517] 챌린지 가이드 게시판 추가

---

src/components/admin/challenge/user/table/table-body/TableRowContent.tsx
src/components/admin/challenge/user/table/table-head/TableHead.tsx
src/interfaces/Application.interface.ts
src/interfaces/interface.ts
src/utils/tableCellWidthList.ts

> Close #519
챌린지 운영 쪽 기획이 확정되지 않아서 당장 API 연결이 불가합니다.

[#519] 참여자 리스트 노출 변경

---

src/components/admin/challenge/home/item/MissionDateItem.tsx
src/components/admin/challenge/home/item/MissionResultItem.tsx
src/components/admin/challenge/mission/mission/table/table-body/TableBodyRow.tsx
src/components/admin/challenge/mission/mission/table/table-body/TableRowContent.tsx
src/components/admin/challenge/mission/mission/table/table-body/TableRowDetailMenu.tsx
src/components/admin/challenge/mission/mission/table/table-body/TableRowEditorMenu.tsx
src/components/admin/challenge/submit-check/table/table-body/TableRowContent.tsx
src/components/admin/challenge/ui/dropdown/home/TopDropdown.tsx
src/components/admin/program/program-user/bottom-action/BottomAction.tsx
src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
src/components/common/challenge/dashboard/mission-calendar/MissionCalendarItem.tsx
src/components/common/challenge/dashboard/mission-calendar/MissionIcon.tsx
src/components/common/challenge/dashboard/mission-calendar/MissionNotStartedIcon.tsx
src/components/common/challenge/dashboard/mission-calendar/MissionTodayIcon.tsx
src/components/common/challenge/dashboard/section/DailyMissionSection.tsx
src/components/common/challenge/dashboard/section/ScoreSection.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionCalendarItem.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionIcon.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionNotStartedIcon.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionTodayIcon.tsx
src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionItem.tsx
src/components/common/challenge/my-challenge/mission/YetMissionItem.tsx
src/components/common/challenge/my-challenge/section/DailyMissionSection.tsx
src/components/common/challenge/my-challenge/section/MissionCalendarSection.tsx
src/components/common/home/regacy/header/HomeHeader.tsx
src/pages/admin/program/ProgramUsers.tsx

[#536] 챌린지 대시보드 임시 개편 및 오류 수정

---

src/components/common/challenge/dashboard/section/ScoreSection.tsx
src/components/common/challenge/my-challenge/section/DailyMissionInfoSection.tsx
src/pages/common/challenge/ChallengeDashboard.tsx

[#539] 챌린지 대시보드 임시 개편 마무리

---

src/components/admin/challenge/mission/mission/table/table-body/TableBody.tsx
src/components/admin/challenge/mission/mission/table/table-head/TableHead.tsx
src/components/admin/challenge/submit-check/table/table-body/TableBody.tsx
src/components/admin/challenge/submit-check/table/table-head/TableHead.tsx

[#545] 어드민 챌린지 테이블 번호를 회차로 변경

---

src/Router.tsx
src/components/common/challenge/dashboard/section/ScoreSection.tsx
src/components/common/challenge/ui/layout/NavBar.tsx

[#549] 챌린지 대시보드 일부 항목 숨기기

---

src/Router.tsx
src/components/common/challenge/dashboard/section/ScoreSection.tsx
src/components/common/challenge/ui/layout/NavBar.tsx

[#549] 챌린지 대시보드 일부 항목 숨기기 (develop)

---

src/components/admin/challenge/home/section/GuideSection.tsx
src/components/admin/challenge/home/section/MissionDateSection.tsx
src/components/admin/challenge/home/section/MissionResultSection.tsx
src/components/admin/challenge/home/section/NoticeSection.tsx
src/components/admin/challenge/ui/lineTable/LineTableBodyRow.tsx
src/pages/admin/challenge/ChallengeMission.tsx
src/pages/admin/challenge/ChallengeMissionManagement.tsx
src/reducers/missionTemplateReducer.ts

> Close #548 
- 미션 템플릿 API만 테스트한 상태
- 미션태그 컬럼 추가 예정
- 챌린지 가이드와 챌린자 참여자 API 추후 확인 필요

[#548] 미션 템플릿 API 수정

---

src/Router.tsx
src/components/admin/program/ui/editor/ProgramInputContent.tsx
src/components/common/mypage/review/section/DoneSection.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/components/common/review/score/StarScore.tsx
src/components/common/review/score/TenScore.tsx
src/components/common/review/score/YesNoScore.tsx
src/components/common/review/section/ConfirmSection.tsx
src/components/common/review/section/StarScoreSection.tsx
src/components/common/review/section/TenScroeSection.tsx
src/components/common/review/section/TextAreaSection.tsx
src/pages/admin/program/ProgramEditor.tsx
src/pages/common/mypage/Application.tsx
src/pages/common/mypage/Review.tsx
src/pages/common/review/ReviewCreate.tsx

[#560] QA 직전 최종 수정하기

---

src/components/admin/program/ui/editor/ProgramInputContent.tsx
src/pages/admin/program/ProgramEditor.tsx
src/utils/convert.ts

[#565] 프로그램 개설 오류 수정

---

src/components/common/program/banner/Banner.tsx
src/components/common/program/filter/FilterSideBar.tsx
src/components/common/program/programs/card/EmptyCardList.tsx
src/components/common/program/programs/card/ProgramCard.tsx
src/pages/common/program/Programs.tsx

[#564] 프로그램 페이지 2차 QA 반영

---

src/components/common/program/programs/card/ProgramCard.tsx

[#569] 프로그램 페이지 2.5차 QA 수정 사항 반영

---

src/components/common/home/regacy/header/HomeHeader.tsx

[#572] 배너 타이틀 19기로 변경

---

public/icons/circle-checked.svg
public/icons/circle-unchecked.svg
src/components/admin/program/programs/table-content/TableBody.tsx
src/components/admin/program/ui/editor/FAQEditor.tsx
src/components/admin/program/ui/editor/ProgramInputContent.tsx
src/components/common/program/program-detail/apply/content/CautionContent.tsx
src/components/common/program/program-detail/apply/content/InputContent.tsx
src/components/common/program/program-detail/apply/content/OverviewContent.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/apply/section/MotiveAnswerSection.tsx
src/components/common/program/program-detail/apply/section/UserInputSection.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/tab/tab-content/DetailTabContent.tsx
src/components/common/program/program-detail/tab/tab-content/ReviewTabContent.tsx
src/components/common/program/program-detail/toggle/DateToggle.tsx
src/components/common/ui/input/TextArea.tsx
src/pages/admin/program/ProgramEditor.tsx
src/pages/admin/program/Programs.tsx

[#570] 1차 QA 수정사항 반영

---

package-lock.json
package.json
src/App.tsx
src/components/admin/program/ui/editor/FAQEditor.tsx
src/components/admin/program/ui/editor/ProgramInputContent.tsx
src/components/admin/review/review-detail/table-content/TableBody.tsx
src/components/admin/review/review-detail/table-content/TableHead.tsx
src/components/admin/review/reviews/table-content/TableBody.tsx
src/components/common/program/program-detail/apply/content/OverviewContent.tsx
src/components/common/program/program-detail/apply/section/PayInfoSection.tsx
src/components/common/program/program-detail/toggle/DateToggle.tsx
src/pages/admin/program/ProgramEditor.tsx
src/pages/admin/review/Reviews.tsx
src/pages/admin/review/ReviewsDetail.tsx

[#576] 어드민 후기 관리 페이지 제작

---

src/components/common/program/pagination/MuiPagination.tsx
src/components/common/program/programs/card/ProgramCard.tsx
src/components/common/program/programs/card/ProgramClassificationTag.tsx
src/pages/common/program/Programs.tsx

[#578 ] 프로그램 페이지 2.6차 QA 수정사항 반영

---

src/App.tsx
src/components/admin/banner/main-banner/MainBannerInputContent.tsx
src/components/admin/banner/pop-up-banner/PopUpBannerInputContent.tsx
src/components/admin/banner/program-banner/ProgramBannerInputContent.tsx
src/components/admin/banner/top-bar-banner/TopBarBannerInputContent.tsx
src/components/admin/review/review-detail/table-content/TableBody.tsx
src/pages/admin/banner/main-banner/MainBannerCreate.tsx
src/pages/admin/banner/main-banner/MainBannerEdit.tsx
src/pages/admin/banner/pop-up-banner/PopUpBannerCreate.tsx
src/pages/admin/banner/pop-up-banner/PopUpBannerEdit.tsx
src/pages/admin/banner/program-banner/ProgramBannerCreate.tsx
src/pages/admin/banner/program-banner/ProgramBannerEdit.tsx
src/pages/admin/banner/top-bar-banner/TopBarBannerCreate.tsx
src/pages/admin/banner/top-bar-banner/TopBarBannerEdit.tsx
src/pages/admin/review/ReviewsDetail.tsx

[#586] 배너 수정 기능 완성

---

src/components/admin/program/programs/table-content/TableBody.tsx
src/components/admin/review/reviews/table-content/TableBody.tsx
src/components/admin/ui/button/ActionButton.tsx
src/components/admin/user/users/table-content/TableBody.tsx
src/pages/admin/banner/main-banner/MainBanners.tsx
src/pages/admin/banner/pop-up-banner/PopUpBanners.tsx
src/pages/admin/banner/program-banner/ProgramBanners.tsx
src/pages/admin/banner/top-bar-banner/TopBarBanners.tsx
src/pages/admin/coupon/Coupons.tsx
src/pages/admin/program/Programs.tsx
src/pages/admin/review/Reviews.tsx
src/pages/admin/review/ReviewsDetail.tsx
src/pages/admin/user/Users.tsx

[#!590] 어드민 QA 전 마무리 2차

---

src/components/common/home/new/banner/Banner.tsx
src/components/common/home/new/banner/TopBanner.tsx
src/components/common/home/new/overview/ProgramOverviewListItem.tsx
src/components/common/home/new/ui/Popup.tsx
src/interfaces/Banner.interface.ts

[#592] 홈 화면 api 연동 및 날짜 상태 관리

---

src/components/common/program/program-detail/section/ApplySection.tsx

> Close #600 
https://www.notion.so/letsintern/cb48d78851a54c509ec41b383fc60ac6?pvs=4

[#600] 프로그램 신청완료 상태 반영 안되는 오류 수정

---

src/components/common/program/program-detail/section/MobileApplySection.tsx

[Fix] coupon 관련 타입 오류 수정

---

src/components/common/auth/modal/MarketingModal.tsx
src/components/common/auth/ui/InfoContainer.tsx
src/components/common/auth/ui/PrivacyLink.tsx
src/components/common/auth/ui/SocialLogin.tsx
src/pages/common/auth/SignUp.tsx
src/utils/axios.ts

[Feat] 회원가입 시 유입경로 및 추가 정보 레이아웃(와이어프레임) 구현, API 연결

---

src/components/admin/banner/main-banner/MainBannerInputContent.tsx
src/components/admin/banner/pop-up-banner/PopUpBannerInputContent.tsx
src/components/admin/banner/program-banner/ProgramBannerInputContent.tsx
src/interfaces/Banner.interface.ts
src/pages/admin/banner/main-banner/MainBannerCreate.tsx
src/pages/admin/banner/main-banner/MainBannerEdit.tsx
src/pages/admin/banner/main-banner/MainBanners.tsx
src/pages/admin/banner/pop-up-banner/PopUpBannerCreate.tsx
src/pages/admin/banner/pop-up-banner/PopUpBannerEdit.tsx
src/pages/admin/banner/pop-up-banner/PopUpBanners.tsx
src/pages/admin/banner/program-banner/ProgramBannerCreate.tsx
src/pages/admin/banner/program-banner/ProgramBannerEdit.tsx
src/pages/admin/banner/program-banner/ProgramBanners.tsx
src/pages/admin/banner/top-bar-banner/TopBarBannerCreate.tsx
src/pages/admin/banner/top-bar-banner/TopBarBannerEdit.tsx
src/pages/admin/banner/top-bar-banner/TopBarBanners.tsx

[#609] 어드민 모바일 배너 이미지 업로드 기능 추가

---

src/components/admin/challenge/mission/mission/table/table-body/TableRowDetailMenu.tsx
src/components/admin/challenge/submit-check-detail/filter/ResultFilter.tsx
src/components/admin/challenge/submit-check-detail/filter/StatusFilter.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/CommentCell.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/ResultDropdown.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/StatusDropdown.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/TableRow.tsx
src/components/admin/challenge/submit-check-detail/table/table-head/TableHead.tsx
src/components/admin/challenge/submit-check/table/table-body/ChallengeSubmitDetail.tsx
src/components/admin/challenge/ui/lineTable/LineTableBodyRow.tsx
src/pages/admin/challenge/ChallengeOperationAttendances.tsx
src/pages/common/challenge/MyChallengeDashboard.tsx
src/schema.ts
src/utils/tableCellWidthList.ts

> Close #
[## 사진](https://www.notion.so/letsintern/ADMIN-f20f711d4538465bbfaca8e3bff096a5?pvs=4)

제출확인 로드/수정할 수 있도록 개선 (검증 필요)

---

package-lock.json
package.json
src/components/common/auth/modal/PrivacyPolicyModal.tsx
src/components/common/auth/ui/InfoContainer.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/pages/common/auth/FindPassword.tsx
src/pages/common/auth/Login.tsx
src/pages/common/auth/SignUp.tsx
src/store/useAuthStore.ts

> Close #614 
- 비밀번호 변경 시 이메일 전송 후 로그인으로 이동
- 개인정보 동의 내용 워딩 수정
- zustand 도입 > useAuthStore 에서 isLoggedIn, login, logout 이용하면 됨

[Fix] 회원가입 페이지 수정

---

src/components/common/mypage/review/section/WaitingSection.tsx

- 마이페이지 > 후기 에서 프로그램 신청하기 버튼 라우팅 수정

[Fix] QA 진행 중 프로그램 관련 수정

---

src/components/common/program/program-detail/tab/tab-content/ReviewTabContent.tsx

[Feat] 프로그램 상세 리뷰 조회 api 연동 수정

---

src/components/admin/challenge/home/section/GuideSection.tsx
src/components/admin/challenge/home/section/NoticeSection.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionTodayIcon.tsx
src/pages/admin/challenge/ChallengeContents.tsx
src/pages/admin/challenge/ChallengeMissionManagement.tsx
src/pages/admin/challenge/ChallengeOperationHome.tsx
src/pages/admin/challenge/ChallengeOperationPayback.tsx
src/pages/common/mypage/Application.tsx

[#630] 챌린지 어드민 2차 QA 수정사항 반영

---

src/pages/admin/challenge/ChallengeMissionManagement.tsx

[#632] 챌린지 어드민 미션 관리 수정 아이콘 안 보이는 오류 수정

---

src/Router.tsx
src/components/common/mypage/privacy/section/BasicInfo.tsx
src/pages/common/mypage/Application.tsx
src/pages/common/mypage/MyPage.tsx
src/pages/common/mypage/Privacy.tsx
src/pages/common/mypage/Review.tsx
src/pages/common/program/ProgramDetail.tsx
src/pages/common/review/ReviewCreate.tsx
src/utils/axios.ts

- 로그인 연결 리다이렉트
- 회원탈퇴 추가
- 리뷰 수정 추가
등 추가되었습니다.

[Feat] QA 요청사항 반영 2차

---

src/components/admin/program/program-user/bottom-action/BottomAction.tsx
src/components/admin/program/program-user/bottom-action/ChallengeActionDropdown.tsx
src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
src/components/admin/program/program-user/table-content/TableRow.tsx
src/components/admin/program/ui/editor/ProgramInputContent.tsx
src/components/common/mypage/application/section/CompleteSection.tsx
src/components/common/mypage/application/section/ParticipateSection.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/pages/admin/program/ProgramEditor.tsx
src/pages/admin/program/ProgramUsers.tsx
src/pages/admin/review/Reviews.tsx
src/pages/common/mypage/Review.tsx

[#635] 어드민 챌린지 제외 QA 수정사항 반영

---

src/components/common/challenge/dashboard/section/GuideSection.tsx
src/components/common/challenge/dashboard/section/NoticeSection.tsx
src/components/common/challenge/dashboard/section/ScoreSection.tsx
src/pages/common/challenge/ChallengeDashboard.tsx

[#635] 챌린지 가이드 섹션 디자인 변경

---

src/Router.tsx
src/components/common/challenge/dashboard/section/ScoreSection.tsx
src/components/common/challenge/ui/layout/ChallengeLayout.tsx
src/components/common/mypage/privacy/form-control/BankDropdown.tsx
src/components/common/mypage/privacy/form-control/GradeDropdown.tsx
src/pages/common/challenge/ChallengeUserInfo.tsx
src/pages/common/mypage/Privacy.tsx

[#638] 챌린지 대시보드 입장 추가입력 페이지 제작

---

src/components/admin/program/ui/editor/ProgramInputContent.tsx

[#644] 프로그램 어드민 입금 예정 날짜 관련 오류 수정

---

src/components/admin/challenge/submit-check-detail/table/table-body/ResultDropdown.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/StatusDropdown.tsx
src/context/CurrentAdminChallengeProvider.tsx
src/pages/admin/challenge/ChallengeOperationAttendances.tsx
src/pages/admin/challenge/ChallengeOperationRegisterMission.tsx
src/schema.ts

어드민 챌린지운영 수정

---

src/components/common/home/new/program/ProgramGridItem.tsx
src/components/common/mypage/application/section/ApplySection.tsx
src/components/common/mypage/ui/card/menu/DeleteMenu.tsx
src/components/common/program/program-detail/apply/content/OverviewContent.tsx
src/components/common/program/program-detail/apply/section/PriceSection.tsx
src/components/common/program/program-detail/toggle/DateToggle.tsx
src/pages/admin/challenge/ChallengeOperationAttendances.tsx
src/pages/common/mypage/Review.tsx

최종 QA 일부 반영

---

src/components/admin/ui/layout/AdminLayout.tsx

[#654] 어드민 웹사이트 점검 페이지 추가

---

src/components/admin/program/program-user/bottom-action/ChallengeActionDropdown.tsx
src/components/admin/program/program-user/table-content/TableBody.tsx
src/components/admin/program/program-user/table-content/TableRow.tsx
src/components/admin/program/ui/editor/ProgramInputContent.tsx
src/components/common/challenge/ui/layout/ChallengeLayout.tsx
src/pages/admin/challenge/ChallengeOperationRegisterMission.tsx
src/pages/admin/program/ProgramEditor.tsx
src/pages/admin/program/ProgramUsers.tsx
src/pages/admin/user/Users.tsx
src/pages/common/challenge/ChallengeDashboard.tsx
src/pages/common/challenge/ChallengeUserInfo.tsx

[#656] 최종 QA 수정사항 반영

---

src/components/common/challenge/dashboard/section/EndDailyMissionSection.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionCalendar.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionCalendarItem.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionIcon.tsx
src/components/common/challenge/my-challenge/mission-calendar/MissionTodayIcon.tsx
src/components/common/challenge/my-challenge/section/MissionCalendarSection.tsx
src/pages/common/challenge/ChallengeDashboard.tsx
src/schema.ts

[#658] 챌린지 종료 화면 오류 수정

---

src/components/common/program/program-detail/apply/content/InputContent.tsx
src/components/common/program/program-detail/apply/content/OverviewContent.tsx
src/components/common/program/program-detail/apply/content/ScheduleContent.tsx
src/components/common/program/program-detail/apply/modal/ApplyModal.tsx
src/components/common/program/program-detail/button/FilledButton.tsx
src/components/common/program/program-detail/button/NotiButton.tsx
src/components/common/program/program-detail/review/ReviewItem.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/components/common/program/program-detail/toggle/DateToggle.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/pages/common/program/ProgramDetail.tsx

> Close #662 
- [Sprint4 최종 배포](https://www.notion.so/letsintern/Sprint4-12eaea1c05b44d39852c5f2155bf1702)

[#662] 최종 QA 수정사항 반영 - 프로그램 상세페이지

---

src/components/admin/challenge/submit-check-detail/table/table-body/ResultDropdown.tsx
src/components/admin/challenge/submit-check-detail/table/table-body/StatusDropdown.tsx
src/components/admin/challenge/submit-check/table/table-body/ChallengeSubmitDetail.tsx
src/components/common/challenge/my-challenge/menu/AbsentMissionSubmitMenu.tsx
src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
src/components/common/mypage/ui/button/LinkButton.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/pages/admin/challenge/ChallengeOperationAttendances.tsx
src/pages/admin/challenge/ChallengeOperationParticipants.tsx
src/pages/common/challenge/ChallengeDashboard.tsx
src/utils/convert.ts

[#661] QA 수정사항 반영

---

src/components/common/program/program-detail/apply/content/OverviewContent.tsx
src/pages/common/program/ProgramDetail.tsx

[#665] 최종 QA 수정사항 (240622) - 프로그램 페이지

---

src/pages/common/challenge/ChallengeDashboard.tsx
src/pages/common/challenge/MyChallengeDashboard.tsx

[#668] 챌린지 종료 관련 로직 수정

---

src/components/common/challenge/my-challenge/menu/AbsentMissionSubmitMenu.tsx
src/components/common/challenge/my-challenge/section/DailyMissionSubmitSection.tsx

[#671] 챌린지 링크 제출 후 수정하기 버튼 뜨도록 수정

---

src/components/common/home/new/banner/Banner.tsx
src/components/common/home/new/banner/TopBanner.tsx
src/components/common/home/new/overview/EmptyListItemContainer.tsx
src/components/common/home/new/overview/ProgramListItemContainer.tsx
src/components/common/home/new/overview/ProgramOverviewListItem.tsx
src/components/common/mypage/application/section/ApplySection.tsx
src/components/common/mypage/application/section/CompleteSection.tsx
src/components/common/mypage/application/section/ParticipateSection.tsx
src/components/common/mypage/review/section/DoneSection.tsx
src/components/common/mypage/review/section/WaitingSection.tsx
src/components/common/mypage/ui/modal/PriceInfoModal.tsx
src/components/common/program/banner/Banner.tsx
src/components/common/program/program-detail/apply/content/OverviewContent.tsx
src/components/common/program/program-detail/apply/content/ScheduleContent.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/components/common/review/section/TenScroeSection.tsx
src/pages/common/program/ProgramDetail.tsx
src/pages/common/program/Programs.tsx
src/pages/common/review/ReviewCreate.tsx

- 홈화면 Overview 디자인 수정
- 프로그램 배너 오류 수정
- 결제 정보 확인 모달 수정
- 홈 isLoading 제거
- 홈 및 프로그램 로딩 쿨타임 적용
- 마이페이지 그리드 레이아웃 통일

[Fix] 최종 QA 반영 (4차)

---

src/components/admin/ui/layout/AdminLayout.tsx
src/components/common/ui/layout/Layout.tsx

[#686] 웹사이트 점검 페이지 제거

---

src/components/admin/ui/layout/AdminLayout.tsx
src/components/common/ui/layout/Layout.tsx

[#688] 점검 페이지 제거된 화면 main에 반영 및 배포

---

src/components/common/mypage/ui/modal/PriceInfoModal.tsx

[#690] 결제 정보 모달 표시 오류 수정

---

public/index.html

https://lets-career.slack.com/archives/C076J24G49X/p1719141464526759?thread_ts=1719074745.115719&cid=C076J24G49X

[Feat] 변경된 naver-site-verification 코드 삽입

---

src/pages/common/auth/FindPassword.tsx

- #701
https://lets-career.slack.com/archives/C0639AAHJG3/p1719240025953839

[Fix] 비밀번호 찾기에 휴대폰 번호 추가

---

public/index.html
src/components/common/home/new/banner/Banner.tsx
src/components/common/home/new/banner/TopBanner.tsx
src/components/common/home/new/overview/EmptyListItemContainer.tsx
src/components/common/home/new/overview/ProgramListItemContainer.tsx
src/components/common/home/new/program/ProgramGridItem.tsx
src/components/common/home/new/program/ProgramSection.tsx
src/components/common/home/new/review/ReviewSection.tsx
src/components/common/home/new/ui/Popup.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/components/common/program/banner/Banner.tsx
src/components/common/program/filter/FilterCheckbox.tsx
src/components/common/program/filter/FilterSideBar.tsx
src/components/common/program/program-detail/apply/content/CautionContent.tsx
src/components/common/program/program-detail/apply/content/InputContent.tsx
src/components/common/program/program-detail/apply/content/OverviewContent.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/button/NotiButton.tsx
src/components/common/program/program-detail/tab/tab-bar/TabBar.tsx
src/components/common/program/programs/card/EmptyCardList.tsx
src/components/common/program/programs/card/ProgramCard.tsx
src/components/common/review/section/ConfirmSection.tsx
src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/footer/Icon.tsx
src/components/common/ui/layout/footer/MenuLink.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/nav/SideNavItem.tsx
src/interfaces/Program.interface.ts
src/pages/common/program/ProgramDetail.tsx
src/utils/axios.ts

[#707] GA 클래스 세팅

---

src/components/common/challenge/my-challenge/dropdown/AbsentContentsDropdown.tsx
src/components/common/challenge/my-challenge/dropdown/ContentsDropdown.tsx

[#710] 챌린지 대시보드 콘텐츠 링크 관련 오류 수정

---

src/components/common/challenge/my-challenge/dropdown/AbsentContentsDropdown.tsx
src/components/common/challenge/my-challenge/dropdown/ContentsDropdown.tsx

Reverts Let-s-intern/lets-intern-client#711

Revert "[#710] 챌린지 대시보드 콘텐츠 링크 관련 오류 수정"

---

src/components/admin/program/ui/editor/ProgramInputContent.tsx
src/components/common/program/program-detail/toggle/DateToggle.tsx
src/pages/admin/program/ProgramEditor.tsx

> Close #718
https://lets-career.slack.com/lists/T02U8B2562Z/F079PASPQJF?record_id=Rec079LH06KLM
https://lets-career.slack.com/lists/T02U8B2562Z/F079PASPQJF?record_id=Rec07A26E8TMX

라이브 프로그램 관련 문제 수정

---

src/components/common/program/filter/FilterSideBar.tsx

[#723] 필터 선택 시 GA 잡히도록 수정

---

src/components/common/program/program-detail/apply/content/InputContent.tsx
src/pages/common/program/ProgramDetail.tsx
src/utils/programConst.ts

> Close #722 
- **신청정보**
<br/>
- **결제정보**

[#722] 신청폼 화면에서 닫을 수 있는 버튼 추가 - 모바일

---

src/components/common/home/new/banner/Banner.tsx
src/pages/admin/coupon/Coupons.tsx

[#727] 홈페이지 배너 오류 수정 (main)

---

src/components/common/home/new/banner/Banner.tsx
src/pages/admin/coupon/Coupons.tsx

[#727] 홈페이지 배너 오류 수정 (develop)

---

src/components/common/program/program-detail/review/ReviewItem.tsx

[#735] 비회원 리뷰 이름 마스킹 삭제

---

src/components/common/program/program-detail/review/ReviewItem.tsx
src/pages/admin/challenge/ChallengeOperationPayback.tsx

[#738] 후기 별점 삭제

---

src/components/common/program/programs/card/ProgramCard.tsx

[LC-62]
[LC-62]: https://letscareer-team.atlassian.net/browse/LC-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-62 프로그램 날짜 Format 로직 수정

---

src/pages/admin/challenge/ChallengeContents.tsx
src/pages/admin/challenge/ChallengeMissionManagement.tsx

[LC-63]
[LC-63]: https://letscareer-team.atlassian.net/browse/LC-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-63 어드민에서 최대 10개만 콘텐츠가 보이는 문제 수정

---

src/components/common/home/new/banner/Banner.tsx
src/components/common/home/new/banner/TopBanner.tsx
src/components/common/home/new/overview/ProgramOverviewSection.tsx
src/components/common/home/new/program/ProgramGridItem.tsx
src/components/common/home/new/program/ProgramSection.tsx
src/components/common/home/new/ui/Popup.tsx
src/components/common/ui/layout/footer/Footer.tsx

[LC-64](https://letscareer-team.atlassian.net/browse/LC-64)
[LC-64]: https://letscareer-team.atlassian.net/browse/LC-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-64 홈 콘솔 에러 잡기

---

src/components/admin/user/users/table-content/TableBody.tsx
src/components/admin/user/users/table-content/TableHead.tsx
src/interfaces/User.interface.ts
src/pages/admin/user/Users.tsx

[LC-65](https://letscareer-team.atlassian.net/jira/software/projects/LC/issues/LC-65?jql=project%20%3D%20%22LC%22%20ORDER%20BY%20created%20DESC)
[LC-65]: https://letscareer-team.atlassian.net/browse/LC-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-65 회원DB 페이지에 소통용 이메일 칼럼 추가

---

src/pages/admin/user/Users.tsx

[Feat] 어드민 > 회원목록 DB 테이블에 소통용 이메일 열 추가 (console.log 제거)

---

src/components/common/challenge/ui/layout/ChallengeLayout.tsx
src/context/CurrentChallengeProvider.tsx

- [LC-58]
[LC-58]: https://letscareer-team.atlassian.net/browse/LC-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-58 유저 챌린지 대시보드에서 로그인하지 않았을 때 불필요한 API 호출하지 않도록 수정 및 리다이렉트

---

src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
src/components/common/challenge/my-challenge/section/OtherMissionSection.tsx
src/utils/convert.ts

- [LC-61]
[LC-61]: https://letscareer-team.atlassian.net/browse/LC-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-61 미제출일 경우 무조건 결석으로 뜨도록 수정

---

src/components/admin/program/program-user/table-content/TableHead.tsx
src/components/common/program/program-detail/section/ApplySection.tsx

- [LC-47]
[LC-47]: https://letscareer-team.atlassian.net/browse/LC-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-47 프로그램 신청 시 소통용 이메일 전달

---

.vscode/settings.json
eslint.config.mjs
package-lock.json
package.json
src/components/admin/program/program-user/bottom-action/BottomAction.tsx
src/components/admin/program/program-user/bottom-action/ChallengeActionDropdown.tsx
src/components/admin/program/program-user/bottom-action/GeneralActionDropdown.tsx
src/components/admin/program/program-user/table-content/TableBody.tsx
src/components/admin/program/program-user/table-content/TableHead.tsx
src/components/admin/program/program-user/table-content/TableRow.tsx
src/pages/admin/program/ProgramUsers.tsx
src/schema.ts

- [LC-101]
[LC-101]: https://letscareer-team.atlassian.net/browse/LC-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LC-101] 프로그램 관리 - 사용자 - 환불 여부 수정할 수 있도록 기능 추가 및 eslint react hook 업데이트

---

src/schema.ts

- [LC-101]
[LC-101]: https://letscareer-team.atlassian.net/browse/LC-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LC-101] 라이브 신청자 정보 가져올 때 isRefunded 미리 스키마 만들어놓기

---

src/components/common/home/new/advantage/AdvantageSection.tsx
src/components/common/home/new/pass-review/PassReviewSection.tsx
src/components/common/home/new/program/ProgramGridItem.tsx
src/components/common/home/new/program/ProgramSection.tsx
src/components/common/home/new/ui/Description.tsx
src/components/common/home/new/ui/Heading.tsx

- [LC-85]
[LC-85]: https://letscareer-team.atlassian.net/browse/LC-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LC-85] 홈 UX 수정

---

src/components/common/mypage/application/section/ApplySection.tsx
src/components/common/mypage/application/section/CompleteSection.tsx
src/components/common/mypage/application/section/ParticipateSection.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx

- [LC-87]
[LC-87]: https://letscareer-team.atlassian.net/browse/LC-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-86 마이페이지 모집 중 뱃지 삭제 및 더보기버튼 클릭 시 숨김 처리

---

src/components/common/mypage/privacy/section/BasicInfo.tsx
src/components/common/program/program-detail/apply/section/UserInputSection.tsx

- [LC-89]
[LC-89]: https://letscareer-team.atlassian.net/browse/LC-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-89 가입한 이메일과 동일 체크박스 색상 변경

---

src/components/common/program/program-detail/apply/content/InputContent.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/apply/section/MotiveAnswerSection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/pages/common/program/ProgramDetail.tsx
src/utils/programConst.ts

- [LC-87]
[LC-87]: https://letscareer-team.atlassian.net/browse/LC-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-87 모바일 프로그램 신청 이어서 신청하기

---

src/components/common/program/program-detail/apply/content/InputContent.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/apply/section/MotiveAnswerSection.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/pages/common/program/ProgramDetail.tsx

- [LC-116]
[LC-116]: https://letscareer-team.atlassian.net/browse/LC-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-116 라이브클래스 신청 시 신청동시 및 필독사항 스킵

---

src/components/admin/program/program-user/table-content/TableHead.tsx
src/components/admin/program/program-user/table-content/TableRow.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/components/common/ui/layout/footer/Footer.tsx

- [LC-116]
- [LC-120]
[LC-116]: https://letscareer-team.atlassian.net/browse/LC-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-120]: https://letscareer-team.atlassian.net/browse/LC-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-116, LC-120 프로그램 신청(라이브클래스) 신청동기 제거, 푸터 고객센터 수정

---

src/components/common/program/program-detail/section/ApplySection.tsx

- [LC-114]
[LC-114]: https://letscareer-team.atlassian.net/browse/LC-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] ApplySection sticky 제거

---

src/components/common/home/new/advantage/AdvantageSection.tsx
src/components/common/home/new/pass-review/PassReviewSection.tsx
src/components/common/home/new/program/ProgramSection.tsx

- [LC-129]
[LC-129]: https://letscareer-team.atlassian.net/browse/LC-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-129 홈 UX Writing 수정

---

src/components/common/home/new/advantage/AdvantageSection.tsx
src/components/common/home/new/pass-review/PassReviewSection.tsx
src/components/common/home/new/program/ProgramSection.tsx
src/components/common/program/program-detail/section/ApplySection.tsx

- [LC-129]
[LC-129]: https://letscareer-team.atlassian.net/browse/LC-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-129 메인 머지

---

src/components/admin/ui/pagination/AdminPagination.tsx
src/pages/admin/program/Programs.tsx
src/pages/admin/review/Reviews.tsx
src/pages/admin/review/ReviewsDetail.tsx
src/pages/admin/user/UserMemo.tsx
src/pages/admin/user/Users.tsx

LC-131 어드민 후기 상세조회 페이지네이션 적용 (페이지네이션 구조 변경)

---

package-lock.json
package.json
src/Router.tsx
src/components/common/mypage/application/section/CompleteSection.tsx
src/components/common/mypage/application/section/ParticipateSection.tsx
src/components/common/mypage/review/section/DoneSection.tsx
src/components/common/review/score/YesNoScore.tsx
src/components/common/review/section/StarScoreSection.tsx
src/components/common/review/section/TenScoreSection.tsx
src/context/CurrentAdminChallengeProvider.tsx
src/context/CurrentChallengeProvider.tsx
src/pages/WriteReviewChallenge.tsx
src/pages/WriteReviewLive.tsx
src/pages/common/mypage/Application.tsx
src/pages/common/mypage/Review.tsx
src/pages/common/review/ReviewCreate.tsx
src/schema.test.ts
src/schema.ts

- [LC-97]
[LC-97]: https://letscareer-team.atlassian.net/browse/LC-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-97 링크 리뷰 기능 추가

---

src/components/common/ui/layout/channel/ChannelTalkBtn.tsx

- [[LC-110](https://letscareer-team.atlassian.net/browse/LC-110)]
[LC-110]: https://letscareer-team.atlassian.net/browse/LC-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 채널톡 버튼 알람 배지 표시

---

src/schema.ts

- [LC-146]
- ...
[LC-146]: https://letscareer-team.atlassian.net/browse/LC-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-146 livePriceType 타입 불일치 수정

---

src/components/common/auth/ui/SocialLogin.tsx
src/components/common/home/new/banner/TopBanner.tsx
src/components/common/ui/layout/channel/ChannelTalkBtn.tsx

- [[LC-124](https://letscareer-team.atlassian.net/browse/LC-124)]
[LC-124]: https://letscareer-team.atlassian.net/browse/LC-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-124 [USER] 홈 띠 배너 이벤트 전파 막기

---

src/components/common/home/new/banner/TopBanner.tsx

- [[LC-124](https://letscareer-team.atlassian.net/browse/LC-124)]
[LC-124]: https://letscareer-team.atlassian.net/browse/LC-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-124 [USER] 홈 띠 배너 커서 변경

---

src/Router.tsx
src/components/admin/program/programs/table-content/TableBody.tsx
src/pages/admin/program/ProgramUsers.tsx
src/pages/common/mentor/MentorNotificationAfter.tsx
src/pages/common/mentor/MentorNotificationBefore.tsx
src/schema.ts

- [LC-42]
[LC-42]: https://letscareer-team.atlassian.net/browse/LC-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-42 멘토 전달 사항 페이지 추가

---

src/components/admin/review/reviews/table-content/TableBody.tsx
src/pages/admin/review/Reviews.tsx
src/pages/common/mentor/MentorNotificationAfter.tsx
src/pages/common/mentor/MentorNotificationBefore.tsx

- [LC-150]
- [LC-151]
[LC-150]: https://letscareer-team.atlassian.net/browse/LC-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-151]: https://letscareer-team.atlassian.net/browse/LC-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-150 LC-151 멘토 사전사후안내 페이지 및 링크후기 기능 보완

---

src/components/admin/program/program-user/table-content/TableHead.tsx
src/components/admin/program/program-user/table-content/TableRow.tsx

- [LC-116]
[LC-116]: https://letscareer-team.atlassian.net/browse/LC-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-116 어드민페이지 지원동기란 복구

---

src/components/common/program/program-detail/section/ApplySection.tsx

- [LC-114]
- [LC-160]
[LC-114]: https://letscareer-team.atlassian.net/browse/LC-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-160]: https://letscareer-team.atlassian.net/browse/LC-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-114, LC-160 신청폼 sticky 복원 (max-height 적용)

---

src/App.tsx
src/components/common/home/new/overview/ProgramListItemContainer.tsx
src/components/common/mypage/application/section/ApplySection.tsx
src/components/common/mypage/application/section/CompleteSection.tsx
src/components/common/mypage/application/section/ParticipateSection.tsx
src/components/common/mypage/review/section/DoneSection.tsx
src/components/common/mypage/review/section/WaitingSection.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/components/common/program/programs/card/ProgramCard.tsx

- [LC-90]
- [LC-100]
- [LC-175]
[LC-90]: https://letscareer-team.atlassian.net/browse/LC-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-100]: https://letscareer-team.atlassian.net/browse/LC-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-175]: https://letscareer-team.atlassian.net/browse/LC-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-90 LC-100 LC-175 마이페이지 프로그램 카드 관련 수정 및 gtm용 프로그램 제목 추가

---

src/pages/admin/program/ProgramUsers.tsx
src/schema.ts

- [LC-162]
[LC-162]: https://letscareer-team.atlassian.net/browse/LC-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-162 어드민에서 멘토 전달 URL 비밀번호 잘 복사되도록 수정

---

README.md
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/apply/section/PayInfoSection.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/pages/common/program/SelectPaymentPage.tsx

- [LC-183]
[LC-183]: https://letscareer-team.atlassian.net/browse/LC-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-183 충돌 해결

---

src/Router.tsx

- [LC-169]
[LC-169]: https://letscareer-team.atlassian.net/browse/LC-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Draft] LC-169 이전 머지 중 Router 오류 수정

---

public/icons/Arrow_Left_MD.svg
src/api/application.ts
src/api/paymentSchema.ts
src/components/common/mypage/credit/CreditCancelModal.tsx
src/components/common/mypage/credit/CreditListItem.tsx
src/components/common/program/paymentSuccess/PaymentInfoRow.tsx
src/pages/common/mypage/CreditDetail.tsx

- [LC-170]
[LC-170]: https://letscareer-team.atlassian.net/browse/LC-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-170 결제내역 상세 구현

---

src/api/application.ts
src/api/paymentSchema.ts
src/components/admin/program/ui/editor/ProgramInputContent.tsx
src/components/common/mypage/credit/CreditListItem.tsx
src/components/common/mypage/credit/section/CreditList.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/apply/section/MotiveAnswerSection.tsx
src/components/common/program/program-detail/apply/section/UserInputSection.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/components/common/program/program-detail/toggle/DateToggle.tsx
src/components/common/ui/input/Input.tsx
src/components/common/ui/input/TextArea.tsx
src/data/getPaymentSearchParams.ts
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentFail.tsx
src/pages/common/program/ProgramDetail.tsx

- [LC-167]
- [LC-121]
[LC-167]: https://letscareer-team.atlassian.net/browse/LC-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-121]: https://letscareer-team.atlassian.net/browse/LC-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-167 어드민, 결제 실패 페이지 등 보완

---

src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/pages/common/program/Payment.tsx

- [LC-170]
[LC-170]: https://letscareer-team.atlassian.net/browse/LC-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-170 마이페이지 더보기 버튼 삭제 및 토스 키 수정

---

src/components/common/program/program-detail/section/ApplySection.tsx
src/schema.ts

- [LC-213]
[LC-213]: https://letscareer-team.atlassian.net/browse/LC-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-213 무료 프로그램 사용자정보 미노출 에러 >  schema에 nullable, optional 추가

---

src/components/common/mypage/application/section/ApplySection.tsx
src/components/common/mypage/credit/CreditListItem.tsx
src/components/common/mypage/review/section/WaitingSection.tsx
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentFail.tsx
src/pages/common/program/PaymentResult.tsx

- [LC-121]
- [LC-191]
[LC-121]: https://letscareer-team.atlassian.net/browse/LC-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-191]: https://letscareer-team.atlassian.net/browse/LC-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

토스결제 관련 GTM용 클래스 추가

---

src/components/common/mypage/ui/modal/PriceInfoModal.tsx

- [LC-255]
[LC-255]: https://letscareer-team.atlassian.net/browse/LC-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-255 입금 마감일 없을 시 '-' 보여주도록 수정

---

src/api/paymentSchema.ts
src/components/common/mypage/credit/CreditCancelModal.tsx
src/components/common/program/ProgramCard.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/data/getPaymentSearchParams.ts
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/program/PaymentFail.tsx
src/pages/common/program/PaymentResult.tsx

- [LC-230]
- [LC-232]
- [LC-239]
[LC-230]: https://letscareer-team.atlassian.net/browse/LC-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-232]: https://letscareer-team.atlassian.net/browse/LC-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-239]: https://letscareer-team.atlassian.net/browse/LC-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-230, LC-232, LC-239 결제취소 모달 및 진행방식 수정

---

src/components/common/program/ProgramCard.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/data/getPaymentSearchParams.ts
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/program/PaymentFail.tsx
src/pages/common/program/PaymentResult.tsx
src/pages/common/program/ProgramDetail.tsx

- [LC-230]
- [LC-232]
- [LC-239]
[LC-230]: https://letscareer-team.atlassian.net/browse/LC-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-232]: https://letscareer-team.atlassian.net/browse/LC-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-239]: https://letscareer-team.atlassian.net/browse/LC-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-230, LC-232, LC-239 Merge Sprint5 into develop

---

src/api/paymentSchema.ts
src/components/common/program/ProgramCard.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/data/getPaymentSearchParams.ts
src/pages/common/program/PaymentResult.tsx

- [LC-230]
[LC-230]: https://letscareer-team.atlassian.net/browse/LC-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-230 progressType 빈 값일 때 위젯 에러 수정

---

src/components/common/program/program-detail/apply/content/PayContent.tsx

- [LC-230]
[LC-230]: https://letscareer-team.atlassian.net/browse/LC-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-230 결제섹션에서 라이브클래스 참여방식 노출

---

src/api/user.ts
src/components/admin/user/users/table-content/TableBody.tsx
src/components/admin/user/users/table-content/TableHead.tsx
src/components/common/mypage/privacy/form-control/GradeDropdown.tsx
src/pages/admin/user/UserDetail.tsx
src/pages/admin/user/UserEdit.tsx
src/pages/admin/user/Users.tsx
src/schema.ts

- [LC-187]
[LC-187]: https://letscareer-team.atlassian.net/browse/LC-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-187 회원DB 상세/수정/삭제 구현

---

src/api/application.ts
src/api/paymentSchema.ts
src/components/common/mypage/credit/CreditListItem.tsx
src/components/common/program/ProgramCard.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/apply/section/CouponSection.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/data/getPaymentSearchParams.ts
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentFail.tsx
src/pages/common/program/PaymentResult.tsx

- [LC-260]
- [LC-261]
- [LC-263]
- [LC-266]
- [LC-267]
- [LC-268]
- [LC-269]
- [LC-270]
[LC-260]: https://letscareer-team.atlassian.net/browse/LC-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-261]: https://letscareer-team.atlassian.net/browse/LC-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-263]: https://letscareer-team.atlassian.net/browse/LC-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-266]: https://letscareer-team.atlassian.net/browse/LC-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-267]: https://letscareer-team.atlassian.net/browse/LC-267?atlOrigin=eyJpIjoiNWRkNTljNzYx …

LC-260 외 7 QA 수정

---

src/Router.tsx
src/api/blog.ts
src/pages/admin/BlogPostListPage.tsx
src/schema.ts
src/utils/convert.ts

- [[LC-278](https://letscareer-team.atlassian.net/browse/LC-278)]
[LC-278]: https://letscareer-team.atlassian.net/browse/LC-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-278 ADMIN 블로그 목록 조회 페이지 디자인 반영

---

src/components/admin/blog/BlogPostEditor.tsx
src/components/admin/blog/TextFieldLimit.tsx
src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx
src/pages/admin/BlogPostListPage.tsx

- [[LC-280](https://letscareer-team.atlassian.net/browse/LC-280)]
[LC-280]: https://letscareer-team.atlassian.net/browse/LC-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-280 블로그 생성 시 content 저장

---

src/pages/admin/BlogCreatePage.tsx

- [[LC-280](https://letscareer-team.atlassian.net/browse/LC-280)]
[LC-280]: https://letscareer-team.atlassian.net/browse/LC-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-280 displayDate 설정 및 블로그 발행

---

src/api/blog.ts
src/api/blogSchema.ts
src/components/admin/blog/BlogPostEditor.tsx
src/components/admin/blog/ToolbarPlugin.tsx
src/pages/admin/BlogCreatePage.tsx

- [[LC-315](https://letscareer-team.atlassian.net/browse/LC-315)]
[LC-315]: https://letscareer-team.atlassian.net/browse/LC-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-280 블로그에 isDisplayed 속성 추가

---

public/icons/check-circle-uncheck.svg
public/icons/check-circle.svg
src/Router.tsx
src/api/application.ts
src/components/common/mypage/credit/section/CreditList.tsx
src/components/common/program/paymentSuccess/DescriptionBox.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/pages/common/mypage/CreditDelete.tsx
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentResult.tsx
src/utils/random.ts

- [LC-320]
[LC-320]: https://letscareer-team.atlassian.net/browse/LC-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-320 신청취소 플로우 구현

---

public/icons/check-circle-uncheck.svg
public/icons/check-circle.svg
src/Router.tsx
src/api/application.ts
src/components/common/mypage/credit/section/CreditList.tsx
src/components/common/program/paymentSuccess/DescriptionBox.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/pages/admin/program/ProgramUsers.tsx
src/pages/common/mypage/CreditDelete.tsx
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentResult.tsx
src/schema.ts
src/utils/random.ts

- [LC-320]
[LC-320]: https://letscareer-team.atlassian.net/browse/LC-320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-320 결제취소 플로우 구현

---

src/api/blog.ts
src/api/blogSchema.ts
src/components/admin/blog/BlogTable.tsx
src/components/admin/blog/TagSelector.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-281](https://letscareer-team.atlassian.net/browse/LC-281)]
[LC-281]: https://letscareer-team.atlassian.net/browse/LC-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-281 블로그 수정  페이지 (노출 여부 로직 제외)

---

src/components/admin/blog/BlogTable.tsx
src/components/common/program/pagination/MuiPagination.tsx
src/pages/common/program/Programs.tsx

- [[LC-325](https://letscareer-team.atlassian.net/browse/LC-325)]
[LC-325]: https://letscareer-team.atlassian.net/browse/LC-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-325 ADMIN 블로그 페이지네이션 적용

---

public/icons/Caret_Circle_Right.svg
public/icons/Caret_Circle_Right_Outline.svg
src/components/common/about/section/program/ProgramCard.tsx

- [[LC-352](https://letscareer-team.atlassian.net/browse/LC-352)]
[LC-352]: https://letscareer-team.atlassian.net/browse/LC-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 아이콘 이름 겹치지 않게 수정

---

src/api/paymentSchema.ts
src/components/common/mypage/application/section/ApplySection.tsx
src/components/common/mypage/application/section/CompleteSection.tsx
src/components/common/mypage/application/section/ParticipateSection.tsx
src/components/common/mypage/credit/CreditDateContainer.tsx
src/components/common/program/ProgramCard.tsx
src/components/common/program/program-detail/apply/section/MotiveAnswerSection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/components/common/program/program-detail/toggle/DateToggle.tsx
src/pages/common/mypage/CreditDelete.tsx
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/mypage/MyPage.tsx
src/pages/common/program/PaymentFail.tsx
src/pages/common/program/PaymentResult.tsx
src/utils/random.ts

- [LC-332]
- [LC-333]
- [LC-334]
- [LC-335]
- [LC-343]
- [LC-344]
- [LC-345]
- [LC-348]
- [LC-351]
- [LC-357]
- [LC-358]
- [LC-360]
[LC-332]: https://letscareer-team.atlassian.net/browse/LC-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-333]: https://letscareer-team.atlassian.net/browse/LC-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-334]: https://letscareer-team.atlassian.net/browse/LC-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-335]: https://letscareer-team.atlassian.net/browse/LC-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-343]: …

LC-332 외 다수 Sprint5 2차 QA 반영

---

src/components/common/mypage/application/section/ApplySection.tsx
src/pages/common/mypage/CreditDelete.tsx

- [LC-366]
[LC-366]: https://letscareer-team.atlassian.net/browse/LC-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-366 환불 기준 정가 반영

---

src/components/common/auth/modal/PrivacyPolicyModal.tsx
src/components/common/ui/layout/footer/Footer.tsx
src/pages/common/auth/SignUp.tsx

- [LC-363]
[LC-363]: https://letscareer-team.atlassian.net/browse/LC-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-363 서비스 이용약관, 개인정보 처리방침 링크 변경

---

src/api/paymentSchema.ts
src/pages/common/mypage/CreditDelete.tsx

- [LC-366]
- [LC-367]
[LC-366]: https://letscareer-team.atlassian.net/browse/LC-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-367]: https://letscareer-team.atlassian.net/browse/LC-367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-367 퀵 계좌이체 결제내역 오류 수정 (tossInfo 타입 수정)

---

src/pages/common/mypage/CreditDelete.tsx

- [LC-379]
[LC-379]: https://letscareer-team.atlassian.net/browse/LC-379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-379 환불 요청 시 부분환불 금액 안 뜨는 이슈 수정

---

public/icons/Caret_Down_MD.svg
public/icons/x-close.svg
src/api/blogSchema.ts
src/components/common/blog/BlogCard.tsx
src/components/common/blog/BlogHashtag.tsx
src/pages/common/blog/BlogHashtagListPage.tsx
src/pages/common/blog/BlogListPage.tsx

- [LC-294]
[LC-294]: https://letscareer-team.atlassian.net/browse/LC-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-294 해시태그 기준 글 목록 화면 구현

---

src/components/common/program/program-detail/apply/content/ScheduleContent.tsx
src/pages/common/program/ProgramDetail.tsx

- [LC-372]
[LC-372]: https://letscareer-team.atlassian.net/browse/LC-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-372 인스타 인앱 경고 수정

---

public/icons/Caret_Circle_Right.svg
public/icons/Caret_Circle_Right_Outline.svg
src/components/common/about/section/program/ProgramCard.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/components/common/program/program-detail/apply/content/InputContent.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/program/program-detail/apply/section/UserInputSection.tsx
src/components/common/ui/button/Button.tsx
src/components/ui/input/Input.tsx
src/pages/common/auth/Login.tsx
src/pages/common/mypage/CreditDelete.tsx
src/pages/common/mypage/CreditDetail.tsx

- [LC-398]
[LC-398]: https://letscareer-team.atlassian.net/browse/LC-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-398 Input에서 엔터키 이벡트 막는 코드 제거

---

src/pages/common/program/ProgramDetail.tsx

- [LC-372]
[LC-372]: https://letscareer-team.atlassian.net/browse/LC-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 인스타그램 경고 수정

---

src/pages/common/program/ProgramDetail.tsx

- [LC-403]
[LC-403]: https://letscareer-team.atlassian.net/browse/LC-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-403 인스타 경고 items-start로 수정

---

src/components/common/ui/layout/footer/Footer.tsx

- [[LC-308](https://letscareer-team.atlassian.net/browse/LC-308)]
[LC-308]: https://letscareer-team.atlassian.net/browse/LC-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 링크 및 디자인 수정

---

src/pages/admin/user/UserEdit.tsx

- [LC-187]
[LC-187]: https://letscareer-team.atlassian.net/browse/LC-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 닫기버튼 수정

---

src/pages/admin/user/UserEdit.tsx

- [LC-187]
[LC-187]: https://letscareer-team.atlassian.net/browse/LC-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-187 닫기버튼 수정

---

src/components/common/ui/layout/footer/Footer.tsx

- [[LC-405](https://letscareer-team.atlassian.net/browse/LC-405)]
[LC-405]: https://letscareer-team.atlassian.net/browse/LC-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

서비스 이용약관, 개인정보처리방침 링크 변경

---

src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/footer/MenuLink.tsx
src/components/common/ui/layout/nav/NavBar.tsx

- [[LC-289](https://letscareer-team.atlassian.net/browse/LC-289)]
[LC-289]: https://letscareer-team.atlassian.net/browse/LC-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

블로그 메뉴 숨기기

---

src/api/blog.ts
src/api/file.ts
src/components/admin/blog/TagSelector.tsx
src/components/admin/lexical/EditorApp.tsx
src/pages/admin/BlogEditPage.tsx
src/utils/random.ts

- [[LC-415](https://letscareer-team.atlassian.net/browse/LC-415)]
[LC-415]: https://letscareer-team.atlassian.net/browse/LC-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-415 ADMIN 블로그 글 쓰기 및 수정 통일

---

src/api/blog.ts

기존에 불러온 블로그 날리기
- [[LC-415](https://letscareer-team.atlassian.net/browse/LC-415)]
[LC-415]: https://letscareer-team.atlassian.net/browse/LC-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 블로그 수정 후 invalidateQueries 추가

---

src/AdminRoutes.tsx
src/api/blog.ts
src/api/blogSchema.ts
src/components/admin/blog/BlogRatingTable.tsx
src/components/admin/ui/layout/AdminLayout.tsx
src/pages/admin/BlogRatingListPage.tsx
src/pages/admin/BlogReviewListPage.tsx

- [[LC-286](https://letscareer-team.atlassian.net/browse/LC-286)]
[LC-286]: https://letscareer-team.atlassian.net/browse/LC-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-286 ADMIN 별점,의견 보는 화면 (목록으로만)

---

src/pages/admin/BlogEditPage.tsx

- [LC-416]
[LC-416]: https://letscareer-team.atlassian.net/browse/LC-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 태그 변수명 변경 (동일한 태그끼리 비교하고 있었음)

---

src/components/admin/lexical/plugins/ToolbarPlugin/fontSize.css
src/components/admin/lexical/plugins/ToolbarPlugin/fontSize.tsx
src/components/admin/lexical/ui/Select.css
src/components/admin/lexical/ui/Select.tsx

- [[LC-423](https://letscareer-team.atlassian.net/browse/LC-423)]
[LC-423]: https://letscareer-team.atlassian.net/browse/LC-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Design] lexical css 선택자 수정

---

src/components/common/ui/layout/footer/Footer.tsx
src/utils/valid.ts

- [[LC-422](https://letscareer-team.atlassian.net/browse/LC-422)]
[LC-422]: https://letscareer-team.atlassian.net/browse/LC-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 광고/제휴 문의 메뉴 추가

---

src/components/admin/lexical/plugins/ImagesPlugin/index.tsx
src/components/common/blog/LexicalContent.tsx

- [LC-425]
[LC-425]: https://letscareer-team.atlassian.net/browse/LC-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-425 블로그 글 이미지 업로드 기능 추가

---

package-lock.json
package.json
src/api/blog.ts
src/pages/common/blog/BlogDetailPage.tsx
src/pages/common/blog/BlogListPage.tsx

- [LC-295]
[LC-295]: https://letscareer-team.atlassian.net/browse/LC-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-295 블로그 글 상세 레이아웃 수정 및 CTA 연결

---

src/pages/common/blog/BlogDetailPage.tsx

- [LC-295]
[LC-295]: https://letscareer-team.atlassian.net/browse/LC-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-295 LexicalContent 에서 index props 제거

---

src/components/common/auth/ui/InfoContainer.tsx
src/pages/common/auth/SignUp.tsx
src/utils/axios.ts

- [LC-427]
[LC-427]: https://letscareer-team.atlassian.net/browse/LC-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-427 소셜 회원가입 오류 문제 수정

---

src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx

- [LC-431]
[LC-431]: https://letscareer-team.atlassian.net/browse/LC-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-431 주소 리다이렉트 시 ? 없어지는 문제 수정

---

src/components/admin/blog/BlogPostEditor.tsx
src/components/admin/lexical/Editor.tsx
src/components/admin/lexical/plugins/ToolbarPlugin/fontSize.css

- [[LC-418](https://letscareer-team.atlassian.net/browse/LC-418)]
[LC-418]: https://letscareer-team.atlassian.net/browse/LC-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-418 Lexical 불필요한 기능 제거

---

src/pages/common/blog/BlogDetailPage.tsx

- [LC-293]
[LC-293]: https://letscareer-team.atlassian.net/browse/LC-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-293 CTA 버튼 너비 수정

---

src/api/blog.ts
src/components/common/blog/LexicalContent.tsx
src/pages/common/blog/BlogDetailPage.tsx

- [LC-440]
- [LC-296]
[LC-440]: https://letscareer-team.atlassian.net/browse/LC-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-296]: https://letscareer-team.atlassian.net/browse/LC-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-440  블로그 상세페이지 후기 등록 연결, 글 상세 작업 (1차)

---

src/api/blog.ts
src/api/blogSchema.ts
src/components/admin/lexical/EditorApp.tsx
src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-434](https://letscareer-team.atlassian.net/browse/LC-434)]
[LC-434]: https://letscareer-team.atlassian.net/browse/LC-434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-434 해시태그 추가 시 블로그에도 자동 등록

---

custom.d.ts
renderer/getServerHtml.ts
src/pages/common/blog/BlogDetailPage.tsx
tsconfig.json

LC-306 블로그 글 공유하기 추가

---

custom.d.ts
renderer/getServerHtml.ts
src/pages/common/blog/BlogDetailPage.tsx
tsconfig.json

LC-306 블로그 글 공유 기능 추가

---

tsconfig.json

LC-306 renderer도 tsconfig에 추가

---

src/pages/common/blog/BlogDetailPage.tsx

LC-306 카카오 공유 링크 수정

---

src/components/admin/lexical/plugins/ListMaxIndentLevelPlugin/index.ts
src/components/admin/lexical/themes/PlaygroundEditorTheme.css

- [[LC-445](https://letscareer-team.atlassian.net/browse/LC-445)]
[LC-445]: https://letscareer-team.atlassian.net/browse/LC-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-445 ADMIN Lexical 스타일 수정

---

src/pages/common/blog/BlogDetailPage.tsx

LC-306 카카오톡 공유 컨텐츠 수정

---

src/pages/common/blog/BlogDetailPage.tsx

LC-306 링크 복사 alert 제거

---

src/pages/common/blog/BlogDetailPage.tsx

LC-306 링크 공유 URL 수정

---

src/api/blogSchema.ts
src/components/admin/blog/BlogTable.tsx
src/components/admin/blog/DateTimePicker.tsx
src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-315](https://letscareer-team.atlassian.net/browse/LC-315)]
- [[LC-444](https://letscareer-team.atlassian.net/browse/LC-444)]
[LC-315]: https://letscareer-team.atlassian.net/browse/LC-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-444]: https://letscareer-team.atlassian.net/browse/LC-444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-444 게시 일자 필드 추가

---

src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-315](https://letscareer-team.atlassian.net/browse/LC-315)]
[LC-315]: https://letscareer-team.atlassian.net/browse/LC-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

한 번 발행한 블로그는 게시 일자 수정 X

---

src/components/admin/lexical/nodes/CodeHighlightNode.tsx
src/components/admin/lexical/nodes/CollapsibleContainerNode.tsx
src/components/admin/lexical/nodes/CollapsibleContentNode.tsx
src/components/admin/lexical/nodes/CollapsibleTitleNode.tsx
src/components/common/blog/LexicalContent.tsx
src/index.css

- [LC-440]
[LC-440]: https://letscareer-team.atlassian.net/browse/LC-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-440 블로그 글 디자인 적용

---

src/components/common/blog/BlogCard.tsx
src/components/common/blog/BlogHashtag.tsx
src/pages/common/blog/BlogHashtagListPage.tsx

- [LC-446]
[LC-446]: https://letscareer-team.atlassian.net/browse/LC-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-446 해시태그 검색 레이아웃 수정

---

src/api/blog.ts
src/pages/common/blog/BlogDetailPage.tsx
src/pages/common/blog/BlogHashtagListPage.tsx

- [LC-446]
[LC-446]: https://letscareer-team.atlassian.net/browse/LC-446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-446 블로그 상세페이지 해시태그 연결 활성화, 추천글 필터링

---

src/api/blogSchema.ts
src/components/admin/blog/BlogTable.tsx

- [[LC-315](https://letscareer-team.atlassian.net/browse/LC-315)]
[LC-315]: https://letscareer-team.atlassian.net/browse/LC-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-315 블로그 조회 페이지에서 블로그 노출 시 발행일자 추가

---

src/api/blog.ts
src/api/blogSchema.ts
src/components/admin/blog/BlogRatingTable.tsx
src/components/admin/blog/BlogTable.tsx

- [[LC-453](https://letscareer-team.atlassian.net/browse/LC-453)]
[LC-453]: https://letscareer-team.atlassian.net/browse/LC-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-453 어드민 블로그 후기 오류 수정

---

src/components/common/ui/layout/footer/Footer.tsx

- [[LC-449](https://letscareer-team.atlassian.net/browse/LC-449)]
[LC-449]: https://letscareer-team.atlassian.net/browse/LC-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

푸터에 블로그 메뉴 추가

---

src/components/admin/program/ui/editor/ProgramInputContent.tsx

- [[LC-399](https://letscareer-team.atlassian.net/browse/LC-399)]
[LC-399]: https://letscareer-team.atlassian.net/browse/LC-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 프로그램 개설 시 필독사항 숨김

---

src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-457](https://letscareer-team.atlassian.net/browse/LC-457)]
[LC-457]: https://letscareer-team.atlassian.net/browse/LC-457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 게시 일자 없는 블로그는 게시 일자 필드 표시

---

src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-458](https://letscareer-team.atlassian.net/browse/LC-458)]
[LC-458]: https://letscareer-team.atlassian.net/browse/LC-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-458 게시일자 과거도 선택 가능

---

src/components/admin/blog/TagSelector.tsx
src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-456](https://letscareer-team.atlassian.net/browse/LC-456)]
[LC-456]: https://letscareer-team.atlassian.net/browse/LC-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] keydown 대신 form 이벤트 사용

---

src/index.css

- [LC-455]
[LC-455]: https://letscareer-team.atlassian.net/browse/LC-455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-455 이미지 캡션 가운데 정렬

---

src/components/common/blog/LexicalContent.tsx
src/index.css

- [LC-424]
[LC-424]: https://letscareer-team.atlassian.net/browse/LC-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-424 토글 디자인 변경 및 유튜브 추가

---

src/pages/common/blog/BlogDetailSSRPage.tsx
src/pages/common/blog/BlogListPage.tsx

- [[LC-428](https://letscareer-team.atlassian.net/browse/LC-428)]
[LC-428]: https://letscareer-team.atlassian.net/browse/LC-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-428 GA 심기

---

src/pages/common/blog/BlogDetailSSRPage.tsx

- [LC-485]
[LC-485]: https://letscareer-team.atlassian.net/browse/LC-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-485 후기 알럿 문구 수정

---

src/components/admin/program/ui/editor/ProgramInputContent.tsx

- [[LC-399](https://letscareer-team.atlassian.net/browse/LC-399)]
[LC-399]: https://letscareer-team.atlassian.net/browse/LC-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

프로그램 생성/수정 시 필독사항 숨김

---

src/components/admin/blog/DateTimePicker.tsx
src/components/admin/blog/TextFieldLimit.tsx
src/components/admin/lexical/Editor.tsx
src/components/admin/lexical/nodes/ImageComponent.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-499](https://letscareer-team.atlassian.net/browse/LC-499)]
[LC-499]: https://letscareer-team.atlassian.net/browse/LC-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-499 Lexical AutoFocus 삭제

---

src/api/blog.ts
src/components/admin/blog/Tag.tsx
src/components/admin/blog/TagSelector.tsx
src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-498](https://letscareer-team.atlassian.net/browse/LC-498)]
[LC-498]: https://letscareer-team.atlassian.net/browse/LC-498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 태그 삭제 기능 추가

---

pages/(catch_all)/+Page.tsx
pages/blog/@id/+onRenderClient.tsx
pages/blog/@id/+onRenderHtml.tsx
src/App.tsx
src/Provider.tsx
src/components/admin/lexical/nodes/ImageNode.css
src/components/admin/lexical/nodes/ImageNode.tsx
src/components/admin/lexical/plugins/ImagesPlugin/index.tsx
src/components/common/blog/LexicalContent.tsx
src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/lib/image.ts
src/pages/common/blog/BlogDetailSSRPage.tsx
src/pages/common/review/ReviewCreate.tsx

- [LC-504]
[LC-504]: https://letscareer-team.atlassian.net/browse/LC-504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-504 SSR 보완, hydrate 잘 되도록 수정, 이미지 압축하여 업로드 등

---

src/components/common/ui/layout/nav/NavBar.tsx

- [LC-510]
[LC-510]: https://letscareer-team.atlassian.net/browse/LC-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-510 블로그 내비게이션 공개

---

src/pages/common/review/ReviewCreate.tsx

- [LC-505]
[LC-505]: https://letscareer-team.atlassian.net/browse/LC-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-505 마이페이지 후기 패딩값 추가

---

src/pages/common/review/ReviewCreate.tsx

- [LC-505]
[LC-505]: https://letscareer-team.atlassian.net/browse/LC-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-505 마이페이지 후기 패딩 추가

---

src/components/common/ui/layout/footer/Footer.tsx

- [LC-510]
[LC-510]: https://letscareer-team.atlassian.net/browse/LC-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-510 푸터에 블로그 추가

---

src/pages/common/blog/BlogHashtagListPage.tsx

- [[LC-508](https://letscareer-team.atlassian.net/browse/LC-508)]
[LC-508]: https://letscareer-team.atlassian.net/browse/LC-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GA] 해시태그 클래스명 추가

---

src/components/common/blog/BlogCategoryTag.tsx
src/pages/common/blog/BlogListPage.tsx

- [[LC-511](https://letscareer-team.atlassian.net/browse/LC-511)]
[LC-511]: https://letscareer-team.atlassian.net/browse/LC-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GA] 블로그 카테고리 태그 수정

---

src/pages/common/auth/FindPassword.tsx

- [LC-527]
[LC-527]: https://letscareer-team.atlassian.net/browse/LC-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-527 비밀번호 찾기 휴대폰번호 자동 하이픈

---

src/api/program.ts
src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx
src/pages/common/blog/BlogDetailSSRPage.tsx
src/schema.ts

- [[LC-513](https://letscareer-team.atlassian.net/browse/LC-513)]
[LC-513]: https://letscareer-team.atlassian.net/browse/LC-513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 조건문에 따라 CTA 링크 생성

---

src/components/common/about/section/ReviewSection.tsx
src/utils/convert.ts
src/utils/formatDateString.ts

- [[LC-530](https://letscareer-team.atlassian.net/browse/LC-530)]
[LC-530]: https://letscareer-team.atlassian.net/browse/LC-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-530 스크롤이 없으면 가운데 정렬

---

src/components/common/about/section/ReviewSection.tsx

- [[LC-530](https://letscareer-team.atlassian.net/browse/LC-530)]
[LC-530]: https://letscareer-team.atlassian.net/browse/LC-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

onResize 처음에 한 번 실행

---

src/components/common/home/new/banner/Banner.tsx
src/components/common/home/new/banner/BannerPlay.tsx

- [[LC-531](https://letscareer-team.atlassian.net/browse/LC-531)]
[LC-531]: https://letscareer-team.atlassian.net/browse/LC-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 모바일 배너 클릭 로직 수정, 내외부 링크 판단

---

src/components/common/blog/LexicalContent.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-533](https://letscareer-team.atlassian.net/browse/LC-533)]
[LC-533]: https://letscareer-team.atlassian.net/browse/LC-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 빈 문단에 <br/> 추가

---

src/components/common/auth/ui/InfoContainer.tsx
src/pages/common/auth/SignUp.tsx

- [[LC-407](https://letscareer-team.atlassian.net/browse/LC-407)]
[LC-407]: https://letscareer-team.atlassian.net/browse/LC-407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

유입경로 필드를 회원가입에서 받기

---

src/components/common/blog/LexicalContent.tsx

- [LC-534]
[LC-534]: https://letscareer-team.atlassian.net/browse/LC-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-534 블로그 이미지-캡션 정렬 얼라인

---

renderer/getServerHtml.ts
src/pages/common/blog/BlogDetailSSRPage.tsx

- [LC-507]
[LC-507]: https://letscareer-team.atlassian.net/browse/LC-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-507 카카오 JS 관련 키 환경변수에서 제거(바로 할당)

---

renderer/getServerHtml.ts
src/pages/common/blog/BlogDetailSSRPage.tsx

- [LC-507]
[LC-507]: https://letscareer-team.atlassian.net/browse/LC-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-507 카카오 공유하기 관련 env 키 제거 

---

src/components/common/blog/LexicalContent.tsx

- [LC-534]
[LC-534]: https://letscareer-team.atlassian.net/browse/LC-534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-534 이미지-캡션 가운데 정렬

---

src/api/user.ts
src/pages/common/auth/FindPassword.tsx

- [[LC-526](https://letscareer-team.atlassian.net/browse/LC-526)]
[LC-526]: https://letscareer-team.atlassian.net/browse/LC-526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-526 소셜 로그인 비밀번호 찾기 메시지 추가

---

vercel.json

LC-537 정적 파일들 브라우저 캐싱 되도록 수정

---

src/pages/admin/BlogCreatePage.tsx
src/pages/admin/BlogEditPage.tsx

- [[LC-542](https://letscareer-team.atlassian.net/browse/LC-542)]
[LC-542]: https://letscareer-team.atlassian.net/browse/LC-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] CTA 링크 설명 추가

---

src/api/program.ts
src/components/common/program/programs/card/ProgramCard.tsx
src/pages/common/program/Programs.tsx
src/schema.ts

- [[LC-544](https://letscareer-team.atlassian.net/browse/LC-544)]
[LC-544]: https://letscareer-team.atlassian.net/browse/LC-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-544 프로그램 코드 정리

---

src/pages/common/program/Programs.tsx

에러 메시지 조건 추가

---

src/components/common/program/program-detail/apply/section/UserInputSection.tsx
src/components/common/ui/layout/channel/ChannelTalkBtn.tsx
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentFail.tsx
src/pages/common/program/PaymentResult.tsx
src/pages/common/review/ReviewCreate.tsx

- [[LC-543](https://letscareer-team.atlassian.net/browse/LC-543)]
[LC-543]: https://letscareer-team.atlassian.net/browse/LC-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-543 후기 작성 NaN 에러 해결

---

src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/data/getPaymentSearchParams.ts
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentFail.tsx
src/pages/common/program/PaymentResult.tsx
src/store/useProgramStore.ts

LC-546 결제 관련 정보 params > zustand로 변경

---

src/components/common/challenge/ui/layout/ChallengeLayout.tsx

- [LC-547]
[LC-547]: https://letscareer-team.atlassian.net/browse/LC-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-547 챌린지 대시보드 access 체크하여 redirect 시키는 부분 임시로 기능 끄기

---

src/components/common/mypage/ui/card/root/ApplicationCard.tsx
src/pages/common/program/Programs.tsx

- [[LC-550](https://letscareer-team.atlassian.net/browse/LC-550)]
[LC-550]: https://letscareer-team.atlassian.net/browse/LC-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 페이지네이션 설정

---

src/components/common/program/program-detail/section/ApplySection.tsx

LC-546 상페 진입 시 프로그램 전역변수 초기화

---

src/components/common/program/program-detail/section/MobileApplySection.tsx

LC-546 프로그램 상세 페이지 들어왔을 시 전역변수 초기화(모바일)

---

src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentResult.tsx
src/store/useProgramStore.ts

LC-546 결제 완료 후 뒤로가기/새로고침 이슈 확인

---

src/pages/common/program/PaymentFail.tsx

LC-546 PaymentFail 에 타입 이슈 수정

---

src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/data/getPaymentSearchParams.ts
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentFail.tsx
src/pages/common/program/PaymentResult.tsx
src/store/useProgramStore.ts

LC-546 사파리 이슈 대응 : 결제 정보 전역변수화

---

tailwind.config.js

- [LC-541]
[LC-541]: https://letscareer-team.atlassian.net/browse/LC-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-541 수료증 작업 세부 수정

---

src/Router.tsx
src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/pages/common/report/ReportPage.tsx

- [[LC-578](https://letscareer-team.atlassian.net/browse/LC-578)]
[LC-578]: https://letscareer-team.atlassian.net/browse/LC-578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-578 Footer/NavBar 서류 진단 메뉴 추가

---

src/Router.tsx
src/pages/common/report/ReportApplyPage.tsx

- [[LC-556](https://letscareer-team.atlassian.net/browse/LC-556)]
[LC-556]: https://letscareer-team.atlassian.net/browse/LC-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-556 서류 진단서 신청하기 라우터 추가

---

src/components/common/challenge/dashboard/section/ScoreSection.tsx

- [LC-541]
[LC-541]: https://letscareer-team.atlassian.net/browse/LC-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-541 수료증 관련 ReactToPrint 분리

---

src/components/common/challenge/dashboard/section/ScoreSection.tsx
src/pages/common/challenge/ChallengeDashboard.tsx

- [LC-541]
[LC-541]: https://letscareer-team.atlassian.net/browse/LC-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-541 수료증 관련 이슈 수정

---

src/components/common/home/new/ui/Popup.tsx

- [[LC-582](https://letscareer-team.atlassian.net/browse/LC-582)]
[LC-582]: https://letscareer-team.atlassian.net/browse/LC-582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 팝업 크기 키우기

---

src/components/common/home/new/ui/Popup.tsx

[Style] 팝업 사이즈 줄임

---

src/components/common/home/new/ui/Popup.tsx
src/context/CurrentChallengeProvider.tsx

- [LC-123]
- ...
[LC-123]: https://letscareer-team.atlassian.net/browse/LC-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 팝업 사이즈 조절

---

src/pages/common/challenge/MyChallengeDashboard.tsx

- [LC-583]
[LC-583]: https://letscareer-team.atlassian.net/browse/LC-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-583 대시보드 이슈 수정

---

src/components/common/report/ControlLabel.tsx
src/components/common/report/Tooltip.tsx
src/components/common/report/date-pickers-toolbar.scss
src/pages/common/report/ReportApplyPage.tsx

- [[LC-556](https://letscareer-team.atlassian.net/browse/LC-556)]
[LC-556]: https://letscareer-team.atlassian.net/browse/LC-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-556 서류진단 신청페이지 - 반응형 디자인 구현

---

src/Router.tsx
src/components/common/program/program-detail/apply/content/PayContent.tsx
src/components/common/report/DateTimePicker.tsx
src/components/common/report/FilledInput.tsx
src/components/common/report/Heading1.tsx
src/components/common/report/Heading3.tsx
src/components/common/report/Label.tsx
src/components/common/ui/BottomSheeet.tsx
src/components/common/ui/layout/channel/ChannelTalkBtn.tsx
src/components/common/ui/layout/nav/NavItem.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentPage.tsx

- [[LC-557](https://letscareer-team.atlassian.net/browse/LC-557)]
[LC-557]: https://letscareer-team.atlassian.net/browse/LC-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-557 서류 진단 결제 페이지 추가

---

src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionDetailMenu.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionItem.tsx
src/components/common/challenge/my-challenge/section/OtherMissionSection.tsx

- [LC-583]
[LC-583]: https://letscareer-team.atlassian.net/browse/LC-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-583 챌린지 대시보드 이슈 수정

---

src/components/common/challenge/my-challenge/mission/AbsentMissionItem.tsx
src/components/common/challenge/my-challenge/mission/DoneMissionItem.tsx
src/components/common/challenge/my-challenge/section/OtherMissionSection.tsx
src/pages/common/challenge/MyChallengeDashboard.tsx

- [LC-583]
[LC-583]: https://letscareer-team.atlassian.net/browse/LC-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LC-583] 새로고침 이슈 수정

---

src/pages/common/report/ReportApplyPage.tsx

- [[LC-586](https://letscareer-team.atlassian.net/browse/LC-586)]
[LC-586]: https://letscareer-team.atlassian.net/browse/LC-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 서류진단 결제 모듈 추가

---

src/AdminRoutes.tsx
src/components/admin/ui/layout/AdminLayout.tsx
src/pages/admin/report/ReportApplicationsPage.tsx

- [LC-567]
[LC-567]: https://letscareer-team.atlassian.net/browse/LC-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-567 어드민 리포트 관련 라우팅 추가

---

src/AdminRoutes.tsx
src/api/blog.ts
src/api/blogSchema.ts
src/api/report.ts
src/pages/admin/report/AdminReportPage.tsx
src/schema.ts

- [LC-552]
[LC-552]: https://letscareer-team.atlassian.net/browse/LC-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-552 API 모킹

---

src/Router.tsx
src/components/common/report/Card.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentFail.tsx
src/pages/common/report/ReportPaymentPage.tsx
src/pages/common/report/ReportPaymentResult.tsx

- [[LC-558](https://letscareer-team.atlassian.net/browse/LC-558)]
- [[LC-559](https://letscareer-team.atlassian.net/browse/LC-559)]
[LC-558]: https://letscareer-team.atlassian.net/browse/LC-558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-559]: https://letscareer-team.atlassian.net/browse/LC-559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

서류진단 결제 완료/실패 페이지 추가

---

public/icons/file-upload.svg
src/api/file.ts
src/api/report.ts
src/components/admin/report/DragDropModule.tsx
src/pages/admin/report/AdminReportPage.tsx
src/pages/admin/report/ReportApplicationsPage.tsx

- [LC-567]
[LC-567]: https://letscareer-team.atlassian.net/browse/LC-567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-567 어드민 서류 진단 참여자 페이지 구현

---

src/Router.tsx
src/api/paymentSchema.ts
src/components/common/mypage/credit/CreditListItem.tsx
src/pages/common/mypage/ReportCreditDelete.tsx
src/pages/common/mypage/ReportCreditDetail.tsx

- [LC-561]
[LC-561]: https://letscareer-team.atlassian.net/browse/LC-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-561 서류진단 결제내역 목록 분기처리

---

custom.d.ts
src/pages/common/program/PaymentResult.tsx

- [LC-538]
[LC-538]: https://letscareer-team.atlassian.net/browse/LC-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-538 결제 성공 시 GTM 이벤트 보내기

---

src/pages/common/program/PaymentResult.tsx

- [LC-538]
[LC-538]: https://letscareer-team.atlassian.net/browse/LC-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-538 GTM payment_success 에 추가 정보 전달

---

src/hooks/useReportPayment.tsx
src/hooks/useReportProgramInfo.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentPage.tsx

- [[LC-591](https://letscareer-team.atlassian.net/browse/LC-591)]
[LC-591]: https://letscareer-team.atlassian.net/browse/LC-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-591 모바일 결제 페이지: 참여자 정보 불러오기

---

src/api/report.ts
src/pages/admin/report/ReportApplicationsPage.tsx
src/pages/admin/report/ReportFeedbackApplicationsPage.tsx
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/mypage/ReportCreditDetail.tsx

- [LC-562]
[LC-562]: https://letscareer-team.atlassian.net/browse/LC-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-562 서류진단 결제 상세 페이지 구현 (API 수정 후 확인 필요)

---

src/api/report.ts
src/pages/common/mypage/ReportCreditDelete.tsx
src/pages/common/mypage/ReportCreditDetail.tsx

- [LC-563]
[LC-563]: https://letscareer-team.atlassian.net/browse/LC-563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-563 서류 진단 결제 취소 페이지 구현 (확인 필요)

---

src/Router.tsx
src/hooks/useReportPayment.tsx
src/hooks/useReportProgramInfo.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentPage.tsx
src/pages/common/report/ReportPaymentResult.tsx
src/pages/common/report/ReportTossPage.tsx
src/store/useReportApplicationStore.ts

- [[LC-576](https://letscareer-team.atlassian.net/browse/LC-576)]
[LC-576]: https://letscareer-team.atlassian.net/browse/LC-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-576 서류 진단 신청서 생성하기

---

src/api/paymentSchema.ts
src/hooks/useReportPayment.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentFail.tsx
src/pages/common/report/ReportPaymentPage.tsx
src/pages/common/report/ReportPaymentResult.tsx
src/store/useReportApplicationStore.ts

- [[LC-576](https://letscareer-team.atlassian.net/browse/LC-576)]
[LC-576]: https://letscareer-team.atlassian.net/browse/LC-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-576 결제 완료/실패 페이지 API 연결

---

src/api/report.ts
src/pages/admin/report/ReportFeedbackApplicationsPage.tsx

LC-570 1:1첨삭 일정 확정 수정

---

src/components/admin/ui/button/ActionButton.tsx
src/components/common/mypage/credit/CreditListItem.tsx
src/pages/admin/report/AdminReportListPage.tsx
src/pages/common/mypage/ReportCreditDelete.tsx
src/pages/common/mypage/ReportCreditDetail.tsx

LC-561 결제목록/상세 관련 수정

---

src/components/admin/coupon/CouponEditor.tsx
src/components/ui/input/Input.tsx
src/hooks/useReportPayment.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentFail.tsx
src/pages/common/report/ReportPaymentResult.tsx
src/utils/convert.ts

- [[LC-594](https://letscareer-team.atlassian.net/browse/LC-594)]
[LC-594]: https://letscareer-team.atlassian.net/browse/LC-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

USER/ADMIN 서류진단 쿠폰 추가

---

src/pages/common/report/ReportPaymentResult.tsx

- [[LC-610](https://letscareer-team.atlassian.net/browse/LC-610)]
[LC-610]: https://letscareer-team.atlassian.net/browse/LC-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-610 서류진단 결제 승인 후 GA 이벤트 보내기

---

src/components/common/report/ReportApplyBottomSheet.tsx
src/pages/common/report/ReportManagementPage.tsx

- [[LC-609](https://letscareer-team.atlassian.net/browse/LC-609)]
[LC-609]: https://letscareer-team.atlassian.net/browse/LC-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[2차] LC-610 서류 진단 GA 클래스 추가

---

src/api/coupon.ts
src/hooks/useReportPayment.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentFail.tsx
src/pages/common/report/ReportPaymentResult.tsx
src/pages/common/report/ReportTossPage.tsx

- [[LC-632](https://letscareer-team.atlassian.net/browse/LC-632)]
[LC-632]: https://letscareer-team.atlassian.net/browse/LC-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-632 서류 진단 쿠폰 할인 안먹는 문제 수정

---

src/components/common/ui/layout/channel/ChannelTalkBtn.tsx

- [[LC-626](https://letscareer-team.atlassian.net/browse/LC-626)]
[LC-626]: https://letscareer-team.atlassian.net/browse/LC-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 서류 진단 채널톡 버튼 위치 조정

---

src/components/common/report/DateTimePicker.tsx
src/pages/common/report/ReportApplyPage.tsx
src/store/useReportApplicationStore.ts

- [[LC-645](https://letscareer-team.atlassian.net/browse/LC-645)]

LC-645 1:1 피드백 서비스 희망날짜 선택시 구매한 항목별로 선택가능 기간 조정필요

---

src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentFail.tsx
src/pages/common/report/ReportPaymentPage.tsx
src/pages/common/report/ReportPaymentResult.tsx

- [[LC-648](https://letscareer-team.atlassian.net/browse/LC-648)]
- [[LC-652](https://letscareer-team.atlassian.net/browse/LC-652)]

LC-648 QA 이슈 수정 (뒤로가기, 파일 업로드)

---

src/pages/common/report/ReportApplyPage.tsx
src/store/useReportApplicationStore.ts

- [[LC-652](https://letscareer-team.atlassian.net/browse/LC-652)]

파일은 별도로 유효성 검사

---

src/api/report.ts
src/components/common/mypage/credit/CreditListItem.tsx
src/pages/common/mypage/ReportCreditDelete.tsx
src/pages/common/mypage/ReportCreditDetail.tsx

- [[LC-665](https://letscareer-team.atlassian.net/browse/LC-665)]
- [[LC-663](https://letscareer-team.atlassian.net/browse/LC-663)]
[LC-665]: https://letscareer-team.atlassian.net/browse/LC-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-663]: https://letscareer-team.atlassian.net/browse/LC-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-665 USER 결제내역 zod 에러 수정

---

src/pages/common/report/ReportApplyPage.tsx

- [[LC-653](https://letscareer-team.atlassian.net/browse/LC-653)]
[LC-653]: https://letscareer-team.atlassian.net/browse/LC-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-653 USER 로그인 안 해도 결제 페이지까지 넘어가짐

---

src/hooks/useReportPayment.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentPage.tsx

- [[LC-660](https://letscareer-team.atlassian.net/browse/LC-660)]
- [[LC-661](https://letscareer-team.atlassian.net/browse/LC-661)]
[LC-660]: https://letscareer-team.atlassian.net/browse/LC-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-661]: https://letscareer-team.atlassian.net/browse/LC-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-660 QA 쿠폰 이슈 수정

---

src/pages/common/program/PaymentResult.tsx
src/pages/common/report/ReportPaymentResult.tsx

- [[LC-667](https://letscareer-team.atlassian.net/browse/LC-667)]
[LC-667]: https://letscareer-team.atlassian.net/browse/LC-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-667 USER 서류진단 무료일 때 로직 추가

---

src/components/common/home/new/review/ReviewSection.tsx
src/components/common/ui/layout/nav/NavBar.tsx
src/index.css

- [[LC-670](https://letscareer-team.atlassian.net/browse/LC-670)]
[LC-670]: https://letscareer-team.atlassian.net/browse/LC-670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-670 [USER] Header, Footer내 서비스명 및 썸네일 변경

---

src/api/report.ts
src/hooks/useReportPayment.ts
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentFail.tsx
src/pages/common/report/ReportPaymentPage.tsx
src/pages/common/report/ReportPaymentResult.tsx

- [[LC-669](https://letscareer-team.atlassian.net/browse/LC-669)]
[LC-669]: https://letscareer-team.atlassian.net/browse/LC-669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-669 서류진단 결제정보 폼 수정

---

src/components/common/report/DateTimePicker.tsx
src/hooks/useMinDate.ts
src/pages/common/report/ReportApplyPage.tsx
src/store/useReportApplicationStore.ts

- [[LC-674](https://letscareer-team.atlassian.net/browse/LC-674)]
- [[LC-677](https://letscareer-team.atlassian.net/browse/LC-677)]
[LC-674]: https://letscareer-team.atlassian.net/browse/LC-674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-677]: https://letscareer-team.atlassian.net/browse/LC-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-674 USER 1:1 피드백 희망일자: 선택할 수 있는 날짜 계산

---

src/api/user.ts
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentPage.tsx
src/pages/common/report/ReportTossPage.tsx
src/store/useReportApplicationStore.ts

- [[LC-681]](https://letscareer-team.atlassian.net/browse/LC-681)
[LC-681]: https://letscareer-team.atlassian.net/browse/LC-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-681 USER 서류 진단 결제 시 정보 수신용 이메일 PATCH user 요청 보내기

---

src/pages/common/report/ReportPaymentResult.tsx

- [[LC-649](https://letscareer-team.atlassian.net/browse/LC-649)]
[LC-649]: https://letscareer-team.atlassian.net/browse/LC-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-649 영수증 보기 후 이전 버튼 누르면 404 페이지로 이동

---

src/pages/common/challenge/ChallengeUserInfo.tsx
src/pages/common/mypage/Privacy.tsx

- [[LC-686](https://letscareer-team.atlassian.net/browse/LC-686)]
[LC-686]: https://letscareer-team.atlassian.net/browse/LC-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-686 고객 계좌번호 입력 삭제

---

src/pages/common/challenge/ChallengeUserInfo.tsx

- [[LC-692](https://letscareer-team.atlassian.net/browse/LC-692)]
[LC-692]: https://letscareer-team.atlassian.net/browse/LC-692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 유효성 검사 조건 변경

---

src/components/common/report/ReportApplyBottomSheet.tsx
src/pages/common/report/ReportApplyPage.tsx

- [[LC-690](https://letscareer-team.atlassian.net/browse/LC-690)]
[LC-690]: https://letscareer-team.atlassian.net/browse/LC-690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-690 USER 자소서 채용공고 입력란 숨기기

---

src/Router.tsx
src/pages/maintenance/Maintenance.tsx

- [[LC-689](https://letscareer-team.atlassian.net/browse/LC-689)]
[LC-689]: https://letscareer-team.atlassian.net/browse/LC-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 서버 점검 페이지 수정

---

src/components/common/auth/ui/SocialLogin.tsx
src/components/common/challenge/ui/layout/ChallengeLayout.tsx
src/pages/common/challenge/ChallengeUserInfo.tsx

- [[LC-604](https://letscareer-team.atlassian.net/browse/LC-604)]
- [[LC-686](https://letscareer-team.atlassian.net/browse/LC-686)]
[LC-604]: https://letscareer-team.atlassian.net/browse/LC-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-686]: https://letscareer-team.atlassian.net/browse/LC-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

고객 계좌 정보 속성 삭제

---

src/Router.tsx

서버 점검 화면 표시

---

src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentResult.tsx
src/pages/common/report/ReportTossPage.tsx

- [[LC-702](https://letscareer-team.atlassian.net/browse/LC-702)]
- [[LC-693](https://letscareer-team.atlassian.net/browse/LC-693)]
[LC-702]: https://letscareer-team.atlassian.net/browse/LC-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-693]: https://letscareer-team.atlassian.net/browse/LC-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-702 dataLayer, 할인률 수정

---

src/lib/refund.ts
src/pages/common/mypage/ReportCreditDelete.tsx
src/pages/common/mypage/ReportCreditDetail.tsx

- [[LC-696](https://letscareer-team.atlassian.net/browse/LC-696)]
- [[LC-697](https://letscareer-team.atlassian.net/browse/LC-697)]
- [[LC-698](https://letscareer-team.atlassian.net/browse/LC-698)]
[LC-696]: https://letscareer-team.atlassian.net/browse/LC-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-697]: https://letscareer-team.atlassian.net/browse/LC-697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-698]: https://letscareer-team.atlassian.net/browse/LC-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-696 결제내역, 결제취소, 환불내역 금액 계산 로직 수정

---

src/components/common/ui/layout/nav/NavBar.tsx
src/components/common/ui/layout/nav/NavItem.tsx

- [[LC-688](https://letscareer-team.atlassian.net/browse/LC-688)]
[LC-688]: https://letscareer-team.atlassian.net/browse/LC-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lc-688 네비게이션바 수정

---

src/components/common/challenge/ui/layout/ChallengeLayout.tsx

https://lets-career.slack.com/archives/C062632NUGN/p1726359215787899?thread_ts=1726300575.352779&cid=C062632NUGN

[임시] /challenge/{params.programId}/user/info 리다이렉트 막기

---

src/schema.ts

- [[LC-705](https://letscareer-team.atlassian.net/browse/LC-705)]
[LC-705]: https://letscareer-team.atlassian.net/browse/LC-705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC- 705 Zod 에러 수정: 프로그램 타입에 REPORT 추가

---

src/hooks/useReportPayment.ts
src/pages/common/report/ReportApplyPage.tsx
src/store/useReportApplicationStore.ts

- [[LC-714](https://letscareer-team.atlassian.net/browse/LC-714)]
[LC-714]: https://letscareer-team.atlassian.net/browse/LC-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 쿠폰 정보를 store에 저장

---

src/pages/admin/report/ReportApplicationsPage.tsx

- [LC-711]
- ..
[LC-711]: https://letscareer-team.atlassian.net/browse/LC-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-711 1:1 피드백 신청안한 유저는 참여자목록에서 1:1피드백란 비활성화

---

src/pages/common/report/ReportApplyPage.tsx

- [LC-713]
[LC-713]: https://letscareer-team.atlassian.net/browse/LC-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-713 프리미엄 채용공고 캡처본 지원 형식 안내 수정

---

src/hooks/useMinDate.ts

- [LC-710]
[LC-710]: https://letscareer-team.atlassian.net/browse/LC-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-710 1:1 피드백 일정 선택 가능 일자 1일 씩 추가하는 걸로 수정

---

src/pages/common/report/ReportApplyPage.tsx

- [[LC-716](https://letscareer-team.atlassian.net/browse/LC-716)]
[LC-716]: https://letscareer-team.atlassian.net/browse/LC-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-716 USER 결제하기 넘어갈 때 로딩 표시 및 파일 맥시멈 제한

---

src/api/application.ts

- [LC-706]
[LC-706]: https://letscareer-team.atlassian.net/browse/LC-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

서류 진단 신청 내역은 마이페이지에서 숨기기

---

src/pages/common/report/ReportApplyPage.tsx

- [LC-716]
[LC-716]: https://letscareer-team.atlassian.net/browse/LC-716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-716 파일 맥시멈 설정 및 로딩 중 표시

---

src/pages/common/report/ReportApplyPage.tsx

- [LC-713]
[LC-713]: https://letscareer-team.atlassian.net/browse/LC-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-713 결제 워딩 수정 및 로딩 로직 수정

---

src/components/common/blog/BlogCard.tsx
src/pages/common/blog/BlogHashtagListPage.tsx
src/pages/common/blog/BlogListPage.tsx

- [[LC-638](https://letscareer-team.atlassian.net/browse/LC-638)]
- [[LC-637](https://letscareer-team.atlassian.net/browse/LC-637)]
[LC-638]: https://letscareer-team.atlassian.net/browse/LC-638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-637]: https://letscareer-team.atlassian.net/browse/LC-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-638 블로그 해시태그 검색 유지 & 검색 건수 표시

---

src/components/common/report/ReportContentContainer.tsx
src/components/common/report/ReportIntroSection.tsx

- [[LC-712](https://letscareer-team.atlassian.net/browse/LC-712)]
[LC-712]: https://letscareer-team.atlassian.net/browse/LC-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 상세페이지 너비 조정

---

src/components/common/report/ReportApplyBottomSheet.tsx

- [[LC-712](https://letscareer-team.atlassian.net/browse/LC-712)]
[LC-712]: https://letscareer-team.atlassian.net/browse/LC-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 바텀 시트 너비 조정

---

src/components/common/ui/layout/footer/Footer.tsx
src/components/common/ui/layout/nav/NavBar.tsx

- [LC-712]
[LC-712]: https://letscareer-team.atlassian.net/browse/LC-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

서류 진단 메뉴 표시

---

src/components/common/report/ReportLandingNav.tsx

- [[LC-712](https://letscareer-team.atlassian.net/browse/LC-712)]
[LC-712]: https://letscareer-team.atlassian.net/browse/LC-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

포폴 메뉴 숨김처리 해제

---

src/components/common/blog/LexicalContent.tsx
src/pages/common/report/ReportResumePage.tsx

- [[LC-717](https://letscareer-team.atlassian.net/browse/LC-717)]
[LC-717]: https://letscareer-team.atlassian.net/browse/LC-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] Lexical 취소선 추가

---

pages/report/landing/+Page.tsx
pages/report/landing/+onRenderClient.tsx
pages/report/landing/+onRenderHtml.tsx
pages/report/landing/+route.ts

- [[LC-722](https://letscareer-team.atlassian.net/browse/LC-722)]
[LC-722]: https://letscareer-team.atlassian.net/browse/LC-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 서류진단 랜딩 페이지 onRenderHtml 추가

---

.vscode/settings.json
src/components/common/mypage/credit/ReportCreditRow.tsx
src/components/common/mypage/credit/ReportCreditSubRow.tsx
src/lib/refund.ts
src/pages/common/mypage/ReportCreditDelete.tsx
src/pages/common/mypage/ReportCreditDetail.tsx

- [LC-703]
[LC-703]: https://letscareer-team.atlassian.net/browse/LC-703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-703 결제상세 UI 수정

---

src/pages/common/report/ReportApplyPage.tsx

- [LC-720]
[LC-720]: https://letscareer-team.atlassian.net/browse/LC-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-720 로딩 스피너 적용

---

src/components/common/mypage/credit/ReportCreditSubRow.tsx
src/pages/common/report/ReportPaymentFail.tsx
src/pages/common/report/ReportPaymentResult.tsx

- [LC-703]
[LC-703]: https://letscareer-team.atlassian.net/browse/LC-703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-703 결제완료 페이지 금액 UI 변경

---

.vscode/settings.json
src/components/common/mypage/credit/ReportCreditRow.tsx
src/components/common/mypage/credit/ReportCreditSubRow.tsx
src/lib/refund.ts
src/pages/common/mypage/ReportCreditDelete.tsx
src/pages/common/mypage/ReportCreditDetail.tsx
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPaymentFail.tsx
src/pages/common/report/ReportPaymentResult.tsx

LC-703 결제금액 관련 UI 수정

---

src/pages/common/report/ReportApplyPage.tsx

- [[LC-726](https://letscareer-team.atlassian.net/browse/LC-726)]
[LC-726]: https://letscareer-team.atlassian.net/browse/LC-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 1:1 피드백 할인 가격 노출

---

src/pages/common/report/ReportApplyPage.tsx

- [[LC-726](https://letscareer-team.atlassian.net/browse/LC-726)]
[LC-726]: https://letscareer-team.atlassian.net/browse/LC-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 결제 UI 변경

---

src/pages/common/report/ReportApplyPage.tsx

- [[LC-731](https://letscareer-team.atlassian.net/browse/LC-731)]
[LC-731]: https://letscareer-team.atlassian.net/browse/LC-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] 옵션  가은 한 줄로 표시

---

src/Router.tsx
src/pages/maintenance/Maintenance.tsx

LC-736 서버 점검 표시

---

src/Router.tsx

LC-736 서버 점검 해제

---

src/Router.tsx

LC-736 Maintenance 제거

---

src/api/report.ts

LC-736 zod 에러 수정

---

src/api/report.ts

LC-736 zod 에러 수정 원복

---

src/pages/maintenance/Maintenance.tsx

LC-736 서버 점검 페이지 수정

---

src/Router.tsx

서버 점검 조건 추가

---

src/api/paymentSchema.ts
src/components/common/mypage/credit/section/CreditList.tsx
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/mypage/ReportCreditDetail.tsx

- [[LC-730](https://letscareer-team.atlassian.net/browse/LC-730)]
[LC-730]: https://letscareer-team.atlassian.net/browse/LC-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-730 결제 일자 통일하기

---

src/pages/common/program/Programs.tsx

프로그램 조회 alert 메시지 수정

---

src/components/common/report/ReportLandingNav.tsx
src/lib/Limiter.test.ts
src/lib/Limiter.ts
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx
src/utils/axios.ts

- [LC-646]
- [LC-704]
[LC-646]: https://letscareer-team.atlassian.net/browse/LC-646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-704]: https://letscareer-team.atlassian.net/browse/LC-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-646 LC-704 무한루프 요청 문제 수정, 서류진단 CTA 버튼 수정

---

src/lib/refund.test.ts

- [LC-703]
[LC-703]: https://letscareer-team.atlassian.net/browse/LC-703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-703 refund.test에 isRefunded 반영

---

src/components/common/home/new/banner/TopBanner.tsx
src/components/common/ui/layout/nav/NavBar.tsx

LC-758 상단 띠배너 스크롤 시 고정

---

src/components/common/blog/LexicalContent.tsx
src/pages/common/blog/BlogDetailSSRPage.tsx

- [[LC-442](https://letscareer-team.atlassian.net/browse/LC-442)]
[LC-442]: https://letscareer-team.atlassian.net/browse/LC-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-442 CTA/본문 내 링크가 내부 링크일 시 현재 페이지에서 이동하고 외부일 시 새 창으로 동작하도록 수정

---

src/api/challenge.ts
src/api/paymentSchema.ts
src/components/common/mypage/credit/CardStatus.tsx
src/context/CurrentAdminChallengeProvider.tsx
src/index.css
src/pages/admin/challenge/ChallengeOperationPayback.tsx
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/mypage/ReportCreditDetail.tsx
src/schema.ts

- [LC-760]
[LC-760]: https://letscareer-team.atlassian.net/browse/LC-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-760 챌린지 일괄 페이백 구현

---

src/api/blog.ts
src/components/common/home/new/review/ReviewSection.tsx
src/pages/common/blog/BlogDetailSSRPage.tsx

- [[LC-763](https://letscareer-team.atlassian.net/browse/LC-763)]
[LC-763]: https://letscareer-team.atlassian.net/browse/LC-763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-763 홈화면내 프로그램 참여후기 -> 블로그 게시글 썸네일로 변경

---

src/components/common/home/new/banner/TopBanner.tsx
src/pages/common/home/Home.tsx

- [LC-758]
[LC-758]: https://letscareer-team.atlassian.net/browse/LC-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TEST-LC-758 띠배너 있을 시 상단 여백 추가

---

src/components/common/home/new/banner/TopBanner.tsx
src/pages/common/home/Home.tsx

- [LC-758]
[LC-758]: https://letscareer-team.atlassian.net/browse/LC-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-758 띠배너 있을 시 상단 여백 추가

---

src/App.tsx
src/pages/common/program/ProgramDetail.tsx

- [[LC-778](https://letscareer-team.atlassian.net/browse/LC-778)]

LC-778 프로그램 상세페이지 CTA

---

src/api/paymentSchema.ts
src/pages/admin/challenge/ChallengeOperationPayback.tsx

- [LC-760]
[LC-760]: https://letscareer-team.atlassian.net/browse/LC-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV] LC-760 페이백 리스트 조건 및 환불여부 변경 조건 추가

---

src/pages/admin/challenge/ChallengeOperationPayback.tsx

- [LC-760]
[LC-760]: https://letscareer-team.atlassian.net/browse/LC-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV] LC-760 페이백 버튼 색상 변경

---

src/pages/common/home/Home.tsx

- [LC-758]
[LC-758]: https://letscareer-team.atlassian.net/browse/LC-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-758 상단 띠배너 모바일 여백 추가

---

src/components/common/home/new/review/ReviewSection.tsx

[Style] 불필요한 너비 스타일 제거

---

src/components/common/home/new/review/ReviewSection.tsx

[Style] 너비 auto로 지정

---

src/components/common/home/new/review/ReviewSection.tsx

- [[LC-786](https://letscareer-team.atlassian.net/browse/LC-786)]
[LC-786]: https://letscareer-team.atlassian.net/browse/LC-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] img에 직접 너비, 높이 지정

---

src/components/common/ui/layout/footer/Footer.tsx

- [[LC-789](https://letscareer-team.atlassian.net/browse/LC-789)]
[LC-789]: https://letscareer-team.atlassian.net/browse/LC-789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Footer 주소 변경

---

src/components/common/home/new/overview/ProgramListItemContainer.tsx
src/components/common/home/new/overview/ProgramOverviewListItem.tsx

- [LC-802]
[LC-802]: https://letscareer-team.atlassian.net/browse/LC-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV] LC-802 홈 프로그램 일정에 VOD 반영

---

src/components/common/home/new/overview/ProgramListItemContainer.tsx
src/components/common/home/new/overview/ProgramOverviewListItem.tsx

- [LC-802]
[LC-802]: https://letscareer-team.atlassian.net/browse/LC-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-802 홈 프로그램 일정에 VOD 반영

---

src/components/common/home/new/overview/ProgramListItemContainer.tsx
src/components/common/home/new/overview/ProgramOverviewListItem.tsx

Reverts Let-s-intern/lets-intern-client#1127

Revert "LC-802 홈 프로그램 일정에 VOD 반영"

---

src/components/common/home/new/overview/ProgramListItemContainer.tsx
src/components/common/home/new/overview/ProgramOverviewListItem.tsx

Reverts Let-s-intern/lets-intern-client#1129

Revert "Revert "LC-802 홈 프로그램 일정에 VOD 반영""

---

src/components/common/home/new/overview/ProgramListItemContainer.tsx

- [LC-802]
[LC-802]: https://letscareer-team.atlassian.net/browse/LC-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-802 VOD navigate 수정

---

src/components/common/home/new/overview/ProgramListItemContainer.tsx

- [LC-802]
[LC-802]: https://letscareer-team.atlassian.net/browse/LC-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV] LC-802 VOD navigate 수정

---

src/pages/common/program/ChallengeDetailSSRPage.tsx

- [[LC-742](https://letscareer-team.atlassian.net/browse/LC-806)]
[LC-742]: https://letscareer-team.atlassian.net/browse/LC-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] Json 파싱 에러 발생하면 예전 프로그램 페이지로 이동

---

src/pages/common/program/ChallengeDetailSSRPage.tsx
src/pages/common/program/LiveDetailSSRPage.tsx

- [[LC-806](https://letscareer-team.atlassian.net/browse/LC-806)]
[LC-806]: https://letscareer-team.atlassian.net/browse/LC-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] desc이 <로 시작하면 예전 프로그램 페이지로 이동

---

src/components/common/ui/layout/nav/NavBar.tsx
src/pages/common/program/ProgramDetailLegacy.tsx

- [[LC-807](https://letscareer-team.atlassian.net/browse/LC-807)]
[LC-807]: https://letscareer-team.atlassian.net/browse/LC-807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] dependency 상세히 설정

---

src/pages/common/program/LiveDetailSSRPage.tsx

- [[LC-806](https://letscareer-team.atlassian.net/browse/LC-806)]
[LC-806]: https://letscareer-team.atlassian.net/browse/LC-806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Chore] 불필요한 상태 삭제

---

src/utils/url.ts

- [[LC-814](https://letscareer-team.atlassian.net/browse/LC-814)]
[LC-814]: https://letscareer-team.atlassian.net/browse/LC-814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-814 ADMIN 블로그 제목에 '/' 포함되면 주소 바뀌는 이슈

---

src/components/common/program/program-detail/button/FilledButton.tsx
src/pages/common/program/ChallengeDetailSSRPage.tsx
src/pages/common/program/LiveDetailSSRPage.tsx
src/pages/common/program/ProgramDetailLegacy.tsx

- [[LC-785](https://letscareer-team.atlassian.net/browse/LC-785)]
[LC-785]: https://letscareer-team.atlassian.net/browse/LC-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-785 USER 프로그램 상페 CTA 버튼 개선 (디자인 적용)

---

src/components/common/program/program-detail/button/GradientButton.tsx
src/pages/common/program/ChallengeDetailSSRPage.tsx
src/pages/common/program/LiveDetailSSRPage.tsx
src/schema.ts

- [[LC-785](https://letscareer-team.atlassian.net/browse/LC-785)]
[LC-785]: https://letscareer-team.atlassian.net/browse/LC-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 데스크탑 CTA 추가

---

src/components/common/program/program-detail/button/GradientButton.tsx
src/pages/common/program/ChallengeDetailSSRPage.tsx

- [[LC-785](https://letscareer-team.atlassian.net/browse/LC-785)]
[LC-785]: https://letscareer-team.atlassian.net/browse/LC-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 로딩 중에는 버튼 disabled

---

src/api/file.ts
src/components/admin/program/ui/form/ImageUpload.tsx
src/components/admin/ui/heading/Heading2.tsx
src/components/ui/input/Input.tsx
src/pages/admin/ChallengeCreate.tsx
src/pages/admin/program/ChallengeBasic.tsx
src/pages/admin/program/ChallengePrice.tsx
src/pages/admin/program/ChallengeSchedule.tsx

- [[LC-815](https://letscareer-team.atlassian.net/browse/LC-815)]
[LC-815]: https://letscareer-team.atlassian.net/browse/LC-815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-815 ADMIN 2.1 프로그램 기본 정보 생성/수정

---

src/api/report.ts
src/pages/common/report/ReportApplyPage.tsx
src/pages/common/report/ReportPersonalStatementPage.tsx
src/pages/common/report/ReportPortfolioPage.tsx
src/pages/common/report/ReportResumePage.tsx

- [[LC-813](https://letscareer-team.atlassian.net/browse/LC-813)]
[LC-813]: https://letscareer-team.atlassian.net/browse/LC-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-813 USER 서류 진단 서비스/자기소개서 오류

---

src/components/common/home/new/review/ReviewSection.tsx

- [[LC-819](https://letscareer-team.atlassian.net/browse/LC-819)]
[LC-819]: https://letscareer-team.atlassian.net/browse/LC-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Style] object-contain 추가

---

src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/pages/admin/program/LiveMentor.tsx

- [[LC-821](https://letscareer-team.atlassian.net/browse/LC-821)]
[LC-821]: https://letscareer-team.atlassian.net/browse/LC-821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-821 ADMIN LIVE 생성/수정 요청하기

---

src/components/common/program/filter/FilterSideBar.tsx
src/components/common/program/programs/card/EmptyCardList.tsx
src/components/common/program/programs/card/ProgramCard.tsx
src/pages/common/program/Programs.tsx

- [[LC-762](https://letscareer-team.atlassian.net/browse/LC-762)]
[LC-762]: https://letscareer-team.atlassian.net/browse/LC-762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-762 USER 프로그램 페이지내 프로그램 카드 수정

---

src/api/challenge.ts
src/api/program.ts
src/pages/common/program/ChallengeDetailSSRPage.tsx
src/pages/common/program/LiveDetailSSRPage.tsx
src/schema.ts

- [[LC-780](https://letscareer-team.atlassian.net/browse/LC-780)]

LC-780 USER NEW 프로그램 상페 구성

---

src/components/common/home/new/program/ProgramSection.tsx

- [[LC-816](https://letscareer-team.atlassian.net/browse/LC-816)]
[LC-816]: https://letscareer-team.atlassian.net/browse/LC-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Chore] 홈 제목 두 줄로 수정

---

src/pages/admin/ChallengeCreate.tsx
src/pages/admin/ChallengeEdit.tsx
src/pages/admin/program/ChallengeCurriculum.tsx
src/types/interface.ts

- [[LC-793](https://letscareer-team.atlassian.net/browse/LC-793)]
[LC-793]: https://letscareer-team.atlassian.net/browse/LC-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-793 챌린지 커리큘럼 세션 추가

---

src/pages/admin/ChallengeCreate.tsx
src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/pages/admin/program/LiveCurriculum.tsx
src/types/interface.ts

- [[LC-793](https://letscareer-team.atlassian.net/browse/LC-793)]
[LC-793]: https://letscareer-team.atlassian.net/browse/LC-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-793 ADMIN LIVE 커리큘럼 추가

---

src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/schema.ts

- [[LC-820](https://letscareer-team.atlassian.net/browse/LC-820)]
[LC-820]: https://letscareer-team.atlassian.net/browse/LC-820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] LIVE VOD 제공 여부 추가

---

src/api/faq.ts
src/pages/admin/ChallengeCreate.tsx
src/pages/admin/ChallengeEdit.tsx
src/pages/admin/LiveEdit.tsx
src/pages/admin/program/ChallengeFaq.tsx
src/schema.ts

- [[LC-795](https://letscareer-team.atlassian.net/browse/LC-795)]
[LC-795]: https://letscareer-team.atlassian.net/browse/LC-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-795 ADMIN 챌린지 FAQ 추가

---

src/pages/admin/program/ChallengeCurriculum.tsx

- [[LC-793](https://letscareer-team.atlassian.net/browse/LC-793)]
[LC-793]: https://letscareer-team.atlassian.net/browse/LC-793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ADMIN 챌린지: [Fix] 커리큘럼 제목, 내용 textarea로 변경

---

pages/program/challenge/@id/+onRenderClient.tsx
pages/program/challenge/@id/+onRenderHtml.tsx
pages/program/live/@id/+onRenderClient.tsx
pages/program/live/@id/+onRenderHtml.tsx
renderer/+onRenderClient.tsx
renderer/+onRenderHtml.tsx
src/context/ServerChallenge.tsx
src/context/ServerLive.tsx
src/pages/common/program/ChallengeDetailSSRPage.tsx

- [LC-827]
[LC-827]: https://letscareer-team.atlassian.net/browse/LC-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-827 프로그램 상세 SSR 오류 수정

---

src/api/program.ts
src/components/common/program/banner/Banner.tsx
src/pages/admin/banner/program-banner/ProgramBannerCreate.tsx
src/pages/admin/banner/program-banner/ProgramBannerEdit.tsx
src/pages/admin/banner/program-banner/ProgramBanners.tsx
src/schema.ts

- [LC-823]
[LC-823]: https://letscareer-team.atlassian.net/browse/LC-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEV] LC-823 프로그램 배너 이슈 수정

---

src/components/admin/ui/heading/Heading3.tsx
src/pages/admin/ChallengeCreate.tsx
src/pages/admin/ChallengeEdit.tsx
src/pages/admin/program/ChallengePoint.tsx
src/types/interface.ts

- [[LC-829](https://letscareer-team.atlassian.net/browse/LC-829)]
[LC-829]: https://letscareer-team.atlassian.net/browse/LC-829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-829 챌린지 POINT 추가

---

src/components/ChallengeView.tsx
src/components/LiveView.tsx
src/components/admin/ChallengePreviewButton.tsx
src/components/admin/LivePreviewButton.tsx
src/components/admin/PreviewModal.tsx
src/context/ServerChallenge.tsx
src/context/ServerLive.tsx
src/pages/admin/ChallengeCreate.tsx
src/pages/admin/ChallengeEdit.tsx
src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/pages/common/program/ChallengeDetailSSRPage.tsx
src/pages/common/program/LiveDetailSSRPage.tsx

- [LC-777] 프로그램 상페 미리보기 기능
- ...
[LC-777]: https://letscareer-team.atlassian.net/browse/LC-777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-777 프로그램 상페 미리보기 기능

---

src/components/common/program/program-detail/Description.tsx
src/components/common/program/program-detail/Heading2.tsx
src/components/common/program/program-detail/OutlineBox.tsx
src/pages/common/program/ChallengeIntro.tsx

- [[LC-835](https://letscareer-team.atlassian.net/browse/LC-835)]

LC-835 USER 4.1 챌린지 소개 반응형 적용

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/common/program/program-detail/Box.tsx
src/components/common/program/program-detail/Description.tsx
src/components/common/program/program-detail/Heading2.tsx
src/components/common/program/program-detail/SuperTitle.tsx
src/pages/common/program/ChallengeCheckList.tsx
src/pages/common/program/ChallengeIntro.tsx

- [[LC-836](https://letscareer-team.atlassian.net/browse/LC-836)]
[LC-836]: https://letscareer-team.atlassian.net/browse/LC-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-836 USER 4.2 체크리스트 (정적값)

---

src/components/ChallengeView.tsx
src/pages/common/program/ChallengeCheckList.tsx
src/pages/common/program/ChallengeResult.tsx

- [[LC-830](https://letscareer-team.atlassian.net/browse/LC-830)]
[LC-830]: https://letscareer-team.atlassian.net/browse/LC-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-830 USER [챌린지] 4.3 결과물 (정적값)

---

src/Router.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/common/program/program-detail/apply/content/PaymentInputContent.tsx
src/components/common/program/program-detail/apply/section/PriceSection.tsx
src/components/common/program/program-detail/header/Header.tsx
src/components/common/program/program-detail/section/ApplySection.tsx
src/components/common/program/program-detail/section/MobileApplySection.tsx
src/components/common/ui/layout/channel/ChannelTalkBtn.tsx
src/lib/order.ts
src/pages/common/mypage/CreditDelete.tsx
src/pages/common/mypage/CreditDetail.tsx
src/pages/common/program/ChallengeDetailSSRPage.tsx
src/pages/common/program/LiveDetailSSRPage.tsx
src/pages/common/program/OrderProgramInfo.tsx
src/pages/common/program/Payment.tsx
src/pages/common/program/PaymentInputPage.tsx
src/store/useProgramStore.ts

- [LC-779]
- ...
[LC-779]: https://letscareer-team.atlassian.net/browse/LC-779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-779 결제 정보 입력 페이지 추가 및 로직 정리

---

src/components/admin/ui/heading/Heading2.tsx
src/pages/admin/ChallengeCreate.tsx
src/pages/admin/ChallengeEdit.tsx
src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/pages/admin/program/ChallengeBasic.tsx
src/pages/admin/program/ProgramBlogReviewEditor.tsx
src/pages/common/program/ProgramBlogReview.tsx
src/types/interface.ts

- [LC-801]
- ...
[LC-801]: https://letscareer-team.atlassian.net/browse/LC-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-801 ADMIN 블로그 후기(게시글)

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeNavigation.tsx

- [LC-782]
[LC-782]: https://letscareer-team.atlassian.net/browse/LC-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Sprint8] LC-782 프로그램 상페 네비게이션 바 추가

---

src/components/ChallengeView.tsx
src/pages/common/program/ChallengeCurriculum.tsx

- [[LC-822](https://letscareer-team.atlassian.net/browse/LC-822)]
[LC-822]: https://letscareer-team.atlassian.net/browse/LC-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-822 USER [챌린지] 5 커리큘럼

---

src/pages/admin/program/FaqSection.tsx
src/schema.ts

- [[LC-849](https://letscareer-team.atlassian.net/browse/LC-849)]
[LC-849]: https://letscareer-team.atlassian.net/browse/LC-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-849 ADMIN FAQ 유형 추가

---

src/api/challenge.ts
src/api/faq.ts
src/components/ChallengeView.tsx
src/pages/admin/program/FaqSection.tsx
src/pages/common/program/ChallengeFaq.tsx
src/pages/common/program/ChallengeIntro.tsx

- [[LC-824](https://letscareer-team.atlassian.net/browse/LC-824)]
[LC-824]: https://letscareer-team.atlassian.net/browse/LC-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-824 USER [챌린지] 10 FAQ (진행 중)

---

src/pages/common/program/ChallengeCurriculum.tsx
src/pages/common/program/ChallengeFaq.tsx

- [[LC-824](https://letscareer-team.atlassian.net/browse/LC-824)]
[LC-824]: https://letscareer-team.atlassian.net/browse/LC-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-824 USER [챌린지] 10 FAQ

---

public/icons/speech-bubble-icon.svg
src/components/LiveView.tsx
src/components/live-view/LiveMentor.tsx

- [[LC-791](https://letscareer-team.atlassian.net/browse/LC-791)]
[LC-791]: https://letscareer-team.atlassian.net/browse/LC-791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-791 USER [라이브] 2.3 멘토 소개

---

src/components/admin/OutlinedTextarea.tsx
src/pages/admin/LiveEdit.tsx
src/pages/admin/program/FaqSection.tsx
src/pages/admin/program/LiveCurriculum.tsx
src/pages/admin/program/LiveMentor.tsx
src/pages/admin/program/ProgramBlogReviewEditor.tsx
src/types/interface.ts

- [LC-862]
[LC-862]: https://letscareer-team.atlassian.net/browse/LC-862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-862 ADMIN 멘토 경력, 한 줄 소개 textarea로 변경 + ADMIN 라이브 content 초기화

---

src/api/program.ts
src/components/LiveView.tsx
src/components/challenge-view/ChallengeFaq.tsx
src/components/common/ui/layout/channel/ChannelTalkBtn.tsx
src/components/live-view/LiveFaq.tsx
src/components/live-view/LiveVod.tsx
src/pages/admin/program/FaqSection.tsx

- [[LC-848](https://letscareer-team.atlassian.net/browse/LC-848)]
- [[LC-861](https://letscareer-team.atlassian.net/browse/LC-861)]
[LC-848]: https://letscareer-team.atlassian.net/browse/LC-848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LC-861]: https://letscareer-team.atlassian.net/browse/LC-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-848 USER [라이브] 2.7 FAQ + 문의 버튼 클릭 시 채널톡 오픈

---

src/components/admin/ui/heading/Heading2.tsx
src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/types/interface.ts

- [LC-865]
[LC-865]: https://letscareer-team.atlassian.net/browse/LC-865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-865 ADMIN 3.3.2 [라이브] 커리큘럼 추가 입력

---

src/components/LiveView.tsx

- [LC-866]
[LC-866]: https://letscareer-team.atlassian.net/browse/LC-866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-866 USER 2.5.2 [라이브] 커리큘럼 추가 입력

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeIntro.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/common/program/program-detail/Heading2.tsx

- [LC-870]
[LC-870]: https://letscareer-team.atlassian.net/browse/LC-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-870 챌린지 포인트 스타일 수정

---

src/components/ChallengeView.tsx
src/components/LiveView.tsx
src/components/challenge-view/ChallengeCheckList.tsx
src/components/challenge-view/ChallengeCurriculum.tsx
src/components/challenge-view/ChallengeFaq.tsx
src/components/challenge-view/ChallengeIntro.tsx
src/components/challenge-view/ChallengeResult.tsx
src/components/common/program/program-detail/Description.tsx
src/components/common/program/program-detail/Heading2.tsx
src/components/common/program/program-detail/SuperTitle.tsx
src/components/live-view/LiveCurriculum.tsx
src/components/live-view/LiveFaq.tsx
src/components/live-view/LiveMentor.tsx
src/components/live-view/LiveVod.tsx

- [LC-872]
[LC-872]: https://letscareer-team.atlassian.net/browse/LC-872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-872 USER 컴포넌트 breakpoint, padding 조정

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengePointView.tsx
src/schema.ts

- [LC-857]
[LC-857]: https://letscareer-team.atlassian.net/browse/LC-857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-857 챌린지 타입에 따라 색상 객체 생성

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengePointView.tsx

- [LC-857]
[LC-857]: https://letscareer-team.atlassian.net/browse/LC-857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 챌린지 색상 타입 수정

---

src/components/ChallengeView.tsx
src/components/LiveView.tsx
src/components/ProgramDetailNavigation.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/common/program/program-detail/basicInfo/BasicInfoBottomRow.tsx
src/components/live-view/LiveBasicInfo.tsx
src/components/live-view/LiveInfoBottom.tsx
src/utils/formatDateString.ts

- [LC-800]
[LC-800]: https://letscareer-team.atlassian.net/browse/LC-800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Sprint8] LC-800 상페 하단 모집개요/가격정보

---

src/assets/bubble_tail.svg
src/components/LiveView.tsx
src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/live-view/LiveBasicInfo.tsx
src/components/live-view/LiveInformation.tsx
src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/pages/admin/program/LiveInformation.tsx
src/types/interface.ts

- [LC-792]
[LC-792]: https://letscareer-team.atlassian.net/browse/LC-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-792 어드민/유저 라이브클래스 소개 섹션 추가

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeCheckList.tsx
src/components/common/program/program-detail/Box.tsx
src/components/common/program/program-detail/OutlineBox.tsx
src/components/common/program/program-detail/SuperTitle.tsx

- [LC-874]
[LC-874]: https://letscareer-team.atlassian.net/browse/LC-874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-874 챌린지 체크리스트 상태 별 구분

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeResult.tsx
src/components/common/program/program-detail/OutlineBox.tsx

- [LC-874]
[LC-874]: https://letscareer-team.atlassian.net/browse/LC-874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-874 챌린지 타입별 결과물 구분 (사진 추가 예정)

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeCurriculum.tsx

- [LC-856]
[LC-856]: https://letscareer-team.atlassian.net/browse/LC-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-856 (디자인수정) USER [챌린지] 5 커리큘럼

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeFaq.tsx

- [LC-880]
[LC-880]: https://letscareer-team.atlassian.net/browse/LC-880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-880 USER 챌린지 10 FAQ 타입별 구분

---

src/pages/admin/program/FaqSection.tsx

- [LC-889]
[LC-889]: https://letscareer-team.atlassian.net/browse/LC-889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-889 ADMIN FAQ 로직 수정

---

src/pages/admin/program/FaqSection.tsx

- [LC-896]
[LC-896]: https://letscareer-team.atlassian.net/browse/LC-896?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-896 [ADMIN] FAQ 미리 선택되어있으면 좋겠음

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeResult.tsx

- [LC-925]
[LC-925]: https://letscareer-team.atlassian.net/browse/LC-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-925 after 그라데이션 적용

---

src/api/program.ts
src/components/common/program/banner/Banner.tsx
src/pages/admin/banner/program-banner/ProgramBannerCreate.tsx
src/pages/admin/banner/program-banner/ProgramBannerEdit.tsx
src/pages/admin/banner/program-banner/ProgramBanners.tsx
src/schema.ts

- [LC-823]
[LC-823]: https://letscareer-team.atlassian.net/browse/LC-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LC-823] 프로그램 배너 개선

---

src/components/ChallengeView.tsx
src/components/challenge-view/ChallengeCheckList.tsx
src/components/challenge-view/ChallengeIntroPortfolio.tsx

LC-936 USER [챌린지] 포트폴리오 디자인 수정

---

src/components/ChallengeView.tsx
src/components/ProgramBestReviewSection.tsx
src/components/ProgramDetailBlogReviewSection.tsx
src/components/challenge-view/ChallengeCurriculum.tsx
src/components/challenge-view/ChallengeDifferent.tsx
src/components/challenge-view/ChallengeFaq.tsx
src/components/challenge-view/ChallengeInfoBottom.tsx
src/components/challenge-view/ChallengePointView.tsx

- [LC-938]
[LC-938]: https://letscareer-team.atlassian.net/browse/LC-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-938 USER 챌린지 페딩, 너비 정리

---

src/components/ChallengeView.tsx
src/components/LiveView.tsx
src/components/ProgramBestReviewSection.tsx
src/components/ProgramDetailBlogReviewSection.tsx
src/components/challenge-view/ChallengePointView.tsx
src/components/common/program/program-detail/review/ProgramDetailReviewItem.tsx
src/components/live-view/LiveCurriculum.tsx
src/components/live-view/LiveFaq.tsx
src/components/live-view/LiveInfoBottom.tsx
src/components/live-view/LiveInformation.tsx
src/components/live-view/LiveIntro.tsx
src/components/live-view/LiveMentor.tsx

- [LC-742]
[LC-742]: https://letscareer-team.atlassian.net/browse/LC-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-742 Sprint8 개발내용 머지

---

src/components/challenge-view/ChallengeBasicInfo.tsx

- [LC-943]
[LC-943]: https://letscareer-team.atlassian.net/browse/LC-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-943 챌린지 가격 수정

---

src/components/challenge-view/ChallengeBasicInfo.tsx

- [LC-943]
[LC-943]: https://letscareer-team.atlassian.net/browse/LC-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 정가에 보증금 포함

---

src/components/LiveView.tsx
src/components/live-view/LiveCurriculum.tsx
src/pages/admin/LiveCreate.tsx
src/pages/admin/LiveEdit.tsx
src/pages/admin/program/LiveCurriculum.tsx
src/types/interface.ts

- [LC-946]
[LC-946]: https://letscareer-team.atlassian.net/browse/LC-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-946 [USER&ADMIN] LIVE 클래스 커리큘럼 제목 입력란 추가

---

src/components/common/program/program-detail/apply/section/UserInputSection.tsx
src/pages/common/program/PaymentInputPage.tsx

- [LC-952]
[LC-952]: https://letscareer-team.atlassian.net/browse/LC-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Feat] 챌린지 할부 배너 추가

---

src/components/challenge-view/ChallengeBasicInfo.tsx

- [LC-942]
[LC-942]: https://letscareer-team.atlassian.net/browse/LC-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-942 챌린지 기본 정보, 스타일 수정

---

src/components/ChallengeView.tsx
src/components/LiveView.tsx
src/components/ProgramBestReviewSection.tsx
src/components/ProgramDetailBlogReviewSection.tsx
src/components/challenge-view/ChallengeFaq.tsx
src/components/common/program/program-detail/different/BenefitCard.tsx
src/components/live-view/LiveInformation.tsx
src/components/live-view/LiveIntro.tsx

- [LC-945]
[LC-945]: https://letscareer-team.atlassian.net/browse/LC-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-945 혜택 카드 스타일 수정

---

src/components/common/FloatingNotification.tsx
src/pages/common/program/ProgramDetailLegacy.tsx

- [LC-950]
[LC-950]: https://letscareer-team.atlassian.net/browse/LC-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-950 인스타그램 결제 방지 컴포넌트 분리

---

src/components/challenge-view/ChallengeBasicInfo.tsx
src/components/challenge-view/ChallengeBrand.tsx
src/components/challenge-view/ChallengeCurriculum.tsx
src/components/challenge-view/ChallengeDifferent.tsx
src/components/challenge-view/ChallengeIntroCareerStart.tsx

- [LC-970]
[LC-970]: https://letscareer-team.atlassian.net/browse/LC-970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-970 USER 맞춤법 및 띄어쓰기, 줄바꿈

---

src/components/challenge-view/ChallengeResult.tsx

- [LC-971]
[LC-971]: https://letscareer-team.atlassian.net/browse/LC-971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-971 좌우 스크롤 구분

---

src/pages/common/program/ChallengeDetailSSRPage.tsx
src/pages/common/program/LiveDetailSSRPage.tsx

- [LC-949]
[LC-949]: https://letscareer-team.atlassian.net/browse/LC-949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Fix] 모바일 cta가 먼저 뜨도록 수정

---

src/components/challenge-view/ChallengeIntroPortfolio.tsx

- [LC-973]
[LC-973]: https://letscareer-team.atlassian.net/browse/LC-973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LC-973 포폴 소개 워딩 수정
